"""Execution + comparison engine for the R4 frozen scenarios (D-80 R4).

Executes the scenarios `scenario_defs.py` authors and compares the results
against the frozen baselines `manifest.json` declares. Consumed by
`python/tests/necb/test_frozen_scenarios.py` (the CI gate) and by
`freeze.py` (which adds the Ruby seal, double-run determinism, provenance,
and the atomic write).

Strictness contract (the frozen suite must never go green-but-vacuous):
- every manifest-declared baseline file must EXIST and match its sha256
  before any comparison runs;
- a CLI scenario's run dir must contain EXACTLY the declared file set —
  undeclared extras fail too;
- stream normalization substitutes the LONGEST path first and refuses to
  run if a placeholder token already occurs in the raw output;
- newlines are canonicalized (CRLF/CR -> LF) before exact comparison;
- subprocess environments are CONSTRUCTED (infrastructure allowlist +
  authored overlay), never inherited — host HBIX_* can never leak in.
"""

from __future__ import annotations

import hashlib
import importlib.util
import io
import json
import os
import shutil
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO_ROOT = HERE.parents[1]
PYTHON_ROOT = REPO_ROOT / "python"
EPW = (PYTHON_ROOT / "tests" / "fixtures" / "weather"
       / "CAN_ON_Toronto.Intl.AP.716240_CWEC2020.epw")
SEED = REPO_ROOT / "verification" / "oracle" / "fixtures" / "5ZoneNoHVAC.osm"
MANIFEST = HERE / "manifest.json"
BASELINES = HERE / "baselines"

DEFAULT_TIMEOUT_S = 600

#: The interpreter scenario subprocesses run under: BTAP_PYTHON wins, then
#: the repo venv (local dev — it carries the openstudio wheel), then
#: whatever is running this code (CI venvs: the wheel is already there).
def python_exe():
    if os.environ.get("BTAP_PYTHON"):
        return os.environ["BTAP_PYTHON"]
    venv = PYTHON_ROOT / ".venv" / "bin" / "python"
    return str(venv) if venv.exists() else sys.executable

#: Infrastructure vars a scenario subprocess may inherit — everything else
#: comes from the scenario's authored env. HBIX_* is deliberately absent.
ENV_ALLOWLIST = ("PATH", "HOME", "TMPDIR", "BTAP_ENERGYPLUS",
                 "BTAP_ENERGYPLUS_ARCHIVE", "SYSTEMROOT",
                 # relocatable interpreters (actions/setup-python's
                 # tool-cache build) find their shared libpython via this
                 "LD_LIBRARY_PATH",
                 # the Ruby side of the freeze-time seal loads the SDK via
                 # these; harmless for Python subprocesses
                 "RUBYLIB", "GEM_HOME", "GEM_PATH")


def sha256(path):
    return hashlib.sha256(Path(path).read_bytes()).hexdigest()


def load_manifest():
    return json.loads(MANIFEST.read_text(encoding="utf-8"))


def load_compare_runs():
    spec = importlib.util.spec_from_file_location(
        "compare_runs", REPO_ROOT / "verification" / "compare_runs.py")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


# ---------------------------------------------------------------- corpus

def ensure_corpus(scratch):
    """Generate the Python sample corpus once per scratch root, stamped and
    slug-asserted both directions (the run_corpus.rb contract, ported)."""
    corpus = Path(scratch) / "_samples"
    marker = corpus / ".generated_by"
    expected = sorted(json.loads(
        (PYTHON_ROOT / "scripts" / "sample_manifest.json")
        .read_text(encoding="utf-8"))["samples"])
    if corpus.exists() and any(corpus.glob("*.osm")):
        stamped = marker.read_text(encoding="utf-8").strip() if marker.exists() else None
        if stamped != "python":
            who = repr(stamped) if stamped else "an unknown generator"
            raise RuntimeError(
                f"corpus at {corpus} was generated by {who} — "
                "delete it or use a fresh scratch root")
    else:
        proc = subprocess.run(
            [python_exe(), str(PYTHON_ROOT / "scripts" / "generate_samples.py"),
             str(corpus)],
            capture_output=True, text=True,
            env=build_env({}, {}),  # prepends inherited PYTHONPATH (CI SDK)
            check=False)
        if proc.returncode != 0:
            raise RuntimeError(f"sample generation failed:\n{proc.stderr[-2000:]}")
    actual = sorted(p.stem for p in corpus.glob("*.osm"))
    if actual != expected:
        raise RuntimeError(
            "corpus does not match sample_manifest.json:\n"
            f"  missing: {sorted(set(expected) - set(actual))}\n"
            f"  extra:   {sorted(set(actual) - set(expected))}")
    marker.write_text("python\n", encoding="utf-8")
    return corpus


def lone_epw(scratch):
    """An EPW with NO ddy sibling (the usage-missing-ddy trigger)."""
    dest = Path(scratch) / "lone" / EPW.name
    dest.parent.mkdir(parents=True, exist_ok=True)
    if not dest.exists():
        shutil.copyfile(EPW, dest)
    return dest


# ---------------------------------------------------------- environment

def _base_env():
    env = {k: os.environ[k] for k in ENV_ALLOWLIST if k in os.environ}
    env["LANG"] = env["LC_ALL"] = "C.UTF-8"
    # The openstudio bindings print FutureWarnings to stderr with the
    # importing environment's ABSOLUTE site path (venv locally, the image
    # Python tree in CI) — unfreezable noise that is never product output.
    # Suppressed at the source so frozen streams are environment-portable.
    env["PYTHONWARNINGS"] = "ignore::FutureWarning"
    return env


def build_env(scenario, resolved_env):
    env = _base_env()
    # PREPEND, never clobber: in the CI containers the openstudio SDK
    # arrives via the caller's PYTHONPATH (no wheel there) — the same rule
    # run_corpus.rb documented.
    inherited = os.environ.get("PYTHONPATH")
    env["PYTHONPATH"] = (str(PYTHON_ROOT) + os.pathsep + inherited
                         if inherited else str(PYTHON_ROOT))
    env.update(resolved_env)
    return env


# --------------------------------------------------------- placeholders

def resolve(value, ctx):
    for token, repl in ctx.items():
        value = value.replace(token, str(repl))
    return value


def make_ctx(run_dir, corpus, lone):
    return {"<RUN_DIR>": run_dir, "<ROOT>": REPO_ROOT, "<EPW>": EPW,
            "<SEED>": SEED, "<CORPUS>": corpus, "<LONE_EPW>": lone}


# -------------------------------------------------------- normalization

def normalize(text, run_dir, scratch=None):
    text = text.replace("\r\n", "\n").replace("\r", "\n")
    tokens = ["<RUN_DIR>", "<ROOT>"] + (["<SCRATCH>"] if scratch else [])
    for token in tokens:
        if token in text:
            raise RuntimeError(
                f"raw output already contains the placeholder {token} — "
                "normalization would be ambiguous")
    # Longest path first: a run dir under the repo root (or the scratch
    # root) must not have its prefix rewritten out from under it.
    subs = [(str(run_dir), "<RUN_DIR>"), (str(REPO_ROOT), "<ROOT>")]
    if scratch:
        subs.append((str(scratch), "<SCRATCH>"))
    subs.sort(key=lambda pair: len(pair[0]), reverse=True)
    for real, token in subs:
        text = text.replace(real, token)
    return text


# ------------------------------------------------------------ execution

class ScenarioRun:
    def __init__(self, exit_code, stdout, stderr, run_dir, scratch=None):
        self.exit_code = exit_code
        self.stdout = stdout
        self.stderr = stderr
        self.run_dir = run_dir
        self.scratch = scratch


def execute(scenario, run_dir, ctx):
    kind = scenario["kind"]
    if kind == "cli":
        run = _execute_cli(scenario, run_dir, ctx)
        run.scratch = _scratch_of(ctx)
        return run
    if kind == "api":
        return _execute_api(scenario, run_dir)
    if kind == "audit-unit":
        return _execute_audit_unit(run_dir)
    if kind == "verdict-unit":
        return _execute_verdict_unit(scenario, run_dir)
    raise ValueError(f"unknown scenario kind {kind!r}")


def _execute_cli(scenario, run_dir, ctx, argv0=None):
    argv = [resolve(a, ctx) for a in scenario["argv"]]
    env = build_env(scenario,
                    {k: resolve(v, ctx) for k, v in scenario["env"].items()})
    cmd = argv0 or [python_exe(), "-m", "btap.necb.cli"]
    proc = subprocess.run(
        [*cmd, *argv], capture_output=True, text=True, env=env,
        cwd=str(REPO_ROOT), timeout=scenario.get("timeout_s", DEFAULT_TIMEOUT_S),
        check=False)
    return ScenarioRun(proc.returncode, proc.stdout, proc.stderr, run_dir)


def _scratch_of(ctx):
    lone = ctx.get("<LONE_EPW>")
    return Path(lone).parents[1] if lone else None


def _sys_path_python():
    if str(PYTHON_ROOT) not in sys.path:
        sys.path.insert(0, str(PYTHON_ROOT))


def _execute_api(scenario, run_dir):
    _sys_path_python()
    from btap.necb import performance_compliance
    from tests.necb.support import compliance_fixture

    performance_compliance(compliance_fixture(), run_dir=str(run_dir),
                           **scenario["api_call"])
    return ScenarioRun(None, "", "", run_dir)


def _execute_audit_unit(run_dir):
    _sys_path_python()
    spec = importlib.util.spec_from_file_location(
        "audit_scenario", HERE / "audit_scenario.py")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    audit = module.build_scenario()
    run_dir = Path(run_dir)
    (run_dir / "audit.json").write_text(audit.to_json(), encoding="utf-8")
    (run_dir / "audit.txt").write_text(str(audit), encoding="utf-8")
    return ScenarioRun(None, "", "", run_dir)


def _execute_verdict_unit(scenario, run_dir):
    _sys_path_python()
    from types import SimpleNamespace

    from btap.necb import cli

    report = {
        "annual": True, "vintage": "2020", "hdd": 3890, "tier": 1,
        "percent_of_target": 90.1 if scenario["compliant"] else 109.9,
        "proposed": {"total_site_kwh": 2725.0, "eui_kwh_per_m2": 3.4,
                     "floor_area_m2": 800.0,
                     "unmet_occupied_hours": {"heating": 0.8, "cooling": 13.5},
                     "clean_run": True},
        "reference": {"total_site_kwh": 3025.0 if scenario["compliant"] else 2478.0,
                      "eui_kwh_per_m2": 3.8 if scenario["compliant"] else 3.1,
                      "floor_area_m2": 800.0,
                      "unmet_occupied_hours": {"heating": 24.8, "cooling": 0.0},
                      "clean_run": True},
    }
    result = SimpleNamespace(compliant=scenario["compliant"], report=report,
                             run_dir=str(run_dir), audit=None)
    out = io.StringIO()
    cli.emit(result, {"json": False, "report_html": False}, out)
    return ScenarioRun(cli.verdict_exit(result), out.getvalue(), "", run_dir)


# ------------------------------------------------------------ comparison

def verify_baselines(scenario, manifest):
    """Every declared baseline exists and matches its manifest sha256."""
    problems = []
    base = BASELINES / scenario["id"]
    declared = scenario.get("baseline_sha256", {})
    if not declared and _compared_names(scenario):
        problems.append(f"{scenario['id']}: no baselines recorded in the "
                        "manifest — was this scenario ever frozen?")
    for name, digest in declared.items():
        path = base / name
        if not path.is_file():
            problems.append(f"{scenario['id']}: baseline {name} is MISSING "
                            f"({path}) — never fall back to a silent pass")
        elif sha256(path) != digest:
            problems.append(f"{scenario['id']}: baseline {name} does not "
                            "match its manifest sha256 — hand-edited?")
    if base.is_dir():
        extras = {p.name for p in base.iterdir() if p.is_file()} - set(declared)
        if extras:
            problems.append(f"{scenario['id']}: undeclared file(s) in the "
                            f"baseline dir: {sorted(extras)} — frozen "
                            "directories are exact sets, like live run dirs")
    return problems


def _compared_names(scenario):
    names = list(scenario.get("files", [])) + list(scenario.get("text_files", {}))
    for stream in ("stdout", "stderr"):
        if scenario.get("streams", {}).get(stream) == "exact":
            names.append(f"{stream}.txt")
    return names


def compare(scenario, run, spec, cr):
    problems = []
    base = BASELINES / scenario["id"]
    run_dir = Path(run.run_dir) if run.run_dir else None

    if scenario.get("expect_exit") is not None and run.exit_code != scenario["expect_exit"]:
        problems.append(f"{scenario['id']}: exit {run.exit_code}, expected "
                        f"{scenario['expect_exit']}\nstderr: {run.stderr[-800:]}")

    if scenario.get("no_run_dir"):
        if run_dir and run_dir.exists() and any(run_dir.iterdir()):
            problems.append(f"{scenario['id']}: expected NO artifacts, found "
                            f"{[p.name for p in run_dir.iterdir()]}")
    elif run_dir:
        expected = set(scenario.get("expected_run_files")
                       or (list(scenario.get("files", []))
                           + list(scenario.get("text_files", {}))))
        if expected:
            actual = {p.name for p in run_dir.iterdir() if p.is_file()}
            if actual != expected:
                problems.append(
                    f"{scenario['id']}: run dir holds {sorted(actual)}, "
                    f"declared {sorted(expected)} — extras and absences both "
                    "fail (freeze what you emit)")

    for name in scenario.get("files", []):
        diffs = []
        cr.compare_file(str(base), str(run.run_dir), name, spec, diffs)
        problems.extend(f"{scenario['id']}: {d}" for d in diffs)

    for name, mode in scenario.get("text_files", {}).items():
        baseline = (base / name).read_text(encoding="utf-8") if (base / name).is_file() else None
        live_path = Path(run.run_dir) / name
        live = live_path.read_text(encoding="utf-8") if live_path.is_file() else None
        if baseline is None or live is None:
            problems.append(f"{scenario['id']}: {name} missing on "
                            f"{'baseline' if baseline is None else 'live'} side")
            continue
        if mode == "normalized":
            baseline_n, live_n = baseline, normalize(live, run.run_dir, run.scratch)
        else:
            baseline_n, live_n = baseline, live.replace("\r\n", "\n").replace("\r", "\n")
        if baseline_n != live_n:
            problems.append(f"{scenario['id']}: {name} differs from the "
                            f"frozen baseline ({mode})")

    for stream in ("stdout", "stderr"):
        mode = scenario.get("streams", {}).get(stream)
        live = getattr(run, stream)
        if mode == "exact":
            frozen = (base / f"{stream}.txt")
            if not frozen.is_file():
                problems.append(f"{scenario['id']}: frozen {stream} missing")
                continue
            if frozen.read_text(encoding="utf-8") != normalize(live, run.run_dir or "<none>", run.scratch):
                problems.append(f"{scenario['id']}: {stream} differs from "
                                "the frozen stream")
        frags = scenario.get("fragments", {}).get(stream, {})
        for needle in frags.get("required", []):
            if needle not in live:
                problems.append(f"{scenario['id']}: {stream} lacks required "
                                f"fragment {needle!r}")
        for needle in frags.get("forbidden", []):
            if needle in live:
                problems.append(f"{scenario['id']}: {stream} contains "
                                f"forbidden fragment {needle!r}")

    frag_files = scenario.get("fragments", {})
    for name, frags in frag_files.items():
        if name in ("stdout", "stderr"):
            continue
        path = Path(run.run_dir) / name
        content = path.read_text(encoding="utf-8") if path.is_file() else ""
        for needle in frags.get("required", []):
            if needle not in content:
                problems.append(f"{scenario['id']}: {name} lacks required "
                                f"fragment {needle!r}")

    for assertion in scenario.get("byte_asserts", []):
        path = Path(run.run_dir) / assertion["file"]
        actual = path.read_text(encoding="utf-8") if path.is_file() else None
        if actual != assertion["equals"]:
            got = repr(actual)[:60]
            problems.append(f"{scenario['id']}: {assertion['file']} != "
                            f"{assertion['equals']!r} (got {got})")
    return problems
