#!/usr/bin/env ruby
# frozen_string_literal: true

# Leg-B corpus runner (D-78): drive a btap-compliance CLI over the committed
# corpus deterministically, so two invocations — two Ruby passes, or one Ruby
# and one PYTHON pass — produce comparable run directories for
# compare_runs.py.
#
#   ruby verification/run_corpus.rb OUT_ROOT [--tier none|sizing|annual] \
#     [--cli ruby|python] [--samples-gen ruby|python]
#
# --cli python (M6) drives the Python port's CLI (python -m btap.necb.cli)
# over the SAME models with the SAME arguments; PYTHON_CLI names the
# interpreter (default: python/.venv/bin/python if present, else python3).
# --samples-gen selects WHICH implementation generates the corpus models
# (D-80 R2: the 2x2 generator/CLI matrix needs both) — the generated slug
# set is asserted against python/scripts/sample_manifest.json in both
# directions either way, and the run count is asserted per tier, so a
# generator that silently shrinks the corpus fails loudly.
#
# Corpus v1: the 17 generated installer samples (regenerated on demand — they
# are derived artifacts, never committed) + the raw 5-zone fixture driven
# through the space-type on-ramp. Tier `none` runs every model with
# --simulate none (fast; full reference-transform + rules coverage); tier
# `sizing` runs a subset through real E+ sizing (needs the openstudio CLI —
# or, for the Python side, the provisioned engine).
require 'fileutils'
require 'rbconfig'

ROOT = File.expand_path('..', __dir__)
OUT_ROOT = ARGV[0] or abort('usage: run_corpus.rb OUT_ROOT [--tier none|sizing|annual] [--cli ruby|python]')
TIER = ARGV.include?('--tier') ? ARGV[ARGV.index('--tier') + 1] : 'none'
CLI_KIND = ARGV.include?('--cli') ? ARGV[ARGV.index('--cli') + 1] : 'ruby'
abort("unknown --cli #{CLI_KIND} (ruby|python)") unless %w[ruby python].include?(CLI_KIND)
SAMPLES_GEN = ARGV.include?('--samples-gen') ? ARGV[ARGV.index('--samples-gen') + 1] : 'ruby'
abort("unknown --samples-gen #{SAMPLES_GEN} (ruby|python)") unless %w[ruby python].include?(SAMPLES_GEN)
CLI = File.join(ROOT, 'btap-necb/exe/btap-compliance.rb')
DEFAULT_VENV = File.join(ROOT, 'python/.venv/bin/python')
PYTHON = ENV['PYTHON_CLI'] || (File.exist?(DEFAULT_VENV) ? DEFAULT_VENV : 'python3')
SAMPLES = File.join(OUT_ROOT, '_samples')

# Samples are generated, not committed — build them once per corpus root.
# The generator's identity is stamped beside them: reusing a corpus that a
# DIFFERENT implementation generated would silently turn a generator-
# equivalence cell into a same-generator one (post-merge review, finding 6).
GEN_MARKER = File.join(SAMPLES, '.generated_by')
if File.exist?(File.join(SAMPLES, '01-baseboard-gas.osm'))
  stamped = File.exist?(GEN_MARKER) ? File.read(GEN_MARKER).strip : nil
  unless stamped == SAMPLES_GEN
    abort("corpus at #{SAMPLES} was generated by #{stamped ? stamped.inspect : 'an unknown generator'} " \
          "but --samples-gen #{SAMPLES_GEN} was requested — delete it or use a fresh OUT_ROOT")
  end
else
  puts "generating the sample corpus (#{SAMPLES_GEN})…"
  gen_ok = if SAMPLES_GEN == 'python'
             env = { 'PYTHONPATH' => [File.join(ROOT, 'python'), ENV['PYTHONPATH']].compact.join(File::PATH_SEPARATOR) }
             system(env, PYTHON, File.join(ROOT, 'python/scripts/generate_samples.py'), SAMPLES,
                    out: File::NULL, err: File::NULL)
           else
             system(RbConfig.ruby, File.join(ROOT, 'btap-necb/scripts/generate_samples.rb'), SAMPLES,
                    out: File::NULL, err: File::NULL)
           end
  gen_ok or abort("sample generation (#{SAMPLES_GEN}) failed")
  generated_this_run = true
end

# The exact-corpus contract (D-80 R2): the generated slug set must equal the
# committed manifest in BOTH directions — a generator that drops, renames, or
# invents a sample fails here, not as a silently smaller diff downstream.
require 'json'
EXPECTED_SLUGS = JSON.parse(File.read(File.join(ROOT, 'python/scripts/sample_manifest.json')))['samples'].sort
actual_slugs = Dir.glob(File.join(SAMPLES, '*.osm')).map { |m| File.basename(m, '.osm') }.sort
unless actual_slugs == EXPECTED_SLUGS
  abort("corpus does not match sample_manifest.json:\n" \
        "  missing: #{(EXPECTED_SLUGS - actual_slugs).inspect}\n" \
        "  extra:   #{(actual_slugs - EXPECTED_SLUGS).inspect}")
end
# Stamp only AFTER the exact-set contract holds: a generator that exits 0
# with an incomplete corpus leaves the directory UNSTAMPED, so the next run
# refuses it with the delete-and-regenerate message instead of repeatedly
# reusing a stamped-but-invalid corpus.
File.write(GEN_MARKER, "#{SAMPLES_GEN}\n") if defined?(generated_this_run) && generated_this_run

# The shared fixture weather trio (epw/ddy/stat beside each other) — the
# simulating tiers need it; the committed corpus args carried no --epw, so
# tier `sizing` had never actually run (exit 2 at the CLI's usage guard).
WEATHER = File.join(ROOT, 'btap-modeling/test/fixtures/weather/CAN_ON_Toronto.Intl.AP.716240_CWEC2020.epw')
BASE_ARGS = ['--hdd', '3890', '--storeys', '1', '--no-report', '--quiet'].freeze
FIXTURE_ARGS = (BASE_ARGS + ['--space-type', 'Space Function/Office enclosed > 25 m2']).freeze
SIZING_SUBSET = %w[01-baseboard-gas 02-psz-gas-dx 09-water-source-hp].freeze
# Tier `annual` is `--simulate annual --quick` (a one-week run period): the
# full determination arithmetic incl. unmet hours and the 8.4.1.2.(2)-(4)
# verdict entries, exit 6 by design (a shortened period is never a
# determination). Two models, per the M6 acceptance.
ANNUAL_SUBSET = %w[01-baseboard-gas 02-psz-gas-dx].freeze

runs = Dir.glob(File.join(SAMPLES, '*.osm')).sort.map { |m| [File.basename(m, '.osm'), m, BASE_ARGS] }
runs << ['5zone-onramp', File.join(ROOT, 'btap-modeling/lib/btap_modeling/hvac/data/5ZoneNoHVAC.osm'), FIXTURE_ARGS]
runs.select! { |name, _, _| SIZING_SUBSET.include?(name) } if TIER == 'sizing'
runs.select! { |name, _, _| ANNUAL_SUBSET.include?(name) } if TIER == 'annual'

failures = []
runs.each do |name, model, args|
  out_dir = File.join(OUT_ROOT, TIER, name)
  FileUtils.mkdir_p(out_dir)
  simulate_args = TIER == 'annual' ? ['--simulate', 'annual', '--quick'] : ['--simulate', TIER]
  simulate_args += ['--epw', WEATHER] unless TIER == 'none'
  cmd = if CLI_KIND == 'python'
          [PYTHON, '-m', 'btap.necb.cli', model, *simulate_args, *args, '-o', out_dir]
        else
          [RbConfig.ruby, CLI, model, *simulate_args, *args, '-o', out_dir]
        end
  # Prepend, never clobber: in the SDK container the openstudio bindings
  # arrive via the CALLER's PYTHONPATH (no wheel there).
  env = if CLI_KIND == 'python'
          { 'PYTHONPATH' => [File.join(ROOT, 'python'), ENV['PYTHONPATH']].compact.join(File::PATH_SEPARATOR) }
        else
          {}
        end
  ok = system(env, *cmd, out: File.join(out_dir, 'stdout.log'), err: %i[child out])
  # --simulate none/sizing exit 6 (no determination) BY DESIGN; only crashes
  # (nil exitstatus) and internal errors (5) are failures here.
  code = Process.last_status&.exitstatus
  audit_written = File.exist?(File.join(out_dir, 'audit.json'))
  failures << "#{name} (exit #{code.inspect}, audit=#{audit_written})" unless ok || (code == 6 && audit_written)
  puts format('  %-24s exit %-3s %s', name, code.inspect, audit_written ? 'audit.json ok' : 'NO AUDIT')
end

abort("corpus failures: #{failures.join(', ')}") unless failures.empty?

# Run-count contract per tier (the silent-shrink hazard): a subset name that
# stops matching a generated sample would otherwise just shrink the corpus.
expected_runs = { 'none' => EXPECTED_SLUGS.size + 1,
                  'sizing' => SIZING_SUBSET.size,
                  'annual' => ANNUAL_SUBSET.size }.fetch(TIER)
unless runs.size == expected_runs
  abort("tier #{TIER} ran #{runs.size} models, expected #{expected_runs} — " \
        'a corpus subset silently shrank')
end
puts "corpus complete: #{runs.size}/#{expected_runs} runs under #{File.join(OUT_ROOT, TIER)}"
