#!/usr/bin/env ruby
# frozen_string_literal: true

# Regenerates NECB_GEM_COVERAGE.md — the family-wide rollup of every domain
# gem's NECB article_coverage manifest. Deterministic: sorted by gem then
# article, 2020/2025 rows that differ only by the 8.4.4<->8.4.5 renumbering are
# merged into one row citing both vintages.
#
#   ruby scripts/generate_necb_gem_coverage.rb
#
# Run from the repo root. Reads openstudio-*/lib/**/data/necb/*_rules_*.json.

require 'json'

ROOT = File.expand_path('../..', __dir__)
# openstudio-necb (the umbrella) declares the pipeline-level articles no domain
# gem can: the 8.4.1.2 determination itself, calculation methods, the 2025 EUI
# path. CAVEAT: unlike the domain gems, the umbrella has no runtime
# emit_article_coverage yet, so its partial/not_implemented entries do NOT warn
# on every run — they are declaration-only until the emitter consolidation
# lands.
GEMS = %w[openstudio-hvac openstudio-envelope openstudio-loads openstudio-lighting openstudio-shw
          openstudio-necb].freeze

STATUS_GROUPS = [
  ['implemented',        'Implemented'],
  ['partial',            'Partial (warns every run)'],
  ['not_implemented',    'Not implemented (warns every run)'],
  ['satisfied_by_clone', 'Satisfied by construction (clone)'],
  ['host_scope',         'Host / other-gem scope']
].freeze

# VINTAGE-DIRECTIONAL renumbering into canonical 2025 numbering.
#
# 2020's 8.4.4 (Reference Building) became 2025's 8.4.5; 2025's 8.4.4 is the
# NEW Energy Use Intensity subsection with no 2020 equivalent. So only refs
# originating in a 2020 manifest are translated (8.4.4.x -> 8.4.5.x); 2025
# refs pass through untouched. The previous blind bidirectional collapse
# (8.4.[45]. -> 8.4.N.) merged reference-building declarations INTO the 2025
# EUI subsection — wrong content on the one subsection that is genuinely new.
def canonical(article, vintage)
  a = article.to_s
  return a unless vintage.to_s == '2020'

  # ONE-SHOT map (2020 -> 2025): 8.4.4 (Reference Building) -> 8.4.5, and
  # 8.4.5 (Part-Load Curves in 2020 numbering) -> 8.4.6. Sequential subs
  # would cascade 8.4.4 -> 8.4.5 -> 8.4.6.
  a.sub(/\A8\.4\.([45])\./) { "8.4.#{Regexp.last_match(1).to_i + 1}." }
end

def article_sort_key(article)
  article.to_s.scan(/\d+/).map(&:to_i)
end

# Bidirectional prefix match on CANONICAL refs (trailing '.' guards 8.4.5.2.
# from matching 8.4.5.20.): '8.4.5.20.' matches '8.4.5.20.(1)'.
def canonicals_match?(na, nb)
  na.start_with?(nb) || nb.start_with?(na)
end

# ---- collect every manifest entry ----------------------------------------
records = []
GEMS.each do |gem|
  Dir.glob(File.join(ROOT, gem, 'lib', '**', 'data', 'necb', '*_rules_*.json')).sort.each do |path|
    data = JSON.parse(File.read(path))
    coverage = data.dig('article_coverage', 'articles')
    next if coverage.nil?

    vintage = File.basename(path)[/(\d{4})\.json\z/, 1] || data.dig('provenance', 'edition') || '?'
    coverage.each do |art|
      records << { gem: gem, vintage: vintage, article: art['article'].to_s,
                   canonical: canonical(art['article'], vintage),
                   title: art['title'].to_s, status: art['status'].to_s,
                   how: art['how'], gaps: art['gaps'] }
    end
  end
end

# ---- merge cross-vintage duplicates (differ only by renumbering) ----------
merged = {}
records.each do |r|
  key = [r[:gem], r[:canonical], r[:title], r[:status], r[:how], r[:gaps]]
  if merged.key?(key)
    merged[key][:vintages] << r[:vintage]
    merged[key][:articles] << r[:article]
  else
    merged[key] = r.merge(vintages: [r[:vintage]], articles: [r[:article]])
  end
end
rows = merged.values

def vintage_label(vintages)
  vintages.uniq.sort.join(', ')
end

# One article label per merged row: if both vintages, show both numbers.
def article_label(row)
  row[:articles].uniq.sort.join(' / ')
end

def notes(row)
  parts = []
  parts << row[:how] if row[:how] && !row[:how].empty?
  parts << "Gaps: #{row[:gaps]}" if row[:gaps] && !row[:gaps].empty?
  parts.join(' — ').tr('|', '/') # '|' would break the Markdown table
end

# ---- render ----------------------------------------------------------------
out = []
out << '<!-- Generated by scripts/generate_necb_gem_coverage.rb — do not edit by hand.'
out << '     Regenerate: ruby scripts/generate_necb_gem_coverage.rb -->'
out << ''
out << '# NECB coverage across the openstudio-* gem family'
out << ''
out << 'Rollup of every gem\'s NECB `article_coverage` manifest (both vintages;'
out << '2020 refs are canonicalized to 2025 numbering — 2020 8.4.4.x -> 8.4.5.x,'
out << 'the 2025-only 8.4.4 EUI subsection is never merged into). Statuses: **implemented** /'
out << '**partial** (warns every run) / **not_implemented** (warns every run) /'
out << '**satisfied_by_clone** / **host_scope** (delegated to the umbrella or a'
out << 'sibling gem). Each domain gem emits its section of this accounting into'
out << 'the shared AuditLog on every run, so nothing is silently missed —'
out << 'EXCEPT openstudio-necb (the umbrella), whose entries are declaration-only'
out << 'until it gains a runtime emitter: its partial/not_implemented rows do NOT'
out << 'yet warn on every run.'
out << ''

total = rows.size
STATUS_GROUPS.each do |status, heading|
  group = rows.select { |r| r[:status] == status }
           .sort_by { |r| [r[:gem], article_sort_key(r[:canonical])] }
  next if group.empty?

  out << "## #{heading} (#{group.size})"
  out << ''
  out << '| Gem | Vintage | Article | Title | Notes |'
  out << '|---|---|---|---|---|'
  group.each do |r|
    out << "| #{r[:gem]} | #{vintage_label(r[:vintages])} | #{article_label(r)} | #{r[:title]} | #{notes(r)} |"
  end
  out << ''
end

# ---- cross-gem delegations -------------------------------------------------
# Every host_scope article alongside the sibling-gem entry (if any) that covers
# the same article number with an implementing status.
covering = rows.reject { |r| r[:status] == 'host_scope' }
host = rows.select { |r| r[:status] == 'host_scope' }
          .sort_by { |r| [r[:gem], article_sort_key(r[:canonical])] }

out << "## Cross-gem delegations (#{host.size})"
out << ''
out << 'Each `host_scope` article and the sibling-gem entry that actually'
out << 'covers it. "(none in family)" means the umbrella/modeller owns it — a'
out << 'genuine open item to watch on a real run.'
out << ''
out << '| host_scope in | Article | Covered by |'
out << '|---|---|---|'
host.each do |h|
  matches = covering.select { |c| c[:gem] != h[:gem] && canonicals_match?(c[:canonical], h[:canonical]) }
                    .map { |c| "#{c[:gem]} #{article_label(c)} (#{c[:status]})" }
                    .uniq.sort
  covered = matches.empty? ? '(none in family — host/modeller scope)' : matches.join('; ')
  out << "| #{h[:gem]} | #{article_label(h)} | #{covered} |"
end
out << ''
out << "_#{total} coverage entries across #{GEMS.size} gems._"
out << ''

File.write(File.expand_path('../docs/NECB_GEM_COVERAGE.md', __dir__), out.join("\n"))
puts "wrote NECB_GEM_COVERAGE.md — #{total} merged rows (#{records.size} raw entries)"
