#!/usr/bin/env python3
"""Rebuild every derived artifact into a clean directory and compare it, BYTE
FOR BYTE, with the committed copy. Then check the archive and the README.

The previous version printed "byte-for-byte" while calling a semantic
comparison, and validated neither `hbix/` nor `hbix_index.json` at all — so a
changed table row or a new `known_issue` could pass, especially since the
comparator did not read table rows (Sol, `065` item 5). Three changes:

* derived artifacts are compared as BYTES, which they can be: every stage writes
  through one `write_json` with `sort_keys=True`;
* the archive is checked by `integrity.py`, which mechanises the invariants Sol
  verified by hand;
* the README's reported counts are GENERATED between markers, so the narrative
  numbers cannot drift from the artifacts they describe.

    python3 research/d100/pipeline/rebuild.py            # verify, offline
    python3 research/d100/pipeline/rebuild.py --refetch   # also re-answer every
                                                          # request (needs the key)

Under `--refetch` the archive is compared against the committed evidence with
`retrieved_utc` excluded — a stamp is expected to move, a payload is not.
"""

from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

from common import ARTIFACT_ROOT, PIPELINE_DIR, read_json, write_json

#: Derived artifacts, in dependency order.
STAGES = [("citations.py", ["citations.json"]),
          ("trace.py", ["traces.json"]),
          ("packets.py", ["packets.json"]),
          ("compare.py", ["comparisons.json"]),
          ("integrity.py", ["integrity.json"])]
COUNTS_BEGIN = "<!-- COUNTS BEGIN (generated by pipeline/rebuild.py) -->"
COUNTS_END = "<!-- COUNTS END -->"


def run(script: str, out: Path, extra=()):
    result = subprocess.run([sys.executable, str(PIPELINE_DIR / script),
                             "--out", str(out), *extra],
                            capture_output=True, text=True, cwd=PIPELINE_DIR)
    if result.returncode != 0 and script != "integrity.py":
        print(result.stdout)
        print(result.stderr, file=sys.stderr)
        raise SystemExit(f"{script} failed")
    return result.stdout


def counts_block(out: Path) -> str:
    """The README's numbers, derived from the artifacts rather than retyped."""
    integrity = read_json(out / "integrity.json")["summary"]
    citations = read_json(out / "citations.json")
    packets = read_json(out / "packets.json")
    comparisons = read_json(out / "comparisons.json")
    kinds, verdicts, grains = {}, {}, {}
    for entry in citations["citations"].values():
        kinds[entry["kind"]] = kinds.get(entry["kind"], 0) + 1
    for record in comparisons["comparisons"].values():
        verdicts[record["verdict"]] = verdicts.get(record["verdict"], 0) + 1
        grain = record.get("granularity", "-")
        grains[grain] = grains.get(grain, 0) + 1
    traces = read_json(out / "traces.json")
    sites = [site for group in traces.values() for site in group]
    lines = [COUNTS_BEGIN, "", "```text"]
    lines.append(f"citations                 {len(citations['citations'])}")
    for kind in sorted(kinds):
        lines.append(f"  {kind:23} {kinds[kind]}")
    lines.append(f"exact requests (typed)    {integrity['requests']}")
    for state in sorted(integrity["states"]):
        lines.append(f"  {state:23} {integrity['states'][state]}")
    lines.append(f"server_known_issue_count  {integrity['server_known_issue_count']}")
    lines.append(f"packets                   {packets['packet_count']}")
    lines.append(f"  operative_clause null   "
                 f"{sum(1 for p in packets['packets'] if p['requires_human_resolution'])}")
    lines.append(f"ruling sites              {len(sites)} across {len(traces)} decisions")
    lines.append(f"  unverified candidates   "
                 f"{sum(1 for s in sites if s.get('requires_human_resolution'))}")
    lines.append(f"comparisons               {len(comparisons['comparisons'])}")
    for verdict in sorted(verdicts):
        lines.append(f"  {verdict:23} {verdicts[verdict]}")
    lines.append("  by granularity:")
    for grain in sorted(grains):
        lines.append(f"    {grain:36} {grains[grain]}")
    lines.append(f"candidate renumbered pairs {len(comparisons['candidate_pairings'])}")
    lines += ["```", "", COUNTS_END]
    return "\n".join(lines)


def render_readme(out: Path, readme: Path) -> str:
    text = readme.read_text(encoding="utf-8")
    fresh = counts_block(out)
    start, end = text.find(COUNTS_BEGIN), text.find(COUNTS_END)
    if start < 0 or end < 0:
        raise SystemExit(f"{readme.name}: missing the COUNTS markers")
    return text[:start] + fresh + text[end + len(COUNTS_END):]


def archive_evidence(root: Path):
    """Every payload's content and state, with timestamps excluded."""
    out = {}
    for path in sorted((root / "hbix").glob("*.json")):
        stored = read_json(path)
        meta = dict(stored.get("meta", {}))
        meta.pop("retrieved_utc", None)
        out[path.stem] = {"meta": meta, "payload": stored.get("payload")}
    return out


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--into", type=Path, default=None)
    parser.add_argument("--refetch", action="store_true")
    parser.add_argument("--write-readme", action="store_true",
                        help="rewrite the committed README's generated counts")
    args = parser.parse_args(argv)

    temporary = args.into is None and not args.write_readme
    target = (Path(tempfile.mkdtemp(prefix="d100-rebuild-")) if temporary
              else (args.into or Path(tempfile.mkdtemp(prefix="d100-readme-"))))
    target.mkdir(parents=True, exist_ok=True)
    try:
        if args.refetch:
            run("citations.py", target)
            run("fetch.py", target)
        else:
            shutil.copytree(ARTIFACT_ROOT / "hbix", target / "hbix",
                            dirs_exist_ok=True)
            shutil.copy2(ARTIFACT_ROOT / "hbix_index.json", target)

        problems, checked = [], []
        for script, outputs in STAGES:
            run(script, target)
            for name in outputs:
                fresh, committed = target / name, ARTIFACT_ROOT / name
                checked.append(name)
                if not committed.exists():
                    problems.append(f"{name}: not committed")
                elif fresh.read_bytes() != committed.read_bytes():
                    problems.append(f"{name}: BYTES differ from the committed copy")

        # the archive itself, not only what is derived from it
        integrity = read_json(target / "integrity.json")
        if integrity["findings"]:
            problems.extend(f"archive: {f}" for f in integrity["findings"])

        if args.refetch:
            before, after = (archive_evidence(ARTIFACT_ROOT),
                             archive_evidence(target))
            if set(before) != set(after):
                problems.append("refetch: the request set changed")
            for key in sorted(set(before) & set(after)):
                if before[key] != after[key]:
                    problems.append(f"refetch: {key} answered differently "
                                    "(content, not timestamp)")

        readme = ARTIFACT_ROOT / "README.md"
        fresh_readme = render_readme(target, readme)
        if args.write_readme:
            readme.write_text(fresh_readme, encoding="utf-8")
            print(f"wrote the generated counts into {readme.name}")
        elif fresh_readme != readme.read_text(encoding="utf-8"):
            problems.append("README.md: the generated counts are stale — run "
                            "rebuild.py --write-readme")
        checked.append("README.md counts")

        print(f"rebuilt into {target}")
        print(f"checked: {' '.join(checked)}")
        if problems:
            print("\nNOT REPRODUCIBLE:")
            for problem in problems:
                print(f"  {problem}")
            return 1
        print("\nevery derived artifact is byte-identical to its committed copy, "
              "the archive's invariants hold, and the README's counts are current")
        return 0
    finally:
        if temporary:
            shutil.rmtree(target, ignore_errors=True)


if __name__ == "__main__":
    raise SystemExit(main())
