# Regenerate the numeric table of contents at the top of docs/necb_decisions.md
# from the machine-readable registry (lib/btap_necb/data/decisions.json).
#
# The doc itself is CHRONOLOGICAL (newest last), so heading order is not id
# order — this TOC is the id-ordered index a reader needs to find "D-53"
# without scrolling past D-60. The block between the BEGIN/END markers is
# owned by this script; test_decisions_registry.rb fails if it drifts.
#
# Reads the GENERATED Ruby copy of the canonical Python registry (R3, D-81);
# byte identity is CI-enforced on every PR, so these are the canonical bytes.
# Do not repoint this at the Python file — the generator moves with the doc at R6.
#
#   ruby scripts/generate_decisions_toc.rb          # rewrite in place
#   ruby scripts/generate_decisions_toc.rb --check  # exit 1 on drift (no write)

require 'json'

ROOT = File.expand_path('..', __dir__)
DOC = File.join(ROOT, 'docs', 'necb_decisions.md')
REGISTRY = File.join(ROOT, 'lib', 'btap_necb', 'data', 'decisions.json')
BEGIN_MARK = '<!-- TOC BEGIN (generated by scripts/generate_decisions_toc.rb — do not hand-edit) -->'
END_MARK = '<!-- TOC END -->'

def toc_block
  decisions = JSON.parse(File.read(REGISTRY))['decisions']
  lines = decisions.sort_by { |d| d['id'][/\d+/].to_i }.map do |d|
    "- **#{d['id']}** — #{d['title']} _(#{d['kind']})_"
  end
  [BEGIN_MARK, '', '## Index (id order; entries below are chronological)', '', *lines, '', END_MARK].join("\n")
end

doc = File.read(DOC)
fresh = toc_block
current = doc[/#{Regexp.escape(BEGIN_MARK)}.*?#{Regexp.escape(END_MARK)}/m]

if ARGV.include?('--check')
  if current == fresh
    puts 'decisions TOC: up to date'
  else
    warn 'decisions TOC: STALE — run ruby scripts/generate_decisions_toc.rb'
    exit 1
  end
elsif current
  File.write(DOC, doc.sub(current, fresh))
  puts 'decisions TOC: rewritten in place'
else
  # First insertion: after the intro paragraph (before the first '## ' heading).
  insert_at = doc.index(/^## /)
  abort 'no ## heading found to anchor the TOC' unless insert_at
  File.write(DOC, doc[0...insert_at] + fresh + "\n\n" + doc[insert_at..])
  puts 'decisions TOC: inserted'
end
