module OpenStudioNECB
  module Report
    # One method per report section, assembled in ORDER. All methods take the
    # same context and return an HTML string ('' to omit the section).
    # ctx: { report:, audit_entries:, checklist_rows:, proposed:, reference:,
    #        options: } — proposed/reference are ModelQuery.extract hashes
    #        (reference nil on EUI-only runs).
    module Sections
      module_function

      ORDER = %i[header verdict_banner path_declaration checklist energy ghg envelope
                 hvac lighting loads shw costing coverage_appendix audit_appendix
                 declarations].freeze

      DOMAIN_STEPS = {
        envelope: %w[envelope reference_envelope thermal_bridging fdwr srr],
        hvac: %w[selection build efficiency reference_hvac economizer fan_power
                 energy_recovery check_part5 capacity_iteration],
        lighting: %w[lights lighting daylighting reference_daylighting],
        loads: %w[loads space_types assign_space_types occupancy plug_loads],
        shw: %w[shw service_water_heating]
      }.freeze

      def render_all(ctx)
        ORDER.map { |name| send(name, ctx) }.join("\n")
      end

      # -- 1 -----------------------------------------------------------------
      def header(ctx)
        report = ctx[:report]
        options = ctx[:options]
        project = [
          ['Project name', options[:project_name] || '(not provided)'],
          ['Address', options[:address] || '(not provided)'],
          ['Permit / application no.', options[:permit_number] || '(not provided)'],
          ['Prepared by', options[:prepared_by] || '(not provided)'],
          ['Report date', options[:date] || '(run date not stamped)'],
          ['Code edition', "NECB #{report['vintage']}"],
          ['Heating degree-days (HDD18)', H.fmt(report['hdd'], prec: 0)],
          ['Simulation mode', report['simulate']]
        ]
        <<~HTML
          <header>
            <h1>NECB #{H.esc(report['vintage'])} Energy Code Compliance Report</h1>
            <p class="meta">Modelled compliance evidence package for the authority having jurisdiction.
            Generated by the openstudio-necb gem family (SDK-only NECB implementation with article-cited audit trail).</p>
            #{H.kv_table(project)}
            <nav class="toc">
              <a href="#verdict">Summary</a><a href="#paths">Compliance paths</a><a href="#checklist">Checklist</a>
              <a href="#energy">Energy</a>#{ctx[:report].dig('proposed', 'ghg_kg_co2e') ? '<a href="#ghg">GHG</a>' : ''}<a href="#envelope">Envelope</a><a href="#hvac">HVAC</a>
              <a href="#lighting">Lighting</a><a href="#loads">Loads</a><a href="#shw">SHW</a>
              <a href="#coverage">Coverage</a><a href="#audit">Audit trail</a>
            </nav>
          </header>
        HTML
      end

      # -- 2 -----------------------------------------------------------------
      def verdict_banner(ctx)
        report = ctx[:report]
        badges = []
        unless report['compliant'].nil?
          badges << H.badge(report['compliant'] ? 'PERFORMANCE PATH: PASS' : 'PERFORMANCE PATH: FAIL',
                            report['compliant'] ? 'pass' : 'fail')
        end
        if (eui = report['eui_path'])
          badges << H.badge(eui['compliant'] ? 'EUI PATH (8.4.4): PASS' : 'EUI PATH (8.4.4): FAIL',
                            eui['compliant'] ? 'pass' : 'fail')
        end
        if report['reference'] && report['reference']['method'].to_s.include?('archetype') && !report['compliant'].nil?
          badges[0] = H.badge(report['compliant'] ? 'EUI PATH (8.4.4): PASS' : 'EUI PATH (8.4.4): FAIL',
                              report['compliant'] ? 'pass' : 'fail')
        end
        badges << H.badge("TIER #{report['tier']}", 'tier') if report['tier']
        badges << H.badge("GHG LEVEL #{report.dig('ghg', 'level')}", 'ghg') if report.dig('ghg', 'level')
        badges << H.badge('UNDETERMINED (no annual run)', 'warn') if report['compliant'].nil?

        proposed_kwh = report.dig('proposed', 'total_site_kwh')
        target_kwh = report.dig('reference', 'total_site_kwh') ||
                     report.dig('reference', 'building_energy_target_kwh')
        numbers = []
        if proposed_kwh
          numbers << "Proposed: <strong>#{H.fmt(proposed_kwh, prec: 0)} kWh</strong>" \
                     " (#{H.fmt(report.dig('proposed', 'eui_kwh_per_m2'))} kWh/m²·yr)"
        end
        numbers << "Target: <strong>#{H.fmt(target_kwh, prec: 0)} kWh</strong>" if target_kwh
        if proposed_kwh && target_kwh && target_kwh.positive?
          margin = 100.0 * (target_kwh - proposed_kwh) / target_kwh
          numbers << "Margin: <strong>#{margin.round(1)}%</strong> #{margin.negative? ? 'over' : 'under'} target"
        end

        strip = ''
        if report['annual'] == false
          strip = %(<p class="warnstrip">▲ SHORTENED RUN PERIOD — the results below use the same arithmetic
            but are NOT a code-compliant annual determination (NECB 8.4.1.2 requires a simulated year).</p>)
        end
        %(<section id="verdict"><div class="banner"><span class="big">Compliance summary</span>
          #{badges.join(' ')}<span>#{numbers.join(' &nbsp;•&nbsp; ')}</span></div>#{strip}</section>)
      end

      # -- 3 -----------------------------------------------------------------
      def path_declaration(ctx)
        report = ctx[:report]
        eui_primary = report.dig('reference', 'method').to_s.include?('archetype')
        rows = []
        perf_used = !eui_primary && !report['compliant'].nil?
        rows << [H.raw(perf_used ? '●' : '○'), 'NECB 8.4.1.2 — Building Energy Performance (reference building)',
                 verdict_text(perf_used ? report['compliant'] : nil)]
        eui_used = eui_primary || !report['eui_path'].nil?
        eui_verdict = if eui_primary then report['compliant']
                      elsif report['eui_path'] then report['eui_path']['compliant']
                      end
        rows << [H.raw(eui_used ? '●' : '○'), 'NECB 8.4.4 — Archetype Energy Use Intensity (2025)',
                 verdict_text(eui_used ? eui_verdict : nil)]
        rows << [H.raw('○'), 'NECB Parts 3–7 — Prescriptive/trade-off paths',
                 'Not declared by this report (see Part 5 QAQC notes in the HVAC section if run)']
        body = H.table(['Used', 'Compliance path', 'Result'], rows)
        body += %(<p class="meta">Path declaration mirrors the City of Vancouver Building Energy Design
          Statement structure: ● declared path(s), ○ paths not relied upon.</p>)
        H.section('paths', 'Compliance path declaration', body)
      end

      def verdict_text(verdict)
        case verdict
        when true then H.raw("#{H.glyph(:pass)} Complies")
        when false then H.raw("#{H.glyph(:fail)} Does not comply")
        else 'Not used / not determined'
        end
      end

      # -- 4 -----------------------------------------------------------------
      def checklist(ctx)
        rows = ctx[:checklist_rows]
        return H.section('checklist', 'Compliance checklist', '<p>No audited compliance decisions recorded.</p>') if rows.empty?

        table_rows = rows.map do |row|
          [H.raw(H.glyph(row.glyph)),
           H.raw(%(<a href="#audit-#{row.audit_index}">#{H.esc(row.article.empty? ? '—' : row.article)}</a>)),
           row.statement, row.measured || '—']
        end
        body = H.table(['', 'Article', 'Requirement / determination', 'Measured values'], table_rows)
        body += %(<p class="meta">#{H.glyph(:pass)} complies &nbsp; #{H.glyph(:fail)} does not comply &nbsp;
          #{H.glyph(:warning)} warning / modeller attention &nbsp; #{H.glyph(:info)} scope note &nbsp;
          #{H.glyph(:na)} informational. Each article links to the full audit entry.</p>)
        H.section('checklist', 'Compliance checklist', body)
      end

      # -- 5 -----------------------------------------------------------------
      def energy(ctx)
        report = ctx[:report]
        proposed = report['proposed'] || {}
        reference = report['reference'] || {}
        has_ref_energy = !reference['total_site_kwh'].nil?
        body = +"<p>#{H.legend}</p>"

        end_use_rows = (proposed['end_uses_kwh'] || {}).map do |use, value|
          [use.tr('_', ' ').capitalize, value, has_ref_energy ? reference.dig('end_uses_kwh', use) : nil]
        end
        chart = Charts.paired_bars(end_use_rows, unit: 'kWh', label: 'Annual end-use energy, proposed vs reference')
        body << "<h3>End-use breakdown</h3>#{chart}" unless chart.empty?

        totals = []
        totals << ['Proposed', proposed['total_site_kwh']] if proposed['total_site_kwh']
        totals << ['Reference', reference['total_site_kwh']] if has_ref_energy
        targets = []
        targets << ['BET (8.4.4)', report.dig('eui_path', 'bet_kwh') || reference['building_energy_target_kwh']].compact if report['eui_path'] || reference['building_energy_target_kwh']
        chart2 = Charts.total_bars(totals, targets: targets.reject { |t| t.size < 2 })
        body << "<h3>Annual totals</h3>#{chart2}" unless chart2.empty?

        fuel_rows = %w[electricity_kwh natural_gas_kwh district_heating_kwh district_cooling_kwh].filter_map do |fuel|
          p = proposed[fuel]
          r = reference[fuel]
          next if (p.nil? || p.zero?) && (r.nil? || r.zero?)

          [fuel.sub('_kwh', '').tr('_', ' ').capitalize, H.fmt(p, unit: 'kWh', prec: 0),
           has_ref_energy ? H.fmt(r, unit: 'kWh', prec: 0) : '—']
        end
        body << "<h3>Energy by fuel</h3>#{H.table(['Fuel', 'Proposed', 'Reference'], fuel_rows)}" unless fuel_rows.empty?

        if (lines = report.dig('eui_path', 'lines') || reference['lines'])
          line_rows = lines.map do |l|
            l = l.transform_keys(&:to_s)
            [l['archetype'] || l['building_type'], H.fmt(l['area_m2'], unit: 'm²', prec: 1),
             H.fmt(l['eui_kwh_per_m2'], unit: 'kWh/m²·yr', prec: 0), H.fmt(l['kwh'] || l['target_kwh'], unit: 'kWh', prec: 0)]
          end
          body << "<h3>Archetype-EUI building energy target (Table 8.4.4.1)</h3>" \
                  "#{H.table(['Archetype', 'Floor area', 'Target EUI', 'Target energy'], line_rows)}"
        end

        unmet_p = proposed['unmet_occupied_hours']
        if unmet_p
          unmet_r = reference['unmet_occupied_hours'] || {}
          body << '<h3>Unmet occupied hours (limit 100 h)</h3>'
          body << H.table(['', 'Proposed', 'Reference'],
                          [['Heating', H.fmt(unmet_p['heating'], unit: 'h'), H.fmt(unmet_r['heating'], unit: 'h')],
                           ['Cooling', H.fmt(unmet_p['cooling'], unit: 'h'), H.fmt(unmet_r['cooling'], unit: 'h')]])
        end

        if (iterations = report['capacity_iterations']) && !iterations.empty?
          iteration_rows = iterations.map.with_index(1) do |it, i|
            it = it.transform_keys(&:to_s)
            [i, it['action'] || it['adjusted'] || '(see audit)', H.esc(it.reject { |k, _| k == 'unmet_after' }.to_s[0, 160])]
          end
          body << H.details("Capacity auto-iteration history (8.4.1.2.(5)) — #{iterations.size} round(s)",
                            H.table(['Round', 'Adjustment', 'Detail'], iteration_rows))
        end

        H.section('energy', 'Energy results', body, page_break: true)
      end

      # -- 5b: NECB 2025 Part 11 operational GHG ------------------------------
      def ghg(ctx)
        report = ctx[:report]
        proposed_ghg = report.dig('proposed', 'ghg_kg_co2e')
        return '' if proposed_ghg.nil?

        reference_ghg = report.dig('reference', 'ghg_kg_co2e')
        body = +"<p>#{H.legend}</p>"
        chart = Charts.paired_bars([['Operational GHG', proposed_ghg, reference_ghg]],
                                   unit: 'kg CO₂e/yr', label: 'Annual operational GHG emissions, proposed vs reference')
        body << chart
        pairs = [['Proposed emissions', H.fmt(proposed_ghg, unit: 'kg CO₂e/yr', prec: 0)]]
        pairs << ['Reference emissions (GHG target)', H.fmt(reference_ghg, unit: 'kg CO₂e/yr', prec: 0)] if reference_ghg
        if (level = report['ghg'])
          pairs << ['Percent of GHG target', H.fmt(level['percent_of_ghg_target'], unit: '%')]
          pairs << ['GHG performance level (Table 11.2.1.1)',
                    H.raw(level['level'] ? H.badge("LEVEL #{level['level']}", 'ghg') : H.badge('ABOVE TARGET — no level', 'warn'))]
        end
        body << H.kv_table(pairs)
        body << %(<p class="meta">Operational GHG per NECB 2025 Part 11: annual energy by fuel multiplied by
          provincial emission factors (see the audited factor values in the audit trail). Levels A–F are
          assigned by percent of the reference building's emissions.</p>)
        H.section('ghg', 'Operational GHG emissions (NECB 2025 Part 11)', body)
      end

      # -- 6 -----------------------------------------------------------------
      def envelope(ctx)
        proposed = ctx[:proposed]&.dig(:envelope)
        reference = ctx[:reference]&.dig(:envelope)
        body = +"<p>#{H.legend}</p>"
        if proposed
          u_rows = proposed[:surfaces].map do |s|
            ref_match = reference&.dig(:surfaces)&.find { |r| r[:type] == s[:type] }
            [s[:type], s[:avg_u_w_per_m2k], ref_match && ref_match[:avg_u_w_per_m2k]]
          end.reject { |_, p, _| p.nil? }
          chart = Charts.paired_bars(u_rows, unit: 'W/m²·K', label: 'Area-weighted average U-value by surface type', prec: 3)
          body << "<h3>Overall thermal transmittance (area-weighted)</h3>#{chart}"

          area_rows = proposed[:surfaces].map do |s|
            [s[:type], H.fmt(s[:area_m2], unit: 'm²'), H.fmt(s[:avg_u_w_per_m2k], prec: 3)]
          end
          body << H.table(['Surface type', 'Exterior area', 'Avg U (W/m²·K)'], area_rows)
          fdwr_rows = [['Fenestration-and-door-to-wall ratio (FDWR)', H.fmt(proposed[:fdwr], prec: 3),
                        H.fmt(reference&.dig(:fdwr), prec: 3)],
                       ['Skylight-to-roof ratio (SRR)', H.fmt(proposed[:srr], prec: 3), H.fmt(reference&.dig(:srr), prec: 3)]]
          body << H.table(['Ratio', 'Proposed', 'Reference'], fdwr_rows)
        else
          body << '<p>Model geometry not available to this render (report-only mode).</p>'
        end
        body << domain_audit_notes(ctx, :envelope)
        H.section('envelope', 'Building envelope', body, page_break: true)
      end

      # -- 7 -----------------------------------------------------------------
      def hvac(ctx)
        body = +''
        %i[proposed reference].each do |which|
          data = ctx[which]
          next if data.nil?

          accent = which == :proposed ? H::PROPOSED_COLOR : H::REFERENCE_COLOR
          loops = (data[:air_loops] || []) + (data[:plant_loops] || [])
          next if loops.empty?

          body << "<h3>#{which.to_s.capitalize} building systems</h3>"
          loops.each { |loop| body << Diagrams.loop_schematic(loop, accent: accent) }
        end
        body = '<p>No air or plant loops present (e.g. zone-equipment-only design), or models not available.</p>' if body.empty?
        body << domain_audit_notes(ctx, :hvac)
        H.section('hvac', 'HVAC systems', body, page_break: true)
      end

      # -- 8 -----------------------------------------------------------------
      def lighting(ctx)
        body = space_type_table(ctx, :lpd_w_per_m2, 'Lighting power density (W/m²)')
        body << domain_audit_notes(ctx, :lighting)
        H.section('lighting', 'Lighting', body)
      end

      def loads(ctx)
        body = +''
        if (types = ctx[:proposed]&.dig(:space_types)) && !types.empty?
          rows = types.map do |t|
            [t[:name], H.fmt(t[:area_m2], unit: 'm²'), H.fmt(t[:people_per_m2], prec: 4),
             H.fmt(t[:equipment_w_per_m2], unit: 'W/m²', prec: 2)]
          end
          body << H.table(['Space type', 'Floor area', 'People/m²', 'Receptacle W/m²'], rows)
        else
          body << '<p>No space types with floor area in the proposed model.</p>'
        end
        body << domain_audit_notes(ctx, :loads)
        H.section('loads', 'Internal loads (occupancy and receptacle)', body)
      end

      def shw(ctx)
        notes = domain_audit_notes(ctx, :shw)
        body = notes.empty? ? '<p>No service water heating decisions recorded for this run.</p>' : notes
        H.section('shw', 'Service water heating', body)
      end

      # -- 9 -----------------------------------------------------------------
      def costing(ctx)
        report = ctx[:report]
        p_cost = report.dig('proposed', 'cost')
        return '' if p_cost.nil?

        r_cost = report.dig('reference', 'cost') || {}
        rows = %w[hvac envelope total].map do |k|
          [k.capitalize, H.fmt(p_cost[k], unit: '$', prec: 0), H.fmt(r_cost[k], unit: '$', prec: 0)]
        end
        body = H.table(['Scope', 'Proposed', 'Reference'], rows)
        if (delta = report['incremental_cost_proposed_vs_reference'])
          body << H.kv_table([['Incremental cost, proposed vs reference', H.fmt(delta, unit: '$', prec: 0)]])
        end
        body << %(<p class="meta">Costing totals only — line-item ledgers stay in the run directory
          (licensed unit costs are never embedded in this report).</p>)
        H.section('costing', 'Costing summary', body)
      end

      # -- 10 ----------------------------------------------------------------
      def coverage_appendix(ctx)
        entries = ctx[:audit_entries].each_with_index.select { |e, _| e[:step].to_s == 'coverage' }
        warnings = ctx[:audit_entries].each_with_index.select { |e, _| %i[warn warning].include?(e[:level]) }
        body = +''
        unless entries.empty?
          rows = entries.map { |e, i| [e[:article].to_s, e[:action].to_s, H.raw(%(<a href="#audit-#{i}">entry #{i}</a>))] }
          body << "<h3>Article coverage notes</h3>#{H.table(['Article', 'Scope note', 'Audit'], rows)}"
        end
        unless warnings.empty?
          rows = warnings.map do |e, i|
            [H.raw(H.glyph(:warning)), e[:article].to_s, "#{e[:target] ? "#{e[:target]}: " : ''}#{e[:action]}",
             H.raw(%(<a href="#audit-#{i}">entry #{i}</a>))]
          end
          body << "<h3>All warnings (#{warnings.size})</h3>#{H.table(['', 'Article', 'Warning', 'Audit'], rows)}"
        end
        body = '<p>No coverage notes or warnings recorded.</p>' if body.empty?
        H.section('coverage', 'Scope, coverage and warnings', body, page_break: true)
      end

      # -- 11 ----------------------------------------------------------------
      def audit_appendix(ctx)
        rows = ctx[:audit_entries].map.with_index do |e, i|
          level = e[:level].to_s
          # decisions get a neutral glyph here; the checklist carries the verdict
          glyph_kind = { 'warn' => :warning, 'warning' => :warning, 'info' => :info }.fetch(level, :na)
          %(<tr id="audit-#{i}"><td>#{i}</td><td>#{H.glyph(glyph_kind)} #{H.esc(level)}</td>) +
            %(<td>#{H.esc(e[:step])}</td><td>#{H.esc(e[:target])}</td><td>#{H.esc(e[:action])}</td>) +
            %(<td>#{H.esc(e[:article])}</td><td>#{H.esc(compact_inputs(e))}</td></tr>)
        end.join
        table = %(<table><thead><tr><th>#</th><th>Level</th><th>Step</th><th>Target</th>) +
                %(<th>Action</th><th>Article</th><th>Inputs / value</th></tr></thead><tbody>#{rows}</tbody></table>)
        H.section('audit', 'Full audit trail',
                  H.details("#{ctx[:audit_entries].size} audited entries (every value used and article applied)", table))
      end

      def compact_inputs(entry)
        parts = []
        parts << entry[:inputs].map { |k, v| "#{k}=#{v.is_a?(Float) ? v.round(3) : v}" }.join(', ') if entry[:inputs].is_a?(Hash) && !entry[:inputs].empty?
        parts << entry[:value].to_s if entry[:value]
        parts.join(' | ')[0, 220]
      end

      # -- 12 ----------------------------------------------------------------
      def declarations(ctx)
        options = ctx[:options]
        <<~HTML
          <section id="declarations" class="page-break"><h2>Declarations</h2>
            <p>The undersigned declares that the energy model summarized in this report represents the
            design submitted for permit, and that the compliance path(s) declared above were evaluated
            in accordance with NECB #{H.esc(ctx[:report]['vintage'])} Part 8 using whole-building simulation.</p>
            <div>
              <span class="sig">Energy modeller: #{H.esc(options[:prepared_by] || '')}&nbsp;<br>Signature / date</span>
              <span class="sig">Registered professional of record: #{H.esc(options[:professional_of_record] || '')}&nbsp;<br>Signature / seal / date</span>
            </div>
            <footer>Generated by openstudio-necb (openstudio-hvac, -envelope, -loads, -lighting, -shw, -geometry).
            Single-file report: no external resources, scripts or network requests. Audit entries are the
            normative record; this report is a rendering of them.</footer>
          </section>
        HTML
      end

      # -- shared --------------------------------------------------------------
      def space_type_table(ctx, key, heading)
        types = ctx[:proposed]&.dig(:space_types)
        return +'<p>No space types with floor area in the proposed model.</p>' if types.nil? || types.empty?

        ref_types = (ctx[:reference]&.dig(:space_types) || []).to_h { |t| [t[:name], t] }
        rows = types.map do |t|
          ref = ref_types[t[:name]]
          [t[:name], H.fmt(t[:area_m2], unit: 'm²'), H.fmt(t[key], prec: 2),
           ref ? H.fmt(ref[key], prec: 2) : '—']
        end
        +"<h3>#{H.esc(heading)}</h3>#{H.table(['Space type', 'Floor area', 'Proposed', 'Reference'], rows)}"
      end

      # Per-domain audit table: decisions + warnings whose step matches the domain.
      def domain_audit_notes(ctx, domain)
        steps = DOMAIN_STEPS[domain]
        picked = ctx[:audit_entries].each_with_index.select do |e, _|
          steps.any? { |s| e[:step].to_s.include?(s) } && %i[decision warn warning].include?(e[:level])
        end
        return '' if picked.empty?

        rows = picked.first(60).map do |e, i|
          [H.raw(H.glyph(%i[warn warning].include?(e[:level]) ? :warning : :info)), e[:article].to_s,
           "#{e[:target] ? "#{e[:target]}: " : ''}#{e[:action]}",
           H.raw(%(<a href="#audit-#{i}">##{i}</a>))]
        end
        note = picked.size > 60 ? %(<p class="meta">Showing 60 of #{picked.size} — see the full audit trail.</p>) : ''
        H.details("Audited decisions for this domain (#{picked.size})",
                  H.table(['', 'Article', 'Decision', 'Audit'], rows) + note)
      end
    end
  end
end
