module OpenStudioNECB
  module Report
    # One method per report section, assembled in ORDER. All methods take the
    # same context and return an HTML string ('' to omit the section).
    # ctx: { report:, audit_entries:, checklist_rows:, proposed:, reference:,
    #        options: } — proposed/reference are ModelQuery.extract hashes
    #        (reference nil on EUI-only runs).
    module Sections
      module_function

      ORDER = %i[header verdict_banner path_declaration floor_plans checklist energy ghg envelope
                 hvac lighting loads shw costing coverage_appendix rulings_appendix
                 audit_appendix declarations].freeze

      # CONTRACT: maps each per-domain report section to the audit `step:`
      # names (substring match) whose entries it renders as notes. A NEW audit
      # step name introduced in any gem must be added here, or its entries
      # silently drop out of that domain's section (they still appear in the
      # full audit trail appendix).
      DOMAIN_STEPS = {
        envelope: %w[envelope reference_envelope thermal_bridging fdwr srr],
        hvac: %w[selection build efficiency reference_hvac economizer fan_power
                 energy_recovery check_part5 capacity_iteration],
        lighting: %w[lights lighting daylighting reference_daylighting],
        loads: %w[loads space_types assign_space_types occupancy plug_loads],
        shw: %w[shw service_water_heating]
      }.freeze

      def render_all(ctx)
        ORDER.map { |name| send(name, ctx) }.join("\n")
      end

      # -- header --------------------------------------------------------
      def header(ctx)
        report = ctx[:report]
        options = ctx[:options]
        project = [
          ['Project name', options[:project_name] || '(not provided)'],
          ['Address', options[:address] || '(not provided)'],
          ['Permit / application no.', options[:permit_number] || '(not provided)'],
          ['Prepared by', options[:prepared_by] || '(not provided)'],
          ['Report date', options[:date] || '(run date not stamped)'],
          ['Code edition', "NECB #{report['vintage']}"],
          ['Heating degree-days (HDD18)', Html.fmt(report['hdd'], prec: 0)],
          ['Simulation mode', report['simulate']]
        ]
        <<~HTML
          <header>
            <h1>NECB #{Html.esc(report['vintage'])} Energy Code Compliance Report</h1>
            <p class="meta">Modelled compliance evidence package for the authority having jurisdiction.
            Generated by the openstudio-necb gem family (SDK-only NECB implementation with article-cited audit trail).</p>
            #{Html.kv_table(project)}
            <nav class="toc">
              <a href="#verdict">Summary</a><a href="#paths">Compliance paths</a><a href="#checklist">Checklist</a>
              <a href="#floor-plans">Floor plans</a><a href="#energy">Energy</a>#{ctx[:report].dig('proposed', 'ghg_kg_co2e') ? '<a href="#ghg">GHG</a>' : ''}<a href="#envelope">Envelope</a><a href="#hvac">HVAC</a>
              <a href="#lighting">Lighting</a><a href="#loads">Loads</a><a href="#shw">SHW</a>
              <a href="#coverage">Coverage</a><a href="#rulings">Decisions</a><a href="#audit">Audit trail</a>
            </nav>
          </header>
        HTML
      end

      # -- verdict_banner ------------------------------------------------
      def verdict_banner(ctx)
        report = ctx[:report]
        badges = []
        unless report['compliant'].nil?
          badges << Html.badge(report['compliant'] ? 'PERFORMANCE PATH: PASS' : 'PERFORMANCE PATH: FAIL',
                            report['compliant'] ? 'pass' : 'fail')
        end
        if (eui = report['eui_path'])
          badges << if eui['computed'] == false
                      # the as-specified run cannot lawfully serve the 8.4.4 verdict
                      # (Table 8.4.4.2 non-conformance / applicability) — say so,
                      # never render a pass/fail that was not determined
                      Html.badge('EUI PATH (8.4.4): NOT COMPUTED', 'warn')
                    else
                      Html.badge(eui['compliant'] ? 'EUI PATH (8.4.4): PASS' : 'EUI PATH (8.4.4): FAIL',
                              eui['compliant'] ? 'pass' : 'fail')
                    end
        end
        if report['reference'] && report['reference']['method'].to_s.include?('archetype') && !report['compliant'].nil?
          badges[0] = Html.badge(report['compliant'] ? 'EUI PATH (8.4.4): PASS' : 'EUI PATH (8.4.4): FAIL',
                              report['compliant'] ? 'pass' : 'fail')
        end
        # The performance-path tier (vs the reference building) and the EUI-path
        # tier (vs the archetype target) measure the SAME proposed energy against
        # DIFFERENT targets, so they can differ — label each by its path.
        eui_tier = report.dig('eui_path', 'tier')
        if report['tier'] && eui_tier
          badges << Html.badge("PERFORMANCE TIER #{report['tier']}", 'tier')
          badges << Html.badge("EUI TIER #{eui_tier}", 'tier')
        elsif report['tier']
          badges << Html.badge("TIER #{report['tier']}", 'tier')
        end
        badges << Html.badge("GHG LEVEL #{report.dig('ghg', 'level')}", 'ghg') if report.dig('ghg', 'level')
        badges << Html.badge('UNDETERMINED (no annual run)', 'warn') if report['compliant'].nil?

        proposed_kwh = report.dig('proposed', 'total_site_kwh')
        target_kwh = report.dig('reference', 'total_site_kwh') ||
                     report.dig('reference', 'building_energy_target_kwh')
        numbers = []
        if proposed_kwh
          numbers << "Proposed: <strong>#{Html.fmt(proposed_kwh, prec: 0)} kWh</strong>" \
                     " (#{Html.fmt(report.dig('proposed', 'eui_kwh_per_m2'))} kWh/m²·yr)"
        end
        numbers << "Target: <strong>#{Html.fmt(target_kwh, prec: 0)} kWh</strong>" if target_kwh
        if proposed_kwh && target_kwh && target_kwh.positive?
          margin = 100.0 * (target_kwh - proposed_kwh) / target_kwh
          numbers << "Margin: <strong>#{margin.round(1)}%</strong> #{margin.negative? ? 'over' : 'under'} target"
        end

        strip = ''
        if report['annual'] == false
          strip = %(<p class="warnstrip">▲ SHORTENED RUN PERIOD — the results below use the same arithmetic
            but are NOT a code-compliant annual determination (NECB 8.4.1.2 requires a simulated year).</p>)
        end
        if report['tier'] && eui_tier && report['tier'] != eui_tier
          bet = report.dig('eui_path', 'bet_kwh')
          strip += %(<p class="meta">The performance-path tier (#{report['tier']}, vs the reference building
            #{Html.fmt(target_kwh, prec: 0)} kWh) and the EUI-path tier (#{eui_tier}, vs the archetype target
            #{Html.fmt(bet, prec: 0)} kWh) differ because the same proposed energy is measured against different
            targets — a building declares the tier of whichever compliance path it uses.</p>)
        end
        %(<section id="verdict"><div class="banner"><span class="big">Compliance summary</span>
          #{badges.join(' ')}<span>#{numbers.join(' &nbsp;•&nbsp; ')}</span></div>#{strip}</section>)
      end

      # -- path_declaration ----------------------------------------------
      def path_declaration(ctx)
        report = ctx[:report]
        eui_primary = report.dig('reference', 'method').to_s.include?('archetype')
        rows = []
        perf_used = !eui_primary && !report['compliant'].nil?
        rows << [Html.raw(perf_used ? '●' : '○'), 'NECB 8.4.1.2 — Building Energy Performance (reference building)',
                 verdict_text(perf_used ? report['compliant'] : nil)]
        eui_not_computed = report.dig('eui_path', 'computed') == false
        eui_used = eui_primary || (!report['eui_path'].nil? && !eui_not_computed)
        eui_verdict = if eui_primary then report['compliant']
                      elsif eui_used then report['eui_path']['compliant']
                      end
        eui_result = if eui_not_computed
                       "Not computed — #{report.dig('eui_path', 'reason')}"
                     else
                       verdict_text(eui_used ? eui_verdict : nil)
                     end
        rows << [Html.raw(eui_used ? '●' : '○'), 'NECB 8.4.4 — Archetype Energy Use Intensity (2025)',
                 eui_result]
        rows << [Html.raw('○'), 'NECB Parts 3–7 — Prescriptive/trade-off paths',
                 'Not declared by this report (see Part 5 QAQC notes in the HVAC section if run)']
        body = Html.table(['Used', 'Compliance path', 'Result'], rows)
        body += %(<p class="meta">Path declaration mirrors the City of Vancouver Building Energy Design
          Statement structure: ● declared path(s), ○ paths not relied upon.</p>)
        Html.section('paths', 'Compliance path declaration', body)
      end

      def verdict_text(verdict)
        case verdict
        when true then Html.raw("#{Html.glyph(:pass)} Complies")
        when false then Html.raw("#{Html.glyph(:fail)} Does not comply")
        else 'Not used / not determined'
        end
      end

      # -- floor_plans ---------------------------------------------------
      # Per-storey plan views from openstudio-geometry's plan engine (PROPOSED
      # model; the reference's spaces/zones are identical by clone — stated in
      # the section). ctx[:floor_plans] is the never-raise bundle
      # {storeys: [{name:, svg:}], legend_svg:, empty:, inferred_storeys:,
      # error:}; absent/empty/error all render as a one-line note.
      def floor_plans(ctx)
        plans = ctx[:floor_plans]
        return Html.section('floor-plans', 'Floor plans',
                            '<p class="meta">No model was available to draw floor plans from.</p>') if plans.nil?
        if plans[:error] || plans[:empty] || plans[:storeys].empty?
          note = plans[:error] ? "floor-plan extraction failed: #{Html.esc(plans[:error])}" :
                                 'the model contains no floor surfaces to draw'
          return Html.section('floor-plans', 'Floor plans', %(<p class="meta">#{note}</p>))
        end

        body = +%(<p class="meta">Space and thermal-zone names of the PROPOSED model, one plan per
          storey (polygons tinted per thermal zone; hover a space for its space type and area).
          The reference building's spaces and zones are identical by construction — the reference
          is a clone and no transform renames or rezones.</p>)
        if plans[:inferred_storeys]
          body << %(<p class="warnstrip">&#9650; the model carries no BuildingStory objects — storeys
            were INFERRED from floor elevations (&#177;0.01 m bins).</p>)
        end
        # zone legend deliberately not rendered (too small to read; the zone
        # names are on the plans themselves) — the bundle still carries it.
        plans[:storeys].each do |storey|
          body << %(<div class="page-break"><h3>#{Html.esc(storey[:name])}</h3>#{storey[:svg]}</div>)
        end
        Html.section('floor-plans', 'Floor plans', body)
      end

      # -- checklist -----------------------------------------------------
      def checklist(ctx)
        rows = ctx[:checklist_rows]
        return Html.section('checklist', 'Compliance checklist', '<p>No audited compliance decisions recorded.</p>') if rows.empty?

        table_rows = rows.map do |row|
          [Html.raw(Html.glyph(row.glyph)),
           Html.raw(%(<a href="#audit-#{row.audit_index}">#{Html.esc(row.article.empty? ? '—' : row.article)}</a>)),
           Html.raw(Html.building_chip(row.building)),
           row.statement, row.measured || '—']
        end
        body = Html.table(['', 'Article', 'Applies to', 'Requirement / determination', 'Measured values'], table_rows)
        body += %(<p class="meta">#{Html.glyph(:pass)} complies &nbsp; #{Html.glyph(:fail)} does not comply &nbsp;
          #{Html.glyph(:warning)} warning / modeller attention &nbsp; #{Html.glyph(:info)} scope note &nbsp;
          #{Html.glyph(:na)} informational. "Applies to" says WHICH model the row is about —
          #{Html.building_chip('input model')} the .osm as submitted, #{Html.building_chip('proposed building')} the
          proposed design as run, #{Html.building_chip('reference building')} the code-generated reference,
          #{Html.building_chip(nil)} a cross-building verdict. Each article links to the full audit entry.</p>)
        Html.section('checklist', 'Compliance checklist', body)
      end

      # -- energy --------------------------------------------------------
      def energy(ctx)
        report = ctx[:report]
        proposed = report['proposed'] || {}
        reference = report['reference'] || {}
        has_ref_energy = !reference['total_site_kwh'].nil?
        body = +"<p>#{Html.legend}</p>"

        end_use_rows = (proposed['end_uses_kwh'] || {}).map do |use, value|
          [use.tr('_', ' ').capitalize, value, has_ref_energy ? reference.dig('end_uses_kwh', use) : nil]
        end
        chart = Charts.paired_bars(end_use_rows, unit: 'kWh', label: 'Annual end-use energy, proposed vs reference')
        body << "<h3>End-use breakdown</h3>#{chart}" unless chart.empty?

        totals = []
        totals << ['Proposed', proposed['total_site_kwh']] if proposed['total_site_kwh']
        totals << ['Reference', reference['total_site_kwh']] if has_ref_energy
        targets = []
        targets << ['BET (8.4.4)', report.dig('eui_path', 'bet_kwh') || reference['building_energy_target_kwh']].compact if report['eui_path'] || reference['building_energy_target_kwh']
        chart2 = Charts.total_bars(totals, targets: targets.reject { |t| t.size < 2 })
        body << "<h3>Annual totals</h3>#{chart2}" unless chart2.empty?

        fuel_rows = %w[electricity_kwh natural_gas_kwh district_heating_kwh district_cooling_kwh].filter_map do |fuel|
          p = proposed[fuel]
          r = reference[fuel]
          next if (p.nil? || p.zero?) && (r.nil? || r.zero?)

          [fuel.sub('_kwh', '').tr('_', ' ').capitalize, Html.fmt(p, unit: 'kWh', prec: 0),
           has_ref_energy ? Html.fmt(r, unit: 'kWh', prec: 0) : '—']
        end
        body << "<h3>Energy by fuel</h3>#{Html.table(['Fuel', 'Proposed', 'Reference'], fuel_rows)}" unless fuel_rows.empty?

        if (lines = report.dig('eui_path', 'lines') || reference['lines'])
          line_rows = lines.map do |l|
            l = l.transform_keys(&:to_s)
            [l['archetype'] || l['building_type'], Html.fmt(l['area_m2'], unit: 'm²', prec: 1),
             Html.fmt(l['eui_kwh_per_m2'], unit: 'kWh/m²·yr', prec: 0), Html.fmt(l['kwh'] || l['target_kwh'], unit: 'kWh', prec: 0)]
          end
          body << "<h3>Archetype-EUI building energy target (Table 8.4.4.1)</h3>" \
                  "#{Html.table(['Archetype', 'Floor area', 'Target EUI', 'Target energy'], line_rows)}"
        end

        unmet_p = proposed['unmet_occupied_hours']
        if unmet_p
          unmet_r = reference['unmet_occupied_hours'] || {}
          body << '<h3>Unmet occupied hours (limit 100 h)</h3>'
          body << Html.table(['', 'Proposed', 'Reference'],
                          [['Heating', Html.fmt(unmet_p['heating'], unit: 'h'), Html.fmt(unmet_r['heating'], unit: 'h')],
                           ['Cooling', Html.fmt(unmet_p['cooling'], unit: 'h'), Html.fmt(unmet_r['cooling'], unit: 'h')]])
        end

        if (iterations = report['capacity_iterations']) && !iterations.empty?
          iteration_rows = iterations.map.with_index(1) do |it, i|
            it = it.transform_keys(&:to_s)
            [i, it['action'] || it['adjusted'] || '(see audit)', Html.esc(it.reject { |k, _| k == 'unmet_after' }.to_s[0, 160])]
          end
          body << Html.details("Capacity auto-iteration history (8.4.1.2.(5)) — #{iterations.size} round(s)",
                            Html.table(['Round', 'Adjustment', 'Detail'], iteration_rows))
        end

        Html.section('energy', 'Energy results', body, page_break: true)
      end

      # -- NECB 2025 Part 11 operational GHG -----------------------------
      def ghg(ctx)
        report = ctx[:report]
        proposed_ghg = report.dig('proposed', 'ghg_kg_co2e')
        return '' if proposed_ghg.nil?

        reference_ghg = report.dig('reference', 'ghg_kg_co2e')
        body = +"<p>#{Html.legend}</p>"
        chart = Charts.paired_bars([['Operational GHG', proposed_ghg, reference_ghg]],
                                   unit: 'kg CO₂e/yr', label: 'Annual operational GHG emissions, proposed vs reference')
        body << chart
        pairs = [['Proposed emissions', Html.fmt(proposed_ghg, unit: 'kg CO₂e/yr', prec: 0)]]
        pairs << ['Reference emissions (GHG target)', Html.fmt(reference_ghg, unit: 'kg CO₂e/yr', prec: 0)] if reference_ghg
        if (level = report['ghg'])
          pairs << ['Percent of GHG target', Html.fmt(level['percent_of_ghg_target'], unit: '%')]
          pairs << ['GHG performance level (Table 11.2.1.1)',
                    Html.raw(level['level'] ? Html.badge("LEVEL #{level['level']}", 'ghg') : Html.badge('ABOVE TARGET — no level', 'warn'))]
        end
        body << Html.kv_table(pairs)
        body << %(<p class="meta">Operational GHG per NECB 2025 Part 11: annual energy by fuel multiplied by
          provincial emission factors (see the audited factor values in the audit trail). Levels A–F are
          assigned by percent of the reference building's emissions.</p>)
        Html.section('ghg', 'Operational GHG emissions (NECB 2025 Part 11)', body)
      end

      # -- envelope ------------------------------------------------------
      def envelope(ctx)
        proposed = ctx[:proposed]&.dig(:envelope)
        reference = ctx[:reference]&.dig(:envelope)
        body = +"<p>#{Html.legend}</p>"
        if proposed
          u_rows = proposed[:surfaces].map do |s|
            ref_match = reference&.dig(:surfaces)&.find { |r| r[:type] == s[:type] }
            [s[:type], s[:avg_u_w_per_m2k], ref_match && ref_match[:avg_u_w_per_m2k]]
          end.reject { |_, p, _| p.nil? }
          chart = Charts.paired_bars(u_rows, unit: 'W/m²·K', label: 'Area-weighted average U-value by surface type', prec: 3)
          body << "<h3>Overall thermal transmittance (area-weighted)</h3>#{chart}"

          area_rows = proposed[:surfaces].map do |s|
            [s[:type], Html.fmt(s[:area_m2], unit: 'm²'), Html.fmt(s[:avg_u_w_per_m2k], prec: 3)]
          end
          body << Html.table(['Surface type', 'Exterior area', 'Avg U (W/m²·K)'], area_rows)
          fdwr_rows = [['Fenestration-and-door-to-wall ratio (FDWR)', Html.fmt(proposed[:fdwr], prec: 3),
                        Html.fmt(reference&.dig(:fdwr), prec: 3)],
                       ['Skylight-to-roof ratio (SRR)', Html.fmt(proposed[:srr], prec: 3), Html.fmt(reference&.dig(:srr), prec: 3)]]
          body << Html.table(['Ratio', 'Proposed', 'Reference'], fdwr_rows)
        else
          body << '<p>Model geometry not available to this render (report-only mode).</p>'
        end
        body << domain_audit_notes(ctx, :envelope)
        Html.section('envelope', 'Building envelope', body, page_break: true)
      end

      # -- hvac ----------------------------------------------------------
      # HVAC systems are drawn with openstudio-hvac's OpenStudio-App-style
      # loop-diagram engine (the same one behind the system catalog), so the
      # PROPOSED and REFERENCE buildings show faithful supply/demand topology with
      # native OS App component icons rather than crude schematics. report.rb
      # computes the diagram bundles off the SDK models (ctx[:proposed_hvac] /
      # ctx[:reference_hvac], plain hashes); this SDK-free section only lays them
      # out. The icon <defs> they reference are embedded once by report.rb.
      def hvac(ctx)
        body = +''
        body << hvac_building_block('Proposed building systems', ctx[:proposed_hvac],
                                    group: 'p', present: ctx.key?(:proposed_hvac))
        body << hvac_building_block('Reference building systems', ctx[:reference_hvac],
                                    group: 'r', present: ctx.key?(:reference_hvac), reference: true)
        body << domain_audit_notes(ctx, :hvac)
        Html.section('hvac', 'HVAC systems', body, page_break: true)
      end

      # One labelled HVAC subsection for a building's diagram bundle. `bundle` is
      # the plain hash from OpenStudioHVAC.model_hvac_diagrams (or nil). A nil
      # bundle on the reference means there is no reference building on this path
      # (e.g. the 8.4.4 archetype-EUI path); a nil bundle when the key is absent
      # (canned/report-only render) is stated as such.
      def hvac_building_block(heading, bundle, group:, present:, reference: false)
        out = +"<h3>#{Html.esc(heading)}</h3>"
        if bundle.nil?
          out << if !present
                   '<p class="meta">Model geometry not available to this render (report-only mode).</p>'
                 elsif reference
                   '<p class="meta">No reference building on this path (e.g. the 8.4.4 archetype-EUI path).</p>'
                 else
                   '<p class="meta">Model not available to this render.</p>'
                 end
          return out
        end

        # One entry per loop (+ a final Zone-equipment entry), each with a unique
        # id, presented as an OpenStudio-App-style <select> chooser: picking a
        # loop shows just that loop's diagram (inline JS in report.rb; on print
        # every panel is revealed). The descriptive loop labels come from
        # openstudio-hvac (air loops name their served zone), so N packaged
        # single-zone units read "Air loop — Thermal Zone 1", "Air loop —
        # Thermal Zone 2", … rather than N ambiguous "Air loop" entries.
        entries = (bundle[:loops] || []).each_with_index.map do |loop, i|
          ["#{group}-#{i}", loop[:label], loop[:svg]]
        end
        entries << ["#{group}-z", 'Zone equipment', bundle[:zone_equipment_svg]] if bundle[:zone_equipment_svg]
        if entries.empty?
          out << '<p class="meta">No central HVAC loops (zone-equipment-only or not modelled).</p>'
          return out
        end
        out << hvac_loop_select(group, entries)
        out
      end

      # An OpenStudio-App-style per-building loop chooser: a <select> whose
      # options are the building's loops (+ a Zone-equipment entry), and one
      # hidden panel per entry. The first option is selected and its panel shown;
      # inline JS (report.rb) swaps panels on change and reveals all on print.
      # `entries` = [[id, label, svg], …]; `group` ('p'/'r') keeps the proposed
      # and reference choosers independent.
      def hvac_loop_select(group, entries)
        options = entries.each_with_index.map do |(id, label, _svg), i|
          %(<option value="#{id}"#{i.zero? ? ' selected' : ''}>#{Html.esc(label)}</option>)
        end.join
        panels = entries.each_with_index.map do |(id, label, svg), i|
          %(<div class="loop-panel" id="#{id}"#{i.zero? ? '' : ' hidden'}>) +
            %(<div class="loop-panel-title">#{Html.esc(label)}</div><div class="diagram">#{svg}</div></div>)
        end.join
        %(<div class="hvac-select"><label class="loop-select-label">System: ) +
          %(<select class="loop-select">#{options}</select></label>) +
          %(<div class="loop-view">#{panels}</div></div>)
      end

      # -- lighting ------------------------------------------------------
      def lighting(ctx)
        body = space_type_table(ctx, :lpd_w_per_m2, 'Lighting power density (W/m²)')
        body << domain_audit_notes(ctx, :lighting)
        Html.section('lighting', 'Lighting', body)
      end

      # -- loads ---------------------------------------------------------
      def loads(ctx)
        body = +''
        if (types = ctx[:proposed]&.dig(:space_types)) && !types.empty?
          rows = types.map do |t|
            [t[:name], Html.fmt(t[:area_m2], unit: 'm²'), Html.fmt(t[:people_per_m2], prec: 4),
             Html.fmt(t[:equipment_w_per_m2], unit: 'W/m²', prec: 2)]
          end
          body << Html.table(['Space type', 'Floor area', 'People/m²', 'Receptacle W/m²'], rows)
        else
          body << '<p>No space types with floor area in the proposed model.</p>'
        end
        body << domain_audit_notes(ctx, :loads)
        Html.section('loads', 'Internal loads (occupancy and receptacle)', body)
      end

      # -- shw -----------------------------------------------------------
      def shw(ctx)
        notes = domain_audit_notes(ctx, :shw)
        body = notes.empty? ? '<p>No service water heating decisions recorded for this run.</p>' : notes
        Html.section('shw', 'Service water heating', body)
      end

      # -- costing -------------------------------------------------------
      def costing(ctx)
        report = ctx[:report]
        p_cost = report.dig('proposed', 'cost')
        return '' if p_cost.nil?

        r_cost = report.dig('reference', 'cost') || {}
        rows = %w[hvac envelope total].map do |k|
          [k.capitalize, Html.fmt(p_cost[k], unit: '$', prec: 0), Html.fmt(r_cost[k], unit: '$', prec: 0)]
        end
        body = Html.table(['Scope', 'Proposed', 'Reference'], rows)
        if (delta = report['incremental_cost_proposed_vs_reference'])
          body << Html.kv_table([['Incremental cost, proposed vs reference', Html.fmt(delta, unit: '$', prec: 0)]])
        end
        body << %(<p class="meta">Costing totals only — line-item ledgers stay in the run directory
          (licensed unit costs are never embedded in this report).</p>)
        Html.section('costing', 'Costing summary', body)
      end

      # -- coverage_appendix ---------------------------------------------
      def coverage_appendix(ctx)
        all = ctx[:audit_entries]
        entries = all.each_with_index.select { |e, _| e[:step].to_s == 'coverage' }
        warnings = all.each_with_index.select { |e, _| %i[warn warning].include?(e[:level]) }
        covered = Checklist.covered_articles(all)
        body = +''
        unless entries.empty?
          rows = entries.map do |e, i|
            glyph_kind, status_text = coverage_status(e, covered)
            [Html.raw(Html.glyph(glyph_kind)), status_text, e[:article].to_s, e[:action].to_s,
             Html.raw(%(<a href="#audit-#{i}">entry #{i}</a>))]
          end
          body << "<h3>Article coverage notes</h3>#{Html.table(['', 'Status', 'Article', 'Scope note', 'Audit'], rows)}"
        end
        unless warnings.empty?
          rows = warnings.map do |e, i|
            [Html.raw(Html.glyph(:warning)), Html.raw(Html.building_chip(e[:building])), e[:article].to_s,
             "#{e[:target] ? "#{e[:target]}: " : ''}#{e[:action]}",
             Html.raw(%(<a href="#audit-#{i}">entry #{i}</a>))]
          end
          body << "<h3>All warnings (#{warnings.size})</h3>#{Html.table(['', 'Applies to', 'Article', 'Warning', 'Audit'], rows)}"
        end
        body = '<p>No coverage notes or warnings recorded.</p>' if body.empty?
        Html.section('coverage', 'Scope, coverage and warnings', body, page_break: true)
      end

      # Glyph + human status for one coverage entry, reconciled against the set
      # of articles actually implemented in this audit (host_scope delegations
      # are ✓ when a sibling gem covers the article, ▲ when nobody did).
      def coverage_status(entry, covered)
        inputs = entry[:inputs].is_a?(Hash) ? entry[:inputs] : {}
        status = inputs[:status].to_s
        # gap_owner: "modeller" — the article's remaining gaps are wholly the
        # modeller's responsibility (D-09): a scope note, not a warning.
        return [:info, 'modeller scope'] if inputs[:gap_owner].to_s == 'modeller' &&
                                            %w[partial not_implemented].include?(status)

        case status
        when 'implemented' then [:pass, 'implemented']
        when 'satisfied_by_clone' then [:pass, 'satisfied by clone']
        when 'host_scope'
          if Checklist.covered?(entry[:article].to_s, covered)
            [:pass, 'delegated — covered by another gem in this run']
          else
            [:warning, 'delegated — NOT covered in this run']
          end
        when 'partial' then [:warning, 'partial']
        when 'not_implemented' then [:fail, 'not implemented']
        else [:na, '—']
        end
      end

      # -- rulings_appendix ----------------------------------------------
      # The DECISIONS axis of the audit trail. Where the coverage appendix
      # reports which CODE ARTICLES this run acted on, this one reports which of
      # the project's adjudicated interpretations actually fired — the "why did
      # it do it that way" a reader cannot get from the article citation alone.
      #
      # Self-containment: the summary text IS the documentation (no links out —
      # the report is one file and cites nothing external, by contract).
      # Always rendered, because the TOC link is unconditional and the html
      # tests assert every href resolves.
      def rulings_appendix(ctx)
        fired = {} # id => { count:, first_index: }
        ctx[:audit_entries].each_with_index do |e, i|
          Decisions.ids_in(e[:ruling]).each do |id|
            hit = (fired[id] ||= { count: 0, first_index: i })
            hit[:count] += 1
          end
        end
        body =
          if fired.empty?
            '<p>No ruled code paths fired in this run.</p>'
          else
            rows = fired.sort.map do |id, hit|
              entry = Decisions.lookup(id)
              title = entry ? entry['title'] : 'not in registry'
              summary = entry ? entry['summary'] : "Decision #{id} was cited by this run but is not in the decision registry."
              [id, title, summary, hit[:count],
               Html.raw(%(<a href="#audit-#{hit[:first_index]}">entry #{hit[:first_index]}</a>))]
            end
            Html.table(['Decision', 'Title', 'What was decided, and why', 'Times applied', 'First audit entry'], rows)
          end
        note = %(<p class="meta">Modelling the code requires interpreting it. Each row is an
          interpretation or implementation choice this project adopted and that this run acted on;
          the audit entries above carry the same identifiers alongside the article citation.</p>)
        Html.section('rulings', 'Decisions and assumptions applied', body + note, page_break: true)
      end

      # -- audit_appendix ------------------------------------------------
      def audit_appendix(ctx)
        rows = ctx[:audit_entries].map.with_index do |e, i|
          level = e[:level].to_s
          # decisions get a neutral glyph here; the checklist carries the verdict
          glyph_kind = { 'warn' => :warning, 'warning' => :warning, 'info' => :info }.fetch(level, :na)
          %(<tr id="audit-#{i}"><td>#{i}</td><td>#{Html.glyph(glyph_kind)} #{Html.esc(level)}</td>) +
            %(<td>#{Html.building_chip(e[:building])}</td>) +
            %(<td>#{Html.esc(e[:step])}</td><td>#{Html.esc(e[:target])}</td><td>#{Html.esc(e[:action])}</td>) +
            %(<td>#{Html.esc(e[:article])}</td><td>#{Html.esc(compact_inputs(e))}</td></tr>)
        end.join
        table = %(<table><thead><tr><th>#</th><th>Level</th><th>Applies to</th><th>Step</th><th>Target</th>) +
                %(<th>Action</th><th>Article</th><th>Inputs / value</th></tr></thead><tbody>#{rows}</tbody></table>)
        Html.section('audit', 'Full audit trail',
                  Html.details("#{ctx[:audit_entries].size} audited entries (every value used and article applied)", table))
      end

      def compact_inputs(entry)
        parts = []
        parts << entry[:inputs].map { |k, v| "#{k}=#{v.is_a?(Float) ? v.round(3) : v}" }.join(', ') if entry[:inputs].is_a?(Hash) && !entry[:inputs].empty?
        parts << entry[:value].to_s if entry[:value]
        parts.join(' | ')[0, 220]
      end

      # -- declarations --------------------------------------------------
      def declarations(ctx)
        options = ctx[:options]
        <<~HTML
          <section id="declarations" class="page-break"><h2>Declarations</h2>
            <p>The undersigned declares that the energy model summarized in this report represents the
            design submitted for permit, and that the compliance path(s) declared above were evaluated
            in accordance with NECB #{Html.esc(ctx[:report]['vintage'])} Part 8 using whole-building simulation.</p>
            <div>
              <span class="sig">Energy modeller: #{Html.esc(options[:prepared_by] || '')}&nbsp;<br>Signature / date</span>
              <span class="sig">Registered professional of record: #{Html.esc(options[:professional_of_record] || '')}&nbsp;<br>Signature / seal / date</span>
            </div>
            <footer>Generated by openstudio-necb (openstudio-hvac, -envelope, -loads, -lighting, -shw, -geometry).
            Single-file report: no external resources, scripts or network requests. Audit entries are the
            normative record; this report is a rendering of them.</footer>
          </section>
        HTML
      end

      # -- shared --------------------------------------------------------------
      def space_type_table(ctx, key, heading)
        types = ctx[:proposed]&.dig(:space_types)
        return +'<p>No space types with floor area in the proposed model.</p>' if types.nil? || types.empty?

        ref_types = (ctx[:reference]&.dig(:space_types) || []).to_h { |t| [t[:name], t] }
        rows = types.map do |t|
          ref = ref_types[t[:name]]
          [t[:name], Html.fmt(t[:area_m2], unit: 'm²'), Html.fmt(t[key], prec: 2),
           ref ? Html.fmt(ref[key], prec: 2) : '—']
        end
        +"<h3>#{Html.esc(heading)}</h3>#{Html.table(['Space type', 'Floor area', 'Proposed', 'Reference'], rows)}"
      end

      # Per-domain audit table: decisions + warnings whose step matches the domain.
      def domain_audit_notes(ctx, domain)
        steps = DOMAIN_STEPS[domain]
        picked = ctx[:audit_entries].each_with_index.select do |e, _|
          steps.any? { |s| e[:step].to_s.include?(s) } && %i[decision warn warning].include?(e[:level])
        end
        return '' if picked.empty?

        rows = picked.first(60).map do |e, i|
          [Html.raw(Html.glyph(%i[warn warning].include?(e[:level]) ? :warning : :info)),
           Html.raw(Html.building_chip(e[:building])), e[:article].to_s,
           "#{e[:target] ? "#{e[:target]}: " : ''}#{e[:action]}",
           Html.raw(%(<a href="#audit-#{i}">##{i}</a>))]
        end
        note = picked.size > 60 ? %(<p class="meta">Showing 60 of #{picked.size} — see the full audit trail.</p>) : ''
        Html.details("Audited decisions for this domain (#{picked.size})",
                  Html.table(['', 'Applies to', 'Article', 'Decision', 'Audit'], rows) + note)
      end
    end
  end
end
