"""One function per report section, assembled in ORDER (port of
report/sections.rb). All functions take the same context and return an HTML
string ('' to omit the section).

ctx: {'report':, 'audit_entries':, 'checklist_rows':, 'proposed':,
      'reference':, 'proposed_hvac':, 'reference_hvac':, 'floor_plans':,
      'options':} — proposed/reference are model_query.extract dicts
(reference None on EUI-only runs). All keys are strings (the Python audit
and diagram bundles are str-keyed throughout, D-79)."""

from __future__ import annotations

import re

from btap._compat import ruby_round, ruby_str
from btap.necb import decisions as Decisions
from btap.necb.report import charts as Charts
from btap.necb.report import checklist as Checklist
from btap.necb.report import html as Html

ORDER = ("header", "verdict_banner", "path_declaration", "floor_plans",
         "checklist", "energy", "ghg", "envelope", "hvac", "lighting", "loads",
         "shw", "costing", "coverage_appendix", "rulings_appendix",
         "audit_appendix", "declarations")

#: CONTRACT: maps each per-domain report section to the audit ``step`` names
#: (substring match) whose entries it renders as notes. A NEW audit step name
#: introduced in any package must be added here, or its entries silently drop
#: out of that domain's section (they still appear in the full audit trail
#: appendix).
DOMAIN_STEPS = {
    "envelope": ("envelope", "reference_envelope", "thermal_bridging", "fdwr", "srr"),
    "hvac": ("selection", "build", "efficiency", "reference_hvac", "economizer",
             "fan_power", "energy_recovery", "check_part5", "capacity_iteration"),
    "lighting": ("lights", "lighting", "daylighting", "reference_daylighting"),
    "loads": ("loads", "space_types", "assign_space_types", "occupancy",
              "plug_loads"),
    "shw": ("shw", "service_water_heating"),
}


def render_all(ctx):
    return "\n".join(globals()[name](ctx) for name in ORDER)


def _dig(mapping, *keys):
    """Ruby Hash#dig for nested str-keyed dicts."""
    current = mapping
    for key in keys:
        if not isinstance(current, dict):
            return None
        current = current.get(key)
        if current is None:
            return None
    return current


# -- header --------------------------------------------------------

def header(ctx):
    report = ctx["report"]
    options = ctx.get("options") or {}
    project = [
        ["Project name", options.get("project_name") or "(not provided)"],
        ["Address", options.get("address") or "(not provided)"],
        ["Permit / application no.", options.get("permit_number") or "(not provided)"],
        ["Prepared by", options.get("prepared_by") or "(not provided)"],
        ["Report date", options.get("date") or "(run date not stamped)"],
        ["Code edition", f"NECB {report.get('vintage')}"],
        ["Heating degree-days (HDD18)", Html.fmt(report.get("hdd"), prec=0)],
        ["Simulation mode", report.get("simulate")],
    ]
    ghg_link = ('<a href="#ghg">GHG</a>'
                if _dig(report, "proposed", "ghg_kg_co2e") is not None else "")
    return f"""<header>
  <h1>NECB {Html.esc(report.get('vintage'))} Energy Code Compliance Report</h1>
  <p class="meta">Modelled compliance evidence package for the authority having jurisdiction.
  Generated by the btap family (SDK-only NECB implementation with article-cited audit trail).</p>
  {Html.kv_table(project)}
  <nav class="toc">
    <a href="#verdict">Summary</a><a href="#paths">Compliance paths</a><a href="#checklist">Checklist</a>
    <a href="#floor-plans">Floor plans</a><a href="#energy">Energy</a>{ghg_link}<a href="#envelope">Envelope</a><a href="#hvac">HVAC</a>
    <a href="#lighting">Lighting</a><a href="#loads">Loads</a><a href="#shw">SHW</a>
    <a href="#coverage">Coverage</a><a href="#rulings">Decisions</a><a href="#audit">Audit trail</a>
  </nav>
</header>
"""


# -- verdict_banner ------------------------------------------------

def verdict_banner(ctx):
    report = ctx["report"]
    badges = []
    if report.get("compliant") is not None:
        compliant = report["compliant"]
        badges.append(Html.badge(
            "PERFORMANCE PATH: PASS" if compliant else "PERFORMANCE PATH: FAIL",
            "pass" if compliant else "fail"))
    eui = report.get("eui_path")
    if eui:
        if eui.get("computed") is False:
            # the as-specified run cannot lawfully serve the 8.4.4 verdict
            # (Table 8.4.4.2 non-conformance / applicability) — say so, never
            # render a pass/fail that was not determined
            badges.append(Html.badge("EUI PATH (8.4.4): NOT COMPUTED", "warn"))
        else:
            ok = eui.get("compliant")
            badges.append(Html.badge(
                "EUI PATH (8.4.4): PASS" if ok else "EUI PATH (8.4.4): FAIL",
                "pass" if ok else "fail"))
    method = str(_dig(report, "reference", "method") or "")
    if "archetype" in method and report.get("compliant") is not None:
        compliant = report["compliant"]
        badges[0] = Html.badge(
            "EUI PATH (8.4.4): PASS" if compliant else "EUI PATH (8.4.4): FAIL",
            "pass" if compliant else "fail")
    # The performance-path tier (vs the reference building) and the EUI-path
    # tier (vs the archetype target) measure the SAME proposed energy against
    # DIFFERENT targets, so they can differ — label each by its path.
    eui_tier = _dig(report, "eui_path", "tier")
    if report.get("tier") and eui_tier:
        badges.append(Html.badge(f"PERFORMANCE TIER {report['tier']}", "tier"))
        badges.append(Html.badge(f"EUI TIER {eui_tier}", "tier"))
    elif report.get("tier"):
        badges.append(Html.badge(f"TIER {report['tier']}", "tier"))
    if _dig(report, "ghg", "level"):
        badges.append(Html.badge(f"GHG LEVEL {_dig(report, 'ghg', 'level')}", "ghg"))
    if report.get("compliant") is None:
        badges.append(Html.badge("UNDETERMINED (no annual run)", "warn"))

    proposed_kwh = _dig(report, "proposed", "total_site_kwh")
    target_kwh = (_dig(report, "reference", "total_site_kwh")
                  or _dig(report, "reference", "building_energy_target_kwh"))
    numbers = []
    if proposed_kwh is not None:
        numbers.append(
            f"Proposed: <strong>{Html.fmt(proposed_kwh, prec=0)} kWh</strong>"
            f" ({Html.fmt(_dig(report, 'proposed', 'eui_kwh_per_m2'))} kWh/m²·yr)")
    if target_kwh is not None:
        numbers.append(f"Target: <strong>{Html.fmt(target_kwh, prec=0)} kWh</strong>")
    if proposed_kwh is not None and target_kwh is not None and target_kwh > 0:
        margin = 100.0 * (target_kwh - proposed_kwh) / target_kwh
        direction = "over" if margin < 0 else "under"
        numbers.append(
            f"Margin: <strong>{ruby_round(margin, 1)}%</strong> {direction} target")

    strip = ""
    if report.get("annual") is False:
        strip = ('<p class="warnstrip">▲ SHORTENED RUN PERIOD — the results below '
                 "use the same arithmetic\n            but are NOT a code-compliant "
                 "annual determination (NECB 8.4.1.2 requires a simulated year).</p>")
    if report.get("tier") and eui_tier and report["tier"] != eui_tier:
        bet = _dig(report, "eui_path", "bet_kwh")
        strip += (
            f'<p class="meta">The performance-path tier ({report["tier"]}, vs the '
            f"reference building\n            {Html.fmt(target_kwh, prec=0)} kWh) and "
            f"the EUI-path tier ({eui_tier}, vs the archetype target\n            "
            f"{Html.fmt(bet, prec=0)} kWh) differ because the same proposed energy is "
            "measured against different\n            targets — a building declares "
            "the tier of whichever compliance path it uses.</p>")
    return ('<section id="verdict"><div class="banner">'
            '<span class="big">Compliance summary</span>\n          '
            + " ".join(badges)
            + f"<span>{' &nbsp;•&nbsp; '.join(numbers)}</span></div>{strip}</section>")


# -- path_declaration ----------------------------------------------

def path_declaration(ctx):
    report = ctx["report"]
    eui_primary = "archetype" in str(_dig(report, "reference", "method") or "")
    rows = []
    perf_used = not eui_primary and report.get("compliant") is not None
    rows.append([Html.raw("●" if perf_used else "○"),
                 "NECB 8.4.1.2 — Building Energy Performance (reference building)",
                 verdict_text(report.get("compliant") if perf_used else None)])
    eui_not_computed = _dig(report, "eui_path", "computed") is False
    eui_used = eui_primary or (report.get("eui_path") is not None
                               and not eui_not_computed)
    if eui_primary:
        eui_verdict = report.get("compliant")
    elif eui_used:
        eui_verdict = report["eui_path"].get("compliant")
    else:
        eui_verdict = None
    if eui_not_computed:
        eui_result = f"Not computed — {_dig(report, 'eui_path', 'reason')}"
    else:
        eui_result = verdict_text(eui_verdict if eui_used else None)
    rows.append([Html.raw("●" if eui_used else "○"),
                 "NECB 8.4.4 — Archetype Energy Use Intensity (2025)", eui_result])
    rows.append([Html.raw("○"), "NECB Parts 3–7 — Prescriptive/trade-off paths",
                 "Not declared by this report (see Part 5 QAQC notes in the HVAC "
                 "section if run)"])
    body = Html.table(["Used", "Compliance path", "Result"], rows)
    body += ('<p class="meta">Path declaration mirrors the City of Vancouver '
             "Building Energy Design\n          Statement structure: ● declared "
             "path(s), ○ paths not relied upon.</p>")
    return Html.section("paths", "Compliance path declaration", body)


def verdict_text(verdict):
    if verdict is True:
        return Html.raw(f"{Html.glyph('pass')} Complies")
    if verdict is False:
        return Html.raw(f"{Html.glyph('fail')} Does not comply")
    return "Not used / not determined"


# -- floor_plans ---------------------------------------------------
# Per-storey plan views from btap.modeling's plan engine (PROPOSED model; the
# reference's spaces/zones are identical by clone — stated in the section).
# ctx['floor_plans'] is the never-raise bundle {'storeys': [{'name':,
# 'svg':}], 'legend_svg':, 'empty':, 'inferred_storeys':, 'error':};
# absent/empty/error all render as a one-line note.

def floor_plans(ctx):
    plans = ctx.get("floor_plans")
    if plans is None:
        return Html.section(
            "floor-plans", "Floor plans",
            '<p class="meta">No model was available to draw floor plans from.</p>')
    if plans.get("error") or plans.get("empty") or not plans.get("storeys"):
        note = (f"floor-plan extraction failed: {Html.esc(plans['error'])}"
                if plans.get("error")
                else "the model contains no floor surfaces to draw")
        return Html.section("floor-plans", "Floor plans",
                            f'<p class="meta">{note}</p>')

    body = ('<p class="meta">Space and thermal-zone names of the PROPOSED model, '
            "one plan per\n          storey (polygons tinted per thermal zone; hover "
            "a space for its space type and area).\n          The reference "
            "building's spaces and zones are identical by construction — the "
            "reference\n          is a clone and no transform renames or "
            "rezones.</p>")
    if plans.get("inferred_storeys"):
        body += ('<p class="warnstrip">&#9650; the model carries no BuildingStory '
                 "objects — storeys\n            were INFERRED from floor elevations "
                 "(&#177;0.01 m bins).</p>")
    # zone legend deliberately not rendered (too small to read; the zone names
    # are on the plans themselves) — the bundle still carries it.
    for storey in plans["storeys"]:
        body += (f'<div class="page-break"><h3>{Html.esc(storey["name"])}</h3>'
                 f'{storey["svg"]}</div>')
    return Html.section("floor-plans", "Floor plans", body)


# -- checklist -----------------------------------------------------

def _selected_vintage_coverage_text(text, vintage):
    """Keep user-facing application detail, omitting compatibility history."""
    selected = str(vintage or "")
    text = str(text)
    if selected:
        text = text.replace("the 2020/2025 code", f"NECB {selected}")
        text = text.replace("the 2025/2020 code", f"NECB {selected}")
        text = re.sub(r"\s*\(D-57, placement: :necb2020, the default\)",
                      " (D-57)", text)
    text = re.sub(r"\s*The legacy NECB 2011 rule.*?(?=\. Gaps:|$)", "", text)
    text = text.replace(".. Gaps:", ". Gaps:")
    return text.strip()


def _checklist_statement_html(statement, *, vintage=None, coverage=False):
    """Give long coverage determinations a summary / applied / gaps hierarchy."""
    text = (_selected_vintage_coverage_text(statement, vintage)
            if coverage else str(statement))
    applied_marker = " Applied: "
    gaps_marker = " Gaps: "
    if applied_marker not in text:
        return f'<div class="checklist-statement">{Html.esc(text)}</div>'

    summary, detail = text.split(applied_marker, 1)
    applied, separator, gaps = detail.partition(gaps_marker)
    body = (f'<div class="checklist-summary">{Html.esc(summary)}</div>'
            '<div class="checklist-detail"><span>Applied</span> '
            f'{Html.esc(applied)}</div>')
    if separator:
        body += ('<div class="checklist-detail checklist-gaps"><span>Gaps</span> '
                 f'{Html.esc(gaps)}</div>')
    return f'<div class="checklist-statement">{body}</div>'


def _checklist_article(article):
    """Display the governing citation without cross-edition provenance notes."""
    return re.sub(r"\s*\(Table verified identical \d{4}/\d{4}\)\s*$", "",
                  str(article))


def checklist(ctx):
    rows = ctx["checklist_rows"]
    if not rows:
        return Html.section("checklist", "Compliance checklist",
                            "<p>No audited compliance decisions recorded.</p>")

    table_rows = []
    vintage = (ctx.get("report") or {}).get("vintage")
    for row in rows:
        determination = _checklist_statement_html(
            row.statement, vintage=vintage, coverage=row.coverage)
        if row.measured is not None:
            determination += (
                '<div class="checklist-evidence"><span>Evidence</span> '
                f'{Html.esc(row.measured)}</div>')
        table_rows.append([
            Html.raw(Html.glyph(row.glyph)),
            Html.raw(f'<a href="#audit-{row.audit_index}">'
                     f"{Html.esc(_checklist_article(row.article) if row.article else '—')}</a>"),
            Html.raw(Html.building_chip(row.building)),
            Html.raw(determination),
        ])
    body = Html.table(["", "Article", "Applies to", "Requirement / determination"],
                      table_rows, css="checklist")
    body += (
        f'<p class="meta">{Html.glyph("pass")} complies &nbsp; '
        f'{Html.glyph("fail")} does not comply &nbsp;\n          '
        f'{Html.glyph("warning")} warning / modeller attention &nbsp; '
        f'{Html.glyph("info")} scope note &nbsp;\n          '
        f'{Html.glyph("na")} informational. "Applies to" says WHICH model the row '
        f"is about —\n          {Html.building_chip('input model')} the .osm as "
        f"submitted, {Html.building_chip('proposed building')} the\n          "
        f"proposed design as run, {Html.building_chip('reference building')} the "
        f"code-generated reference,\n          {Html.building_chip(None)} a "
        "cross-building verdict. Each article links to the full audit entry.</p>")
    return Html.section("checklist", "Compliance checklist", body)


# -- energy --------------------------------------------------------

def energy(ctx):
    report = ctx["report"]
    proposed = report.get("proposed") or {}
    reference = report.get("reference") or {}
    has_ref_energy = reference.get("total_site_kwh") is not None
    body = f"<p>{Html.legend()}</p>"

    end_use_rows = [
        [use.replace("_", " ").capitalize(), value,
         _dig(reference, "end_uses_kwh", use) if has_ref_energy else None]
        for use, value in (proposed.get("end_uses_kwh") or {}).items()]
    chart = Charts.paired_bars(end_use_rows, unit="kWh",
                               label="Annual end-use energy, proposed vs reference")
    if chart:
        body += f"<h3>End-use breakdown</h3>{chart}"

    totals = []
    if proposed.get("total_site_kwh") is not None:
        totals.append(["Proposed", proposed["total_site_kwh"]])
    if has_ref_energy:
        totals.append(["Reference", reference["total_site_kwh"]])
    targets = []
    if report.get("eui_path") or reference.get("building_energy_target_kwh"):
        target_value = (_dig(report, "eui_path", "bet_kwh")
                        or reference.get("building_energy_target_kwh"))
        if target_value is not None:
            targets.append(["BET (8.4.4)", target_value])
    chart2 = Charts.total_bars(totals, targets=targets)
    if chart2:
        body += f"<h3>Annual totals</h3>{chart2}"

    fuel_rows = []
    for fuel in ("electricity_kwh", "natural_gas_kwh", "district_heating_kwh",
                 "district_cooling_kwh"):
        p = proposed.get(fuel)
        r = reference.get(fuel)
        if (p is None or p == 0) and (r is None or r == 0):
            continue

        fuel_rows.append([
            fuel.replace("_kwh", "").replace("_", " ").capitalize(),
            Html.fmt(p, unit="kWh", prec=0),
            Html.fmt(r, unit="kWh", prec=0) if has_ref_energy else "—"])
    if fuel_rows:
        body += ("<h3>Energy by fuel</h3>"
                 + Html.table(["Fuel", "Proposed", "Reference"], fuel_rows))

    lines = _dig(report, "eui_path", "lines") or reference.get("lines")
    if lines:
        line_rows = [
            [line.get("archetype") or line.get("building_type"),
             Html.fmt(line.get("area_m2"), unit="m²", prec=1),
             Html.fmt(line.get("eui_kwh_per_m2"), unit="kWh/m²·yr", prec=0),
             Html.fmt(line.get("kwh") or line.get("target_kwh"), unit="kWh", prec=0)]
            for line in lines]
        body += ("<h3>Archetype-EUI building energy target (Table 8.4.4.1)</h3>"
                 + Html.table(["Archetype", "Floor area", "Target EUI",
                               "Target energy"], line_rows))

    unmet_p = proposed.get("unmet_occupied_hours")
    if unmet_p:
        unmet_r = reference.get("unmet_occupied_hours") or {}
        body += "<h3>Unmet occupied hours (limit 100 h)</h3>"
        body += Html.table(
            ["", "Proposed", "Reference"],
            [["Heating", Html.fmt(unmet_p.get("heating"), unit="h"),
              Html.fmt(unmet_r.get("heating"), unit="h")],
             ["Cooling", Html.fmt(unmet_p.get("cooling"), unit="h"),
              Html.fmt(unmet_r.get("cooling"), unit="h")]])

    iterations = report.get("capacity_iterations")
    if iterations:
        iteration_rows = []
        for i, it in enumerate(iterations, 1):
            detail = {k: v for k, v in it.items() if k != "unmet_after"}
            iteration_rows.append(
                [i, it.get("action") or it.get("adjusted") or "(see audit)",
                 Html.esc(ruby_str(detail)[:160])])
        body += Html.details(
            "Capacity auto-iteration history (8.4.1.2.(5)) — "
            f"{len(iterations)} round(s)",
            Html.table(["Round", "Adjustment", "Detail"], iteration_rows))

    return Html.section("energy", "Energy results", body, page_break=True)


# -- NECB 2025 Part 11 operational GHG -----------------------------

def ghg(ctx):
    report = ctx["report"]
    proposed_ghg = _dig(report, "proposed", "ghg_kg_co2e")
    if proposed_ghg is None:
        return ""

    reference_ghg = _dig(report, "reference", "ghg_kg_co2e")
    body = f"<p>{Html.legend()}</p>"
    body += Charts.paired_bars(
        [["Operational GHG", proposed_ghg, reference_ghg]],
        unit="kg CO₂e/yr",
        label="Annual operational GHG emissions, proposed vs reference")
    pairs = [["Proposed emissions",
              Html.fmt(proposed_ghg, unit="kg CO₂e/yr", prec=0)]]
    if reference_ghg is not None:
        pairs.append(["Reference emissions (GHG target)",
                      Html.fmt(reference_ghg, unit="kg CO₂e/yr", prec=0)])
    level = report.get("ghg")
    if level:
        pairs.append(["Percent of GHG target",
                      Html.fmt(level.get("percent_of_ghg_target"), unit="%")])
        pairs.append(["GHG performance level (Table 11.2.1.1)",
                      Html.raw(Html.badge(f"LEVEL {level['level']}", "ghg")
                               if level.get("level")
                               else Html.badge("ABOVE TARGET — no level", "warn"))])
    body += Html.kv_table(pairs)
    body += ('<p class="meta">Operational GHG per NECB 2025 Part 11: annual energy '
             "by fuel multiplied by\n          provincial emission factors (see the "
             "audited factor values in the audit trail). Levels A–F are\n          "
             "assigned by percent of the reference building's emissions.</p>")
    return Html.section("ghg", "Operational GHG emissions (NECB 2025 Part 11)", body)


# -- envelope ------------------------------------------------------

def envelope(ctx):
    proposed = _dig(ctx.get("proposed") or {}, "envelope")
    reference = _dig(ctx.get("reference") or {}, "envelope")
    body = f"<p>{Html.legend()}</p>"
    if proposed:
        u_rows = []
        for s in proposed["surfaces"]:
            ref_match = next((r for r in (reference or {}).get("surfaces", [])
                              if r["type"] == s["type"]), None)
            if s["avg_u_w_per_m2k"] is None:
                continue
            u_rows.append([s["type"], s["avg_u_w_per_m2k"],
                           ref_match and ref_match["avg_u_w_per_m2k"]])
        chart = Charts.paired_bars(
            u_rows, unit="W/m²·K",
            label="Area-weighted average U-value by surface type", prec=3)
        body += f"<h3>Overall thermal transmittance (area-weighted)</h3>{chart}"

        area_rows = [[s["type"], Html.fmt(s["area_m2"], unit="m²"),
                      Html.fmt(s["avg_u_w_per_m2k"], prec=3)]
                     for s in proposed["surfaces"]]
        body += Html.table(["Surface type", "Exterior area", "Avg U (W/m²·K)"],
                           area_rows)
        fdwr_rows = [
            ["Fenestration-and-door-to-wall ratio (FDWR)",
             Html.fmt(proposed["fdwr"], prec=3),
             Html.fmt((reference or {}).get("fdwr"), prec=3)],
            ["Skylight-to-roof ratio (SRR)", Html.fmt(proposed["srr"], prec=3),
             Html.fmt((reference or {}).get("srr"), prec=3)]]
        body += Html.table(["Ratio", "Proposed", "Reference"], fdwr_rows)
    else:
        body += "<p>Model geometry not available to this render (report-only mode).</p>"
    body += domain_audit_notes(ctx, "envelope")
    return Html.section("envelope", "Building envelope", body, page_break=True)


# -- hvac ----------------------------------------------------------
# HVAC systems are drawn with btap.modeling's OpenStudio-App-style
# loop-diagram engine (the same one behind the system catalog). The report
# assembler computes the diagram bundles off the SDK models
# (ctx['proposed_hvac'] / ctx['reference_hvac'], plain dicts); this SDK-free
# section only lays them out. The icon <defs> they reference are embedded once
# by the assembler.

def hvac(ctx):
    body = ""
    body += hvac_building_block("Proposed building systems",
                                ctx.get("proposed_hvac"), group="p",
                                present="proposed_hvac" in ctx)
    body += hvac_building_block("Reference building systems",
                                ctx.get("reference_hvac"), group="r",
                                present="reference_hvac" in ctx, reference=True)
    body += domain_audit_notes(ctx, "hvac")
    return Html.section("hvac", "HVAC systems", body, page_break=True)


def hvac_building_block(heading, bundle, *, group, present, reference=False):
    """One labelled HVAC subsection for a building's diagram bundle. `bundle`
    is the plain dict from btap.modeling.model_hvac_diagrams (or None). A None
    bundle on the reference means there is no reference building on this path
    (e.g. the 8.4.4 archetype-EUI path); a None bundle when the key is absent
    (canned/report-only render) is stated as such."""
    out = f"<h3>{Html.esc(heading)}</h3>"
    if bundle is None:
        if not present:
            out += ('<p class="meta">Model geometry not available to this render '
                    "(report-only mode).</p>")
        elif reference:
            out += ('<p class="meta">No reference building on this path '
                    "(e.g. the 8.4.4 archetype-EUI path).</p>")
        else:
            out += '<p class="meta">Model not available to this render.</p>'
        return out

    # One entry per loop (+ a final Zone-equipment entry), each with a unique
    # id, presented as an OpenStudio-App-style <select> chooser: picking a
    # loop shows just that loop's diagram (inline JS in the assembler; on
    # print every panel is revealed). The descriptive loop labels come from
    # btap.modeling (air loops name their served zone).
    entries = [(f"{group}-{i}", loop["label"], loop["svg"])
               for i, loop in enumerate(bundle.get("loops") or [])]
    if bundle.get("zone_equipment_svg"):
        entries.append((f"{group}-z", "Zone equipment",
                        bundle["zone_equipment_svg"]))
    if not entries:
        out += ('<p class="meta">No central HVAC loops (zone-equipment-only or '
                "not modelled).</p>")
        return out
    out += hvac_loop_select(group, entries)
    return out


def hvac_loop_select(group, entries):
    """An OpenStudio-App-style per-building loop chooser: a <select> whose
    options are the building's loops (+ a Zone-equipment entry), and one
    hidden panel per entry. The first option is selected and its panel shown;
    inline JS (the assembler) swaps panels on change and reveals all on print.
    `entries` = [(id, label, svg), …]; `group` ('p'/'r') keeps the proposed
    and reference choosers independent."""
    options = "".join(
        f'<option value="{id}"{" selected" if i == 0 else ""}>'
        f"{Html.esc(label)}</option>"
        for i, (id, label, _svg) in enumerate(entries))
    panels = "".join(
        f'<div class="loop-panel" id="{id}"{"" if i == 0 else " hidden"}>'
        f'<div class="loop-panel-title">{Html.esc(label)}</div>'
        f'<div class="diagram">{svg}</div></div>'
        for i, (id, label, svg) in enumerate(entries))
    return ('<div class="hvac-select"><label class="loop-select-label">System: '
            f'<select class="loop-select">{options}</select></label>'
            f'<div class="loop-view">{panels}</div></div>')


# -- lighting ------------------------------------------------------

def lighting(ctx):
    body = space_type_table(ctx, "lpd_w_per_m2", "Lighting power density (W/m²)")
    body += domain_audit_notes(ctx, "lighting")
    return Html.section("lighting", "Lighting", body)


# -- loads ---------------------------------------------------------

def loads(ctx):
    body = ""
    types = _dig(ctx.get("proposed") or {}, "space_types")
    if types:
        rows = [[t["name"], Html.fmt(t["area_m2"], unit="m²"),
                 Html.fmt(t["people_per_m2"], prec=4),
                 Html.fmt(t["equipment_w_per_m2"], unit="W/m²", prec=2)]
                for t in types]
        body += Html.table(["Space type", "Floor area", "People/m²",
                            "Receptacle W/m²"], rows)
    else:
        body += "<p>No space types with floor area in the proposed model.</p>"
    body += domain_audit_notes(ctx, "loads")
    return Html.section("loads", "Internal loads (occupancy and receptacle)", body)


# -- shw -----------------------------------------------------------

def shw(ctx):
    notes = domain_audit_notes(ctx, "shw")
    body = notes if notes else ("<p>No service water heating decisions recorded "
                                "for this run.</p>")
    return Html.section("shw", "Service water heating", body)


# -- costing -------------------------------------------------------

def costing(ctx):
    report = ctx["report"]
    p_cost = _dig(report, "proposed", "cost")
    if p_cost is None:
        return ""

    r_cost = _dig(report, "reference", "cost") or {}
    rows = [[k.capitalize(), Html.fmt(p_cost.get(k), unit="$", prec=0),
             Html.fmt(r_cost.get(k), unit="$", prec=0)]
            for k in ("hvac", "envelope", "total")]
    body = Html.table(["Scope", "Proposed", "Reference"], rows)
    delta = report.get("incremental_cost_proposed_vs_reference")
    if delta is not None:
        body += Html.kv_table([["Incremental cost, proposed vs reference",
                                Html.fmt(delta, unit="$", prec=0)]])
    body += ('<p class="meta">Costing totals only — line-item ledgers stay in the '
             "run directory\n          (licensed unit costs are never embedded in "
             "this report).</p>")
    return Html.section("costing", "Costing summary", body)


# -- coverage_appendix ---------------------------------------------

def coverage_appendix(ctx):
    all_entries = ctx["audit_entries"]
    entries = [(e, i) for i, e in enumerate(all_entries)
               if str(e.get("step") or "") == "coverage"]
    warnings = [(e, i) for i, e in enumerate(all_entries)
                if e.get("level") == "warning"]
    covered = Checklist.covered_articles(all_entries)
    body = ""
    if entries:
        rows = []
        for e, i in entries:
            glyph_kind, status_text = coverage_status(e, covered)
            rows.append([Html.raw(Html.glyph(glyph_kind)), status_text,
                         str(e.get("article") or ""), str(e.get("action") or ""),
                         Html.raw(f'<a href="#audit-{i}">entry {i}</a>')])
        body += ("<h3>Technical implementation notes</h3>"
             "<p class=\"meta\">The Article column identifies the governing "
             "requirement for this report's selected NECB edition. These "
             "technical notes preserve implementation history and may compare "
             "other editions; those references are context, not additional "
             "requirements applied to this building.</p>"
                 + Html.table(["", "Status", "Article", "Scope note", "Audit"], rows))
    if warnings:
        rows = []
        for e, i in warnings:
            target = e.get("target")
            prefix = f"{target}: " if target is not None else ""
            rows.append([Html.raw(Html.glyph("warning")),
                         Html.raw(Html.building_chip(e.get("building"))),
                         str(e.get("article") or ""),
                         f"{prefix}{e.get('action')}",
                         Html.raw(f'<a href="#audit-{i}">entry {i}</a>')])
        body += (f"<h3>All warnings ({len(warnings)})</h3>"
                 + Html.table(["", "Applies to", "Article", "Warning", "Audit"],
                              rows))
    if not body:
        body = "<p>No coverage notes or warnings recorded.</p>"
    return Html.section("coverage", "Scope, coverage and warnings", body,
                        page_break=True)


def coverage_status(entry, covered):
    """Glyph + human status for one coverage entry, reconciled against the
    set of articles actually implemented in this audit (host_scope delegations
    are ✓ when a sibling package covers the article, ▲ when nobody did)."""
    inputs = entry.get("inputs") if isinstance(entry.get("inputs"), dict) else {}
    status = str(inputs.get("status") or "")
    # gap_owner: "modeller" — the article's remaining gaps are wholly the
    # modeller's responsibility (D-09): a scope note, not a warning.
    if (str(inputs.get("gap_owner") or "") == "modeller"
            and status in ("partial", "not_implemented")):
        return ("info", "modeller scope")

    if status == "implemented":
        return ("pass", "implemented")
    if status == "satisfied_by_clone":
        return ("pass", "satisfied by clone")
    if status == "host_scope":
        if Checklist.covered_by(str(entry.get("article") or ""), covered):
            return ("pass", "delegated — covered by another gem in this run")
        return ("warning", "delegated — NOT covered in this run")
    if status == "partial":
        return ("warning", "partial")
    if status == "not_implemented":
        return ("fail", "not implemented")
    return ("na", "—")


# -- rulings_appendix ----------------------------------------------
# The DECISIONS axis of the audit trail. Where the coverage appendix reports
# which CODE ARTICLES this run acted on, this one reports which of the
# project's adjudicated interpretations actually fired — the "why did it do
# it that way" a reader cannot get from the article citation alone.
#
# Self-containment: the summary text IS the documentation (no links out — the
# report is one file and cites nothing external, by contract). Always
# rendered, because the TOC link is unconditional and the html tests assert
# every href resolves.

def rulings_appendix(ctx):
    fired: dict[str, dict] = {}  # id => {'count':, 'first_index':}
    for i, e in enumerate(ctx["audit_entries"]):
        for id in Decisions.ids_in(e.get("ruling")):
            hit = fired.setdefault(id, {"count": 0, "first_index": i})
            hit["count"] += 1
    if not fired:
        body = "<p>No ruled code paths fired in this run.</p>"
    else:
        rows = []
        for id, hit in sorted(fired.items()):
            entry = Decisions.lookup(id)
            title = entry["title"] if entry else "not in registry"
            summary = (entry["summary"] if entry
                       else f"Decision {id} was cited by this run but is not in "
                            "the decision registry.")
            rows.append([id, title, summary, hit["count"],
                         Html.raw(f'<a href="#audit-{hit["first_index"]}">'
                                  f'entry {hit["first_index"]}</a>')])
        body = Html.table(["Decision", "Title", "What was decided, and why",
                           "Times applied", "First audit entry"], rows)
    note = ('<p class="meta">Modelling the code requires interpreting it. Each row '
            "is an\n          interpretation or implementation choice this project "
            "adopted and that this run acted on;\n          the audit entries above "
            "carry the same identifiers alongside the article citation.</p>")
    return Html.section("rulings", "Decisions and assumptions applied", body + note,
                        page_break=True)


# -- audit_appendix ------------------------------------------------

def audit_appendix(ctx):
    rows = []
    for i, e in enumerate(ctx["audit_entries"]):
        level = str(e.get("level") or "")
        # decisions get a neutral glyph here; the checklist carries the verdict
        glyph_kind = {"warning": "warning", "info": "info"}.get(level, "na")
        rows.append(
            f'<tr id="audit-{i}"><td>{i}</td>'
            f"<td>{Html.glyph(glyph_kind)} {Html.esc(level)}</td>"
            f"<td>{Html.building_chip(e.get('building'))}</td>"
            f"<td>{Html.esc(e.get('step'))}</td><td>{Html.esc(e.get('target'))}</td>"
            f"<td>{Html.esc(e.get('action'))}</td>"
            f"<td>{Html.esc(e.get('article'))}</td>"
            f"<td>{Html.esc(compact_inputs(e))}</td></tr>")
    table = ("<table><thead><tr><th>#</th><th>Level</th><th>Applies to</th>"
             "<th>Step</th><th>Target</th><th>Action</th><th>Article</th>"
             "<th>Inputs / value</th></tr></thead><tbody>"
             + "".join(rows) + "</tbody></table>")
    return Html.section(
        "audit", "Full audit trail",
        Html.details(f"{len(ctx['audit_entries'])} audited entries (every value "
                     "used and article applied)", table))


def compact_inputs(entry):
    parts = []
    inputs = entry.get("inputs")
    if isinstance(inputs, dict) and inputs:
        parts.append(", ".join(
            f"{k}={ruby_str(ruby_round(v, 3) if isinstance(v, float) else v)}"
            for k, v in inputs.items()))
    if entry.get("value") is not None:
        parts.append(ruby_str(entry["value"]))
    return " | ".join(parts)[:220]


# -- declarations --------------------------------------------------

def declarations(ctx):
    options = ctx.get("options") or {}
    return f"""<section id="declarations" class="page-break"><h2>Declarations</h2>
  <p>The undersigned declares that the energy model summarized in this report represents the
  design submitted for permit, and that the compliance path(s) declared above were evaluated
  in accordance with NECB {Html.esc(ctx['report'].get('vintage'))} Part 8 using whole-building simulation.</p>
  <div>
    <span class="sig">Energy modeller: {Html.esc(options.get('prepared_by') or '')}&nbsp;<br>Signature / date</span>
    <span class="sig">Registered professional of record: {Html.esc(options.get('professional_of_record') or '')}&nbsp;<br>Signature / seal / date</span>
  </div>
  <footer>Generated by the btap family (btap-necb, -modeling, -costing, -simulation, -audit).
  Single-file report: no external resources, scripts or network requests. Audit entries are the
  normative record; this report is a rendering of them.</footer>
</section>
"""


# -- shared --------------------------------------------------------------

def space_type_table(ctx, key, heading):
    types = _dig(ctx.get("proposed") or {}, "space_types")
    if not types:
        return "<p>No space types with floor area in the proposed model.</p>"

    ref_types = {t["name"]: t
                 for t in _dig(ctx.get("reference") or {}, "space_types") or []}
    rows = []
    for t in types:
        ref = ref_types.get(t["name"])
        rows.append([t["name"], Html.fmt(t["area_m2"], unit="m²"),
                     Html.fmt(t[key], prec=2),
                     Html.fmt(ref[key], prec=2) if ref else "—"])
    return (f"<h3>{Html.esc(heading)}</h3>"
            + Html.table(["Space type", "Floor area", "Proposed", "Reference"],
                         rows))


def domain_audit_notes(ctx, domain):
    """Per-domain audit table: decisions + warnings whose step matches the
    domain."""
    steps = DOMAIN_STEPS[domain]
    picked = [(e, i) for i, e in enumerate(ctx["audit_entries"])
              if any(s in str(e.get("step") or "") for s in steps)
              and e.get("level") in ("decision", "warning")]
    if not picked:
        return ""

    rows = []
    for e, i in picked[:60]:
        target = e.get("target")
        prefix = f"{target}: " if target is not None else ""
        rows.append([
            Html.raw(Html.glyph("warning" if e.get("level") == "warning"
                                else "info")),
            Html.raw(Html.building_chip(e.get("building"))),
            str(e.get("article") or ""),
            f"{prefix}{e.get('action')}",
            Html.raw(f'<a href="#audit-{i}">#{i}</a>')])
    note = (f'<p class="meta">Showing 60 of {len(picked)} — see the full audit '
            "trail.</p>" if len(picked) > 60 else "")
    return Html.details(
        f"Audited decisions for this domain ({len(picked)})",
        Html.table(["", "Applies to", "Article", "Decision", "Audit"], rows) + note)
