#!/usr/bin/env python3
"""Regenerate the id-ordered TOC region in the hand-authored decision log."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_DOC = REPO_ROOT / "btap-necb" / "docs" / "necb_decisions.md"
DEFAULT_REGISTRY = REPO_ROOT / "python" / "btap" / "necb" / "data" / "decisions.json"
BEGIN_MARK = "<!-- TOC BEGIN (generated by scripts/generate_decisions_toc.rb — do not hand-edit) -->"
END_MARK = "<!-- TOC END -->"


def toc_block(registry: Path) -> str:
    decisions = json.loads(registry.read_text(encoding="utf-8"))["decisions"]
    decisions.sort(key=lambda item: int(re.search(r"\d+", item["id"]).group()))
    lines = [f"- **{item['id']}** — {item['title']} _({item['kind']})_"
             for item in decisions]
    return "\n".join([
        BEGIN_MARK, "", "## Index (id order; entries below are chronological)",
        "", *lines, "", END_MARK,
    ])


def render(doc: str, registry: Path) -> str:
    fresh = toc_block(registry)
    pattern = re.compile(re.escape(BEGIN_MARK) + r".*?" + re.escape(END_MARK), re.DOTALL)
    if pattern.search(doc):
        return pattern.sub(lambda _match: fresh, doc, count=1)
    heading = re.search(r"^## ", doc, re.MULTILINE)
    if heading is None:
        raise ValueError("no ## heading found to anchor the TOC")
    return doc[:heading.start()] + fresh + "\n\n" + doc[heading.start():]


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--doc", type=Path, default=DEFAULT_DOC)
    parser.add_argument("--registry", type=Path, default=DEFAULT_REGISTRY)
    args = parser.parse_args(argv)
    current = args.doc.read_text(encoding="utf-8")
    fresh = render(current, args.registry)
    if args.check:
        if fresh == current:
            print("decisions TOC: up to date")
            return 0
        print("decisions TOC: STALE - run python3 python/scripts/generate_decisions_toc.py")
        return 1
    args.doc.write_text(fresh, encoding="utf-8")
    print("decisions TOC: rewritten in place")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())