#!/usr/bin/env python3
"""Generate the decision registry and the authored decision log from the
per-decision sources in ``docs/decisions/``.

The sources are canonical (D-81). Each ``docs/decisions/D-NN.md`` carries TOML
front matter -- the registry fields -- followed by the authored Markdown body,
whose first line is the section's own ``## D-NN -- <heading>``. Two outputs are
generated from them and are never hand-edited:

* ``python/btap/codes/data/decisions.json`` -- the runtime registry projection;
* ``docs/necb_decisions.md`` -- the authored log, with its short anchors and
  its index inserted mechanically.

Both outputs are emitted in numeric decision-id order. That is the only
ordering invariant a generator can hold: a decision has an initial ruling,
later amendments, and occasionally an id reserved while another decision lands,
so the order entries were authored in is not durable and is not claimed.

``--check`` regenerates into memory and fails when either output has drifted.
``--split`` is the one-time migration that built the sources from the two files
that used to be maintained by hand. It is kept so the migration stays
reproducible and fails closed once the sources exist.
"""

from __future__ import annotations

import argparse
import json
import pathlib
import re
import sys
import tomllib
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
SOURCE_DIR = REPO_ROOT / "docs" / "decisions"
DOC = REPO_ROOT / "docs" / "necb_decisions.md"
REGISTRY = REPO_ROOT / "python" / "btap" / "codes" / "data" / "decisions.json"

PREAMBLE_FILE = "_preamble.md"
META_FILE = "_meta.json"
FENCE = "+++"

EM_DASH = "—"
BEGIN_MARK = ("<!-- TOC BEGIN (generated by scripts/generate_decisions.py "
              + EM_DASH + " do not hand-edit) -->")
END_MARK = "<!-- TOC END -->"
INDEX_HEADING = "## Index (id order)"
#: The marker the pre-migration document carried. Only ``--split`` looks for
#: it, so the preamble can be cut out of the file being retired.
LEGACY_BEGIN_MARK = ("<!-- TOC BEGIN (generated by scripts/"
                     "generate_decisions_toc.rb " + EM_DASH + " do not hand-edit) -->")

#: The registry fields, in the order the generated JSON emits them.
FIELDS = ("id", "title", "kind", "articles", "editions", "summary")

#: Every value an ``editions`` entry may take: a registered code id, or the
#: literal ``unverified``. phylroy asked for the affected code to be explicit
#: (2026-10-07): an authority has to know WHICH code their project is under,
#: and a collective word like "both" stops meaning anything the moment a third
#: edition is registered. The code id is this repository's one public
#: selector, so it is what the field carries. ``vintage`` is retired
#: vocabulary and is not accepted.
#:
#: ``unverified`` is the honest value for the 98 decisions written before this
#: field existed: most were authored against one edition's text and nobody has
#: checked them against the other, so asserting a list would be a guess. It is
#: a declared gap rather than a silent one.
EDITIONS_UNVERIFIED = "unverified"
#: A decision whose conclusion adopts NO operative Code proposition whose
#: numbering, content or result can vary by edition — licensing, delegation,
#: repository governance, the review loop. It is a CATEGORY statement, not a
#: verification state: `unverified` would say "not yet checked" where the
#: truth is "the edition axis does not apply" (Sol, `169`). A decision does
#: NOT qualify merely because its holding list is empty or its subject is
#: tooling, so the classification is authored per decision and never derived
#: from `kind`.
EDITIONS_NOT_APPLICABLE = "not_applicable"
KINDS = ("runtime", "runtime_unwired", "data", "process")
#: The only keys _meta.json may carry.
META_FIELDS = ("registry_comment",)

#: Unbounded digits. `^D-\d{2}$` allowed exactly 100 ids and D-01..D-99 all
#: exist, so the registry had no id left for a new decision. Widening to a
#: fixed three digits would only move the wall, and phylroy expects thousands
#: once other code families arrive. Existing ids are NOT renumbered: every
#: citation in product source, audit entries and frozen baselines keeps
#: working, and the index already sorts numerically rather than lexically.
ID_RE = re.compile(r"^D-\d+$")
#: A body's first line. The heading text is authored prose and is deliberately
#: NOT required to equal the front-matter ``title``, which is the compact
#: runtime/index title; the two differ for most decisions on purpose.
HEADING_RE = re.compile("^## (D-\\d+) " + EM_DASH + " (.+)$")
#: The laxer form the pre-migration document used, where D-76..D-89 carried no
#: heading title at all. Only ``--split`` accepts it.
SPLIT_HEADING_RE = re.compile("^## (D-\\d+)(?: " + EM_DASH + " (.+))?$")
#: Unbounded, like `ID_RE`. Two digits here made the generator emit an
#: anchor it could not then RECOGNISE on the round trip, so a real D-100
#: turned the sync gate red while the generator itself reported success
#: (Sol, `124`.6).
ANCHOR_RE = re.compile(r'^<a id="d-\d+"></a>$')

def numeric_order(ids) -> list:
    """Decision ids in numeric id order -- the one ordering invariant."""
    return sorted(ids, key=lambda item: int(item.split("-")[1]))


# --------------------------------------------------------------------------
# TOML writing
#
# Only what the source schema allows is serialized: a string, or an array of
# strings. Every value goes through one escaper, so a quote, a backslash or a
# control character in authored text cannot terminate the string or smuggle in
# TOML syntax. Nothing is interpolated raw.
# --------------------------------------------------------------------------

_ESCAPES = {
    "\\": "\\\\",
    '"': '\\"',
    "\x08": "\\b",
    "\x0c": "\\f",
    "\n": "\\n",
    "\r": "\\r",
    "\t": "\\t",
}


def toml_string(value) -> str:
    """``value`` as a TOML basic string, escaped so it cannot break out."""
    if not isinstance(value, str):
        raise TypeError("not a string: {!r}".format(value))
    out = ['"']
    for char in value:
        if char in _ESCAPES:
            out.append(_ESCAPES[char])
        elif char < "\x20" or char == "\x7f":
            out.append("\\u{:04x}".format(ord(char)))
        else:
            out.append(char)
    out.append('"')
    return "".join(out)


def toml_value(value) -> str:
    if isinstance(value, str):
        return toml_string(value)
    if isinstance(value, list):
        return "[" + ", ".join(toml_string(item) for item in value) + "]"
    raise TypeError("unsupported TOML value: {!r}".format(value))


#: The holding key for a decision whose editions are not yet established. Its
#: articles are carried unvalidated, because validating them requires knowing
#: which edition's numbering they are written in.
ARTICLES_UNVERIFIED = "unverified"
#: The articles counterpart of ``EDITIONS_NOT_APPLICABLE``. Its list must be
#: EMPTY: a decision that cites an article has a Code proposition to check.
ARTICLES_NOT_APPLICABLE = "not_applicable"


def _bare_article(value: str):
    """The bare article number inside a citation: ``8.4.4.9.(5)`` ->
    ``8.4.4.9``, ``Table 8.4.4.7.-A`` -> ``8.4.4.7``, ``A-8.4.5.4.(1)`` ->
    ``8.4.5.4``. ``None`` when the string carries no number at all."""
    text = re.sub(r"^(Table|Note|Appendix)\s+", "", str(value).strip())
    text = re.sub(r"^A-", "", text)
    match = re.match(r"(\d+(?:\.\d+)*)", text)
    return match.group(1) if match else None


#: Articles cited correctly whose retained payload carries no title. Not an
#: error: the codes service itself returns an empty title for NECB 2025's
#: 8.4.6.7 while serving its full text (D-102).
_untitled_articles: set = set()


def _article_titles(code: str) -> dict:
    """Section 8.4 article number -> title, for one code id, read from that
    edition's own coverage cache with STDLIB ONLY.

    It does NOT import `btap`: `.github/workflows/decisions.yml` runs this
    generator with no dependency install, so an import would make the gate
    fail in CI rather than check anything. The first version of this function
    did import it, got an ImportError, and returned `{}` — which made every
    per-edition check silently pass. A check that cannot fail is worse than no
    check, so a MISSING cache now raises.
    """
    return {number: str(record.get("title") or "").strip().lower()
            for number, record in _article_cache(code).items()
            if record.get("title")}


def _article_cache(code: str) -> dict:
    """One edition's Section 8.4 article records, number -> record."""
    path = (pathlib.Path(__file__).resolve().parents[1] / "btap" / "codes"
            / "necb" / "data" / code / "coverage" / "articles_8_4.json")
    if not path.is_file():
        raise ValueError(
            "cannot validate articles for {!r}: {} is missing, so the "
            "per-edition check would silently pass".format(code, path))
    records = json.loads(path.read_text(encoding="utf-8"))["articles"]
    return {k: v for k, v in records.items() if isinstance(v, dict)}


#: Citation prefixes the Code itself uses. `Article 8.4.4.9.(5)` and
#: `8.4.4.9.(5)` are the same citation, and a validator that normalises one but
#: not the other both ADMITS `Article 8.4.999.1.(5)`, whose prefix hid it from
#: the existence check, and REFUSES a correct `Article 8.4.4.9.(5)` whose
#: unnormalised string simply differed from its counterpart (Sol, `124`.4).
CITATION_PREFIX_RE = re.compile(
    r"^\s*(?:Articles?|Tables?|Notes?|Sentences?|Clauses?|Appendix|A-)\s*", re.I)

#: A leading sentence marker inside an article's text: `1)`, `2)`, ...
SENTENCE_RE = re.compile(r"^\s*(\d+)\)", re.M)


def normalise_citation(value: str) -> str:
    """Strip a supported prefix and collapse whitespace. Returns '' for blank."""
    return CITATION_PREFIX_RE.sub("", str(value)).strip()


#: `8.4.4.9.(5)(a)` -> ('8.4.4.9', 5, 'a', None). FULLMATCH, not a prefix
#: match: a prefix match ignored `8.4.4.9.(5) THIS IS TRAILING JUNK` and
#: downgraded `junk before 8.4.4.9.(5)` to unchecked scope, so arbitrary text
#: rode along beside a real citation (Sol, `125`.3).
CITATION_PARTS_RE = re.compile(
    r"(?P<bare>\d+(?:\.\d+)*)\.?"
    r"(?:\((?P<sentence>\d+)\))?"
    r"(?:\((?P<clause>[a-z]+)\))?"
    r"(?:\((?P<subclause>[ivx]+)\))?")

#: A table citation: `Table 8.4.4.7.-B` -> ('8.4.4.7', 'B').
TABLE_PARTS_RE = re.compile(
    r"(?P<bare>\d+(?:\.\d+)*)\.?-(?P<suffix>[A-Z])")

def _article_record(code: str, bare: str) -> dict:
    cache = _article_cache(code)
    entry = cache.get(bare) or cache.get(bare + ".")
    return entry if isinstance(entry, dict) else {}


def _article_sentence_map(code: str, bare: str) -> dict:
    """``{sentence number: {clause letters}}`` from the snapshot's STRUCTURED
    `sentences` field, not a regex over `raw`.

    Scoping matters: clause letters anywhere in 8.4.x.9's text run a..i,
    because Sentence (6) has nine clauses. Taken unscoped, `(5)(f)` would pass
    while the Code gives Sentence (5) only clauses (a) and (b).
    """
    found = {}
    for sentence in (_article_record(code, bare).get("sentences") or ()):
        if not isinstance(sentence, dict):
            continue
        try:
            number = int(sentence.get("num"))
        except (TypeError, ValueError):
            continue
        letters = set()
        for clause in (sentence.get("clauses") or ()):
            letter = (clause.get("id") or clause.get("letter")
                      if isinstance(clause, dict) else clause)
            if isinstance(letter, str) and letter.strip():
                letters.add(letter.strip().lower())
        found[number] = letters
    return found


def _article_tables(code: str, bare: str) -> set:
    """Table suffixes the snapshot shows for an article, e.g. ``{'A', 'B'}``.

    Empty when the snapshot names none, and the caller must then NOT treat the
    absence as evidence.
    """
    record = _article_record(code, bare)
    found = set()
    for key in ("tables", "table_ids", "tables_referenced"):
        for value in (record.get(key) or ()):
            match = TABLE_PARTS_RE.search(str(value))
            if match:
                found.add(match.group("suffix"))
    haystack = str(record.get("raw") or "") + " ".join(
        str(s.get("text") or "") for s in (record.get("sentences") or ())
        if isinstance(s, dict))
    for match in TABLE_PARTS_RE.finditer(haystack):
        if match.group("bare") == bare:
            found.add(match.group("suffix"))
    return found


def check_articles(name: str, meta: dict) -> None:
    """``articles`` groups citations by an AUTHORED requirement identity, then
    by code id inside it.

    A flat list was ambiguous and wrong: ``8.4.5.9`` is the Heating System
    article in NECB 2025 and the Fuel-Fired Service Water Heater article in
    NECB 2020, so one list spanning editions cites a different requirement in
    each.

    Per-edition nesting alone was NECESSARY BUT INSUFFICIENT (Sol, clearance
    review of be2118d). Its cross-edition check inferred correspondence from
    shared title vocabulary, and three mutations slipped through: claiming an
    edition with no article map for it, adding an unrelated extra article, and
    replacing "Heating System" with "Service Water Heating Systems", which
    passed because both titles contain "heating". Semantic matching on
    vocabulary cannot be made safe.

    So correspondence is AUTHORED, not inferred. Each requirement key names one
    requirement and lists its own article ids per edition; that grouping IS the
    cross-edition equivalence assertion, and the validator checks structure
    rather than guessing meaning::

        [requirements.multi_energy_heating]
        label = "Multi-energy heating capacity allocation"
        necb2020 = ["8.4.4.9.(4)", "8.4.4.9.(5)"]
        necb2025 = ["8.4.5.9.(4)", "8.4.5.9.(5)"]
    """
    articles = meta["articles"]
    if not isinstance(articles, dict) or not articles:
        raise ValueError(
            "{}: articles must be a non-empty map of requirement key -> "
            "{{label, <code id>: [...]}} (a flat list cannot say which "
            "edition's numbering it uses)".format(name))

    codes = registered_codes()
    claimed = set(meta["editions"])

    # RULE 0. `not_applicable` pairs with an EMPTY articles list, in both
    # directions. A decision that cites an article has a Code proposition
    # whose numbering or content can move between editions, which is exactly
    # what this sentinel denies (Sol, `169`).
    not_applicable_articles = ARTICLES_NOT_APPLICABLE in articles
    not_applicable_editions = claimed == {EDITIONS_NOT_APPLICABLE}
    if not_applicable_articles and len(articles) > 1:
        raise ValueError(
            "{}: articles may not mix the {!r} key with anything else".format(
                name, ARTICLES_NOT_APPLICABLE))
    if not_applicable_articles != not_applicable_editions:
        raise ValueError(
            "{}: articles[{!r}] and editions == [{!r}] go together or not at "
            "all — articles={}, editions={}".format(
                name, ARTICLES_NOT_APPLICABLE, EDITIONS_NOT_APPLICABLE,
                not_applicable_articles, sorted(claimed)))
    if not_applicable_articles:
        block = articles[ARTICLES_NOT_APPLICABLE]
        if block != []:
            raise ValueError(
                "{}: articles[{!r}] must be EMPTY — a cited article is a Code "
                "proposition to establish, not an inapplicable axis; got "
                "{!r}".format(name, ARTICLES_NOT_APPLICABLE, block))
        return

    # RULE 1. The holding pen and established editions are mutually exclusive
    # in BOTH directions. Checking only one let a decision claim necb2020 and
    # necb2025 while carrying nothing but `unverified = []` (Sol, `124`.4).
    holding = ARTICLES_UNVERIFIED in articles
    unverified_editions = claimed == {EDITIONS_UNVERIFIED}
    if holding and len(articles) > 1:
        raise ValueError(
            "{}: articles may not mix the {!r} holding key with authored "
            "requirements".format(name, ARTICLES_UNVERIFIED))
    if holding != unverified_editions:
        raise ValueError(
            "{}: articles[{!r}] and editions == [{!r}] go together or not at "
            "all — articles holding={}, editions={}".format(
                name, ARTICLES_UNVERIFIED, EDITIONS_UNVERIFIED,
                holding, sorted(claimed)))
    if holding:
        block = articles[ARTICLES_UNVERIFIED]
        if not isinstance(block, list) or not all(
                isinstance(i, str) for i in block):
            raise ValueError(
                "{}: articles[{!r}] must be a list of strings".format(
                    name, ARTICLES_UNVERIFIED))
        for value in block:
            if not normalise_citation(value):
                raise ValueError(
                    "{}: articles[{!r}] has a blank citation".format(
                        name, ARTICLES_UNVERIFIED))
        return

    for key, block in sorted(articles.items()):
        if not str(key).strip():
            raise ValueError(
                "{}: articles has a blank requirement key — the key and its "
                "label ARE the cross-edition equivalence assertion, so an "
                "empty one asserts nothing".format(name))
        if not isinstance(block, dict):
            raise ValueError(
                "{}: articles[{!r}] must be a table with a label and one list "
                "per code id".format(name, key))
        if not str(block.get("label") or "").strip():
            raise ValueError(
                "{}: articles[{!r}] needs a non-empty label naming the "
                "requirement — the label IS the cross-edition equivalence "
                "assertion".format(name, key))
        listed = {k: v for k, v in block.items() if k != "label"}
        if ARTICLES_UNVERIFIED in listed:
            raise ValueError(
                "{}: articles[{!r}] may not carry the {!r} key inside an "
                "authored requirement".format(
                    name, key, ARTICLES_UNVERIFIED))
        if not listed:
            raise ValueError(
                "{}: articles[{!r}] lists no editions".format(name, key))

        missing = claimed - set(listed)
        if missing:
            raise ValueError(
                "{}: articles[{!r}] lists no article for {}, which editions "
                "claims — a requirement that does not apply in an edition "
                "must not be grouped with one that does".format(
                    name, key, sorted(missing)))
        extra = set(listed) - claimed
        if extra:
            raise ValueError(
                "{}: articles[{!r}] lists {} which editions does not "
                "claim".format(name, key, sorted(extra)))

        scopes = {}
        for code, values in sorted(listed.items()):
            if code not in codes:
                raise ValueError(
                    "{}: articles[{!r}] has key {!r}, which is not a "
                    "registered code id; registered are {}".format(
                        name, key, code, sorted(codes)))
            if not isinstance(values, list) or not values or not all(
                    isinstance(i, str) for i in values):
                raise ValueError(
                    "{}: articles[{!r}][{!r}] must be a non-empty list of "
                    "strings".format(name, key, code))

            # RULE 2. Non-blank and unique WITHIN the edition list. A blank
            # string and a repeated sentence both passed before: one cites
            # nothing, the other counts one piece of evidence twice.
            seen = set()
            energy_section = set()
            for value in values:
                citation = normalise_citation(value)
                if not citation:
                    raise ValueError(
                        "{}: articles[{!r}][{!r}] has a blank citation "
                        "{!r}".format(name, key, code, value))
                if citation in seen:
                    raise ValueError(
                        "{}: articles[{!r}][{!r}] cites {!r} twice".format(
                            name, key, code, citation))
                seen.add(citation)

                # RULE 3/4. Normalise the prefix, then validate the WHOLE
                # citation with a FULLMATCH. A prefix match let
                # `8.4.4.9.(5) THIS IS TRAILING JUNK` through and downgraded
                # `junk before 8.4.4.9.(5)` to unchecked scope (Sol, `125`.3).
                table = TABLE_PARTS_RE.fullmatch(citation)
                parts = CITATION_PARTS_RE.fullmatch(citation)
                if table is None and parts is None:
                    raise ValueError(
                        "{}: articles[{!r}][{!r}] cites {!r}, which is not a "
                        "citation — expected an article like 8.4.4.9.(5)(a) "
                        "or a table like 8.4.4.7.-B, with nothing before or "
                        "after it".format(name, key, code, value))
                bare = (table or parts).group("bare")
                if not bare.startswith("8.4"):
                    energy_section.add(False)
                    continue
                energy_section.add(True)
                # EXISTENCE is record presence, not TITLE presence. Using
                # `_article_titles` here conflated two different conditions and
                # refused a correct citation: NECB 2025's 8.4.6.7 is the
                # air-source heat-pump article, with seven cached sentences and
                # `parse_ok`, but the codes service returns an EMPTY TITLE for
                # it — so a title-keyed check reported "does not exist" for an
                # article that plainly does (D-102).
                if not _article_record(code, bare):
                    raise ValueError(
                        "{}: articles[{!r}][{!r}] cites {!r}, and Section 8.4 "
                        "article {} does not exist in that edition".format(
                            name, key, code, value, bare))
                if not _article_titles(code).get(bare):
                    # Not a failure. A missing title is an upstream gap in the
                    # retained payload, and saying so is more useful than
                    # either refusing the citation or staying silent.
                    _untitled_articles.add((code, bare))

                if table is not None:
                    suffixes = _article_tables(code, bare)
                    if suffixes and table.group("suffix") not in suffixes:
                        raise ValueError(
                            "{}: articles[{!r}][{!r}] cites {!r}, and article "
                            "{} has tables {} in that edition".format(
                                name, key, code, value, bare,
                                sorted(suffixes)))
                    continue

                sentence = parts.group("sentence")
                if sentence is None:
                    continue
                sentences = _article_sentence_map(code, bare)
                if sentences and int(sentence) not in sentences:
                    raise ValueError(
                        "{}: articles[{!r}][{!r}] cites {!r}, and article {} "
                        "has sentences {} in that edition".format(
                            name, key, code, value, bare,
                            sorted(sentences)))
                clause = parts.group("clause")
                if clause is None:
                    continue
                # Scoped to the SENTENCE. 8.4.x.9's clause letters run a..i
                # across the article because (6) has nine, so an unscoped
                # check would admit `(5)(f)` where the Code gives (5) only
                # clauses (a) and (b).
                letters = sentences.get(int(sentence)) or set()
                if letters and clause.lower() not in letters:
                    raise ValueError(
                        "{}: articles[{!r}][{!r}] cites {!r}, and sentence "
                        "({}) of article {} has clauses {} in that "
                        "edition".format(name, key, code, value, sentence,
                                         bare, sorted(letters)))
            scopes[code] = energy_section

        # RULE 6. One requirement, one validation scope — WITHIN each edition
        # and across them. Comparing only across editions let every edition
        # carry the same mixed set `{8.4, other}` and pass (Sol, `125`.3).
        for code, scope in sorted(scopes.items()):
            if len(scope) > 1:
                raise ValueError(
                    "{}: articles[{!r}][{!r}] mixes validated Section 8.4 "
                    "citations with citations this generator cannot check — a "
                    "requirement must be verifiable in every edition it "
                    "claims or in none".format(name, key, code))
        if len({frozenset(v) for v in scopes.values()}) > 1:
            raise ValueError(
                "{}: articles[{!r}] mixes validated Section 8.4 citations "
                "with citations this generator cannot check, across "
                "editions: {} — a requirement must be verifiable in every "
                "edition it claims or in none".format(
                    name, key,
                    {c: ("8.4" if True in s else "other")
                     for c, s in sorted(scopes.items())}))

    # RULE 5 is a NON-rule, and deliberately so. Equal citation counts and
    # equal sentence suffixes across editions are NOT required. The suffix
    # rule I had was wrong in both directions (Sol, `124`.5): it admitted
    # unrelated articles that happened to share suffixes, and it REFUSED a
    # real migration — D-89's modulating-boiler part-load requirement is
    # 8.4.5.2.(3) in NECB 2020 and 8.4.6.2.(2) in NECB 2025, because the 2020
    # article has three sentences and the 2025 article has two. Correspondence
    # is the authored key and label; numbering cannot carry it.


def registered_codes() -> set:
    """The code ids that actually exist, DISCOVERED from the edition snapshots
    rather than listed, so registering a new edition does not leave this
    validation stale."""
    root = (pathlib.Path(__file__).resolve().parents[1]
            / "btap" / "codes" / "necb" / "data")
    return {p.parent.name for p in root.glob("*/manifest.json")}


def front_matter(meta: dict) -> str:
    # Emitting only the known fields would silently discard a typo'd or
    # newly-added one on any rewrite, so an unexpected key is refused here as
    # well as on the way in.
    extra = sorted(set(meta) - set(FIELDS))
    missing = sorted(set(FIELDS) - set(meta))
    if extra or missing:
        raise ValueError(
            "front matter: unexpected {} / missing {}".format(extra, missing))
    lines = [FENCE]
    for field in FIELDS:
        if field == "articles":
            continue            # emitted as a table, after the scalars
        lines.append("{} = {}".format(field, toml_value(meta[field])))
    # `articles` becomes TOML tables, after every scalar: a table header
    # captures each key that follows it. The shape is checked here too —
    # emitting a flat list raised AttributeError deep in the writer instead of
    # saying what was wrong.
    if not isinstance(meta["articles"], dict):
        raise ValueError(
            "front matter: articles must be a map of requirement key -> "
            "table, got {}".format(type(meta["articles"]).__name__))
    for key, block in sorted(meta["articles"].items()):
        lines.append("")
        if key in (ARTICLES_UNVERIFIED, ARTICLES_NOT_APPLICABLE):
            lines.append("[articles]")
            lines.append("{} = {}".format(key, toml_value(block)))
            continue
        lines.append("[articles.{}]".format(key))
        lines.append("label = {}".format(toml_string(block["label"])))
        for code, values in sorted(
                (k, v) for k, v in block.items() if k != "label"):
            lines.append("{} = {}".format(code, toml_value(values)))
    lines.append(FENCE)
    return "\n".join(lines)


def source_text(meta: dict, body: str) -> str:
    """The complete ``D-NN.md`` source file."""
    return "{}\n\n{}".format(front_matter(meta), body)


# --------------------------------------------------------------------------
# Reading the sources
# --------------------------------------------------------------------------

def parse_source(path: Path):
    text = path.read_text(encoding="utf-8")
    if not text.startswith(FENCE + "\n"):
        raise ValueError("{}: no opening {} fence".format(path.name, FENCE))
    end = text.find("\n" + FENCE + "\n", len(FENCE))
    if end < 0:
        raise ValueError("{}: no closing {} fence".format(path.name, FENCE))
    raw = text[len(FENCE) + 1:end + 1]
    close = end + 1 + len(FENCE)          # just past the closing fence
    if text[close:close + 2] != "\n\n":
        raise ValueError(
            "{}: closing {} fence must be followed by one blank line".format(
                path.name, FENCE))
    body = text[close + 2:]
    meta = tomllib.loads(raw)
    validate(path.name, meta, body)
    return meta, body


def validate(name: str, meta: dict, body: str) -> None:
    extra = sorted(set(meta) - set(FIELDS))
    missing = sorted(set(FIELDS) - set(meta))
    if extra or missing:
        raise ValueError("{}: unexpected {} / missing {}".format(name, extra, missing))
    if not ID_RE.match(meta["id"]):
        raise ValueError("{}: malformed id {!r}".format(name, meta["id"]))
    if name != meta["id"] + ".md":
        raise ValueError("{}: filename does not match id {!r}".format(name, meta["id"]))
    if meta["kind"] not in KINDS:
        raise ValueError("{}: unknown kind {!r}".format(name, meta["kind"]))
    if not isinstance(meta["editions"], list) or not meta["editions"] or not all(
            isinstance(item, str) for item in meta["editions"]):
        raise ValueError(
            "{}: editions must be a non-empty list of strings".format(name))
    # Checked BEFORE `check_articles`, which reduces editions to a set and so
    # erased a duplicate silently (Sol, `125`.3).
    duplicates = sorted({item for item in meta["editions"]
                         if meta["editions"].count(item) > 1})
    if duplicates:
        raise ValueError(
            "{}: editions lists {} more than once".format(name, duplicates))
    allowed = (registered_codes() | {EDITIONS_UNVERIFIED,
                                       EDITIONS_NOT_APPLICABLE})
    unknown = sorted(set(meta["editions"]) - allowed)
    if unknown:
        raise ValueError(
            "{}: editions lists {} which are neither a registered code id nor "
            "{!r} nor {!r}; registered are {}".format(
                name, unknown, EDITIONS_UNVERIFIED, EDITIONS_NOT_APPLICABLE,
                sorted(registered_codes())))
    if EDITIONS_NOT_APPLICABLE in meta["editions"] and len(meta["editions"]) > 1:
        raise ValueError(
            "{}: editions may not mix {!r} with anything else — the edition "
            "axis either applies to this decision or it does not".format(
                name, EDITIONS_NOT_APPLICABLE))
    if (EDITIONS_NOT_APPLICABLE in meta["editions"]
            and meta["kind"] != "process"):
        raise ValueError(
            "{}: only a kind='process' decision may be {!r}; this one is "
            "kind={!r}, so it has a Code proposition to establish".format(
                name, EDITIONS_NOT_APPLICABLE, meta["kind"]))
    if EDITIONS_UNVERIFIED in meta["editions"] and len(meta["editions"]) > 1:
        raise ValueError(
            "{}: editions may not mix {!r} with a code id — either it has been "
            "checked or it has not".format(name, EDITIONS_UNVERIFIED))
    check_articles(name, meta)
    for field in ("title", "summary"):
        if not isinstance(meta[field], str) or not meta[field].strip():
            raise ValueError("{}: {} must be a non-empty string".format(name, field))

    lines = body.split("\n")
    heading = HEADING_RE.match(lines[0])
    if heading is None:
        raise ValueError(
            "{}: body must open with '## {} {} <heading>', got {!r}".format(
                name, meta["id"], EM_DASH, lines[0]))
    if heading.group(1) != meta["id"]:
        raise ValueError("{}: heading declares {}, front matter {}".format(
            name, heading.group(1), meta["id"]))
    if not body.endswith("\n") or body.endswith("\n\n"):
        raise ValueError("{}: body must end with exactly one newline".format(name))


#: Only a Markdown suffix can be a lost decision. This is what tolerates editor
#: and OS debris without a blanket dotfile rule: `.D-01.md.swp` exists while a
#: vim buffer is OPEN, and failing on it would stop a developer running the
#: repository's own drift gate until they closed the editor (Fable, PR #64) —
#: but exempting every dotfile then hid `.D-98.md` (Sol, PR #64).
SOURCE_SUFFIXES = frozenset({".md", ".markdown"})
#: A filename that looks like a decision whatever its extension.
DECISION_SHAPED_NAME_RE = re.compile(r"^d[-_ ]?\d", re.IGNORECASE)


def stray_files(source_dir: Path = SOURCE_DIR):
    """Entries in the canonical directory that reach NEITHER generated output.

    A decision whose filename the `D-*.md` glob misses — `d-98.md`, `D-98.MD`,
    `D98.md`, `D-98.markdown`, `sub/D-98.md` — is invisible to both outputs
    while `--check` reports up to date, so a whole decision can go missing with
    a green gate (Fable, PR #64).

    Exposed as a helper deliberately. The first fix computed this inline and the
    test recomputed it from a byte-for-byte copy of the expression, so deleting
    the production guard left the suite green — the fourth instance in this
    repository of a test agreeing with its own reimplementation. One
    implementation, two callers.

    Narrow by design: only `.md`/`.markdown` entries count, and dotfiles and
    editor backups never do. A `.DS_Store` is not a lost decision, and saying it
    "would be silently omitted from both generated outputs" was false.
    """
    keep = {PREAMBLE_FILE, META_FILE} | {
        path.name for path in source_dir.glob("D-*.md")}
    found = []
    for path in sorted(source_dir.rglob("*")):
        relative = path.relative_to(source_dir).as_posix()
        # Emacs's lock file is tested FIRST, before the symlink arm, because it
        # IS a symlink: `.#D-01.md -> user@host.1234:1700000000`, present only
        # while a buffer has unsaved changes. Checking it after the symlink arm
        # left the gate hard-failing for anyone mid-edit in emacs -- exactly
        # what G4 decided against for vim's `.swp` (Fable, PR #64). Safe at this
        # position: a `.#`-prefixed name can never be a canonical source, since
        # sources are `D-NN.md`, so the link is skipped and never followed.
        # ...and ONLY when the remainder names a source the glob already
        # reached. A bare `.#` prefix was too broad both ways Fable predicted: a
        # complete decision in `.#D-98.md` was silently lost, and `.#extra ->`
        # a directory of sources escaped the symlink arm entirely, because this
        # test precedes it. Emacs names its lock `.#<the file being edited>`, so
        # the remainder is always a real source and this costs the real case
        # nothing (Fable, PR #64).
        if path.name.startswith(".#") and path.name[2:] in keep:
            continue
        # is_symlink() is tested BEFORE the keep-set exemption. Checking keep
        # first accepted a symlink NAMED `D-98.md`, and symlinked `_preamble.md`
        # and `_meta.json` with it: the name was exempted and the link followed
        # to its target (Sol, PR #64). A canonical input must be a real file.
        if path.is_symlink():
            found.append(f"{relative} (symlink)")
            continue
        if relative in keep:
            continue
        if not path.is_file():
            continue
        # Bounded debris shapes only. A blanket "starts with a dot" exemption
        # hid `.D-98.md` — a decision-shaped Markdown source — and none of the
        # debris needs it: `.D-01.md.swp` is excluded by its `.swp` suffix,
        # `.DS_Store` and `.gitkeep` carry no Markdown suffix at all, and
        # `D-01.md~` ends with a tilde (Sol, PR #64).
        if path.name.endswith("~"):
            continue
        # Either a Markdown suffix OR a decision-shaped name. Suffix alone
        # silently ignored `D-98` with no extension, `D-98.txt`, `D-98.md.bak`
        # and — the one that will actually happen — `D-98.md ` with a trailing
        # space, which survives copy-paste and is visually identical to a correct
        # filename (Fable, PR #64).
        if (path.suffix.lower() not in SOURCE_SUFFIXES
                and not DECISION_SHAPED_NAME_RE.match(path.name)):
            continue
        found.append(relative)
    return sorted(found)


def read_sources(source_dir: Path = SOURCE_DIR):
    meta = json.loads((source_dir / META_FILE).read_text(encoding="utf-8"))
    # Front matter refuses an unexpected key; this refused nothing, so an edit
    # here could silently take no effect (Fable, PR #64).
    # A leading underscore is the conventional "annotation, not data" marker —
    # `decisions.json` itself uses `_comment` for exactly that two directories
    # away — so refusing it repeated the mistake of refusing a `.DS_Store`
    # (Fable, PR #64).
    extra = sorted(key for key in set(meta) - set(META_FIELDS)
                   if not key.startswith("_"))
    missing = sorted(set(META_FIELDS) - set(meta))
    if extra or missing:
        raise ValueError("{}: unexpected {} / missing {} (keys beginning with "
                         "'_' are annotations and are ignored)".format(
                             META_FILE, extra, missing))
    # Every front-matter field is type-checked; this one was not, so a plain
    # string passed validation and shipped a `str` where every reader of
    # decisions.json's `_comment` expects a list (Fable, PR #64).
    comment = meta["registry_comment"]
    if not isinstance(comment, list) or not all(
            isinstance(line, str) for line in comment):
        raise ValueError(
            "{}: registry_comment must be a list of strings, got {}".format(
                META_FILE, type(comment).__name__))
    preamble = (source_dir / PREAMBLE_FILE).read_text(encoding="utf-8")
    entries = {}
    sources = sorted(source_dir.glob("D-*.md"))
    for path in sources:
        fields, body = parse_source(path)
        entries[fields["id"]] = (fields, body)
    if not entries:
        raise ValueError("{}: no decision sources found".format(source_dir))
    unreached = stray_files(source_dir)
    if unreached:
        raise ValueError(
            "{}: the canonical directory holds only {}, {} and D-NN.md; these "
            "would reach NEITHER generated output: {}".format(
                source_dir, PREAMBLE_FILE, META_FILE, unreached))
    return preamble, entries, meta


# --------------------------------------------------------------------------
# Rendering the two outputs
# --------------------------------------------------------------------------

def render_toc(entries: dict) -> str:
    lines = ["- **{}** {} {} _({})_".format(
        i, EM_DASH, entries[i][0]["title"], entries[i][0]["kind"])
        for i in numeric_order(entries)]
    return "\n".join([BEGIN_MARK, "", INDEX_HEADING, "", *lines, "", END_MARK])


def render_doc(preamble: str, entries: dict) -> str:
    sections = ['<a id="{}"></a>\n\n{}'.format(i.lower(), entries[i][1])
                for i in numeric_order(entries)]
    # The blank line between the preamble and the index is the generator's, so
    # the source file ends at one terminal newline rather than carrying
    # trailing whitespace that `git diff --check` flags (Sol, PR #64).
    return (preamble.rstrip("\n") + "\n\n" + render_toc(entries)
            + "\n\n" + "\n".join(sections))


def render_registry(entries: dict, meta: dict) -> str:
    decisions = [{field: entries[i][0][field] for field in FIELDS}
                 for i in numeric_order(entries)]
    payload = {"_comment": meta["registry_comment"], "decisions": decisions}
    return json.dumps(payload, indent=2, ensure_ascii=False) + "\n"


def generate(source_dir: Path = SOURCE_DIR):
    preamble, entries, meta = read_sources(source_dir)
    return render_doc(preamble, entries), render_registry(entries, meta)


# --------------------------------------------------------------------------
# One-time migration
# --------------------------------------------------------------------------

def split_document(doc: str, registry: dict):
    """The hand-maintained pair, decomposed into per-decision sources.

    Returns ``(preamble, entries)``. A body runs from its own ``## D-NN``
    heading to the line before the next section's block, so every authored byte
    lands in exactly one source and none lands in two. The only body bytes this
    rewrites are the first lines of D-76..D-89, which carried no heading title;
    they take the entry's existing registry title, which is already authored
    canonical prose exposed in the current index.
    """
    by_id = {entry["id"]: entry for entry in registry["decisions"]}
    lines = doc.split("\n")
    heads = [i for i, line in enumerate(lines) if SPLIT_HEADING_RE.match(line)]
    if not heads:
        raise ValueError("no decision headings found")

    def block_start(index: int) -> int:
        return index - 2 if ANCHOR_RE.match(lines[index - 2]) else index

    marker = LEGACY_BEGIN_MARK if LEGACY_BEGIN_MARK in doc else BEGIN_MARK
    preamble = doc[:doc.index(marker)]
    entries, retitled = {}, []
    for position, head in enumerate(heads):
        match = SPLIT_HEADING_RE.match(lines[head])
        decision_id = match.group(1)
        if decision_id not in by_id:
            raise ValueError(
                "{} is in the document but not the registry".format(decision_id))
        if position + 1 < len(heads):
            stop = block_start(heads[position + 1]) - 1
        else:
            stop = len(lines)
        body_lines = list(lines[head:stop])
        if match.group(2) is None:
            body_lines[0] = "## {} {} {}".format(
                decision_id, EM_DASH, by_id[decision_id]["title"])
            retitled.append(decision_id)
        body = "\n".join(body_lines).rstrip("\n") + "\n"
        entries[decision_id] = ({f: by_id[decision_id][f] for f in FIELDS}, body)
    unwritten = sorted(set(by_id) - set(entries))
    if unwritten:
        raise ValueError("registry entries with no section: {}".format(unwritten))
    return preamble, entries, retitled


def write_sources(source_dir: Path, preamble: str, entries: dict, meta: dict) -> None:
    source_dir.mkdir(parents=True, exist_ok=True)
    (source_dir / PREAMBLE_FILE).write_text(preamble, encoding="utf-8")
    (source_dir / META_FILE).write_text(
        json.dumps(meta, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    for decision_id, (fields, body) in entries.items():
        path = source_dir / (decision_id + ".md")
        path.write_text(source_text(fields, body), encoding="utf-8")
        # Re-read through the real parser: a file that cannot be parsed back
        # into the registry entry it came from is a lossy migration.
        parsed, parsed_body = parse_source(path)
        if parsed != fields or parsed_body != body:
            raise ValueError("{} does not re-parse to its source entry".format(path.name))


def run_split(args) -> int:
    existing = sorted(args.source_dir.glob("D-*.md")) if args.source_dir.is_dir() else []
    if existing:
        print("decisions: refusing to split, {} already holds {} sources; the "
              "migration has already run".format(args.source_dir, len(existing)),
              file=sys.stderr)
        return 1
    registry = json.loads(args.registry.read_text(encoding="utf-8"))
    preamble, entries, retitled = split_document(
        args.doc.read_text(encoding="utf-8"), registry)
    write_sources(args.source_dir, preamble, entries,
                  {"registry_comment": registry["_comment"]})
    print("decisions: split {} sections into {} ({} headings retitled: {})".format(
        len(entries), args.source_dir, len(retitled), " ".join(retitled)))
    return 0


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="fail when either generated output has drifted")
    parser.add_argument("--split", action="store_true",
                        help="one-time migration: build the sources from the "
                             "hand-maintained document and registry")
    parser.add_argument("--source-dir", type=Path, default=SOURCE_DIR)
    parser.add_argument("--doc", type=Path, default=DOC)
    parser.add_argument("--registry", type=Path, default=REGISTRY)
    args = parser.parse_args(argv)

    if args.split:
        return run_split(args)

    doc, registry = generate(args.source_dir)
    outputs = ((args.doc, doc), (args.registry, registry))
    if args.check:
        stale = [path.name for path, fresh in outputs
                 if path.read_text(encoding="utf-8") != fresh]
        if stale:
            print("decisions: STALE {} - run python3 python/scripts/"
                  "generate_decisions.py".format(", ".join(stale)), file=sys.stderr)
            return 1
        print("decisions: both generated outputs are up to date")
        return 0
    for path, fresh in outputs:
        path.write_text(fresh, encoding="utf-8")
    print("decisions: wrote {} and {}".format(args.doc.name, args.registry.name))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
