"""A whole building, generated by the ORACLE, driven through the PYTHON pipeline.

The successor to btap-necb/test/test_legacy_archetype_e2e.rb, ported for R6
(D-80). The Ruby gate did the same thing with the Ruby pipeline; that half
dies when the gems are deleted, but the valuable half does not.

Why it survives, and why it must: phase 1 generates the model with
openstudio-standards at legacy_pin/REF — the oracle, which R6 keeps — via
verification/oracle/gen_legacy_archetype.rb, the SAME script the Ruby gate
uses, so the two cannot drift. Phase 2 runs btap's own pipeline. That is the
python-drives / ruby-probes shape Leg C already proved.

This is the only gate that feeds the pipeline a model built by the LEGACY
PROTOTYPE GENERATOR. The frozen-scenario corpus comes from
generate_samples.py, so nothing else exercises what the oracle produces —
Kiva foundations being the concrete example: the corpus has none, and the
Kiva assertions below are exactly what a Python-generated sample can never
cover.

Skips loudly when the pin bundle is absent; LEGACY_PIN_REQUIRED=1 turns that
skip into a failure, matching every sibling parity gate.
"""

from __future__ import annotations

import hashlib
import json
import os
import shutil
import subprocess
import tempfile
import unittest
from pathlib import Path

from tests import support

REPO_ROOT = Path(__file__).resolve().parents[3]
GEN_SCRIPT = REPO_ROOT / "verification" / "oracle" / "gen_legacy_archetype.rb"
PIN_GEMFILE = REPO_ROOT / "legacy_pin" / "Gemfile"
PIN_REF = REPO_ROOT / "legacy_pin" / "REF"
FIXTURES = REPO_ROOT / "python" / "tests" / "fixtures" / "weather"
EPW = FIXTURES / "CAN_ON_Toronto.Intl.AP.716240_CWEC2020.epw"
DDY = FIXTURES / "CAN_ON_Toronto.Intl.AP.716240_CWEC2020.ddy"

TEMPLATE = "NECB2020"
BUILDING_TYPE = "SmallOffice"
PRIMARY_HEATING_FUEL = "Electricity"
ECM_SYSTEM_NAME = "NECB_Default"
#: Generation takes about a minute, so the .osm is cached under the system
#: temp dir keyed by a hash of the RECIPE — script bytes plus parameters — so
#: editing the generator invalidates it and nothing silently reuses a model
#: built by different code.
CACHE_DIR = Path(tempfile.gettempdir()) / "btap_necb_legacy_archetype_e2e_py"


def _generation_arguments(output: str, sizing: str) -> list[str]:
    return [output, sizing, TEMPLATE, BUILDING_TYPE, EPW.name,
            PRIMARY_HEATING_FUEL, ECM_SYSTEM_NAME]


def _recipe(*, pin_ref: bytes | None = None,
            epw: bytes | None = None) -> dict[str, object]:
    arguments = _generation_arguments("<OUTPUT_OSM>", "<SIZING_DIR>")
    return {
        "legacy_ref": (pin_ref if pin_ref is not None else PIN_REF.read_bytes()
                       ).decode("utf-8").strip(),
        "generator_sha256": hashlib.sha256(GEN_SCRIPT.read_bytes()).hexdigest(),
        "epw": EPW.name,
        "epw_sha256": hashlib.sha256(
            epw if epw is not None else EPW.read_bytes()).hexdigest(),
        "arguments": arguments,
    }


def _recipe_key(**overrides) -> str:
    h = hashlib.sha256()
    h.update(json.dumps(_recipe(**overrides), sort_keys=True,
                        separators=(",", ":")).encode("utf-8"))
    return h.hexdigest()[:16]


def _oracle_attestation() -> dict[str, str]:
    return {
        "legacy_ref": PIN_REF.read_text(encoding="utf-8").strip(),
        "template": TEMPLATE,
        "building_type": BUILDING_TYPE,
        "epw": EPW.name,
        "primary_heating_fuel": PRIMARY_HEATING_FUEL,
        "ecm_system_name": ECM_SYSTEM_NAME,
    }


def _pin_available() -> bool:
    if not PIN_GEMFILE.is_file():
        return False
    env = {**os.environ, "BUNDLE_GEMFILE": str(PIN_GEMFILE)}
    try:
        return subprocess.run(["bundle", "check"], env=env, cwd=str(REPO_ROOT),
                              capture_output=True, timeout=120).returncode == 0
    except (OSError, subprocess.SubprocessError):
        return False


def _generate() -> Path:
    """Phase 1, once per recipe: the ORACLE builds the archetype."""
    CACHE_DIR.mkdir(parents=True, exist_ok=True)
    osm = CACHE_DIR / f"legacy_{TEMPLATE.lower()}_{BUILDING_TYPE.lower()}_{_recipe_key()}.osm"
    sidecar = osm.with_suffix(".json")
    if (osm.is_file() and osm.stat().st_size > 0 and sidecar.is_file()
            and json.loads(sidecar.read_text(encoding="utf-8"))
            == _oracle_attestation()):
        return osm

    with tempfile.TemporaryDirectory(prefix="necb-legacy-gen-") as tmp:
        sizing = Path(tmp) / "sizing"
        sizing.mkdir()
        env = {**os.environ, "BUNDLE_GEMFILE": str(PIN_GEMFILE)}
        # LEGACY_PIN_REMOTE is inherited when set, so a developer pointing the
        # pin at a local checkout keeps that resolution instead of re-cloning
        # the ~4.6 GB fork in this child process.
        proc = subprocess.run(
            ["bundle", "exec", "ruby", str(GEN_SCRIPT),
             *_generation_arguments(str(osm), str(sizing))],
            env=env, cwd=str(REPO_ROOT), capture_output=True, text=True,
            timeout=1800)
        if proc.returncode != 0 or not osm.is_file() or osm.stat().st_size == 0:
            raise AssertionError(
                f"phase 1 ({TEMPLATE} {BUILDING_TYPE} generation) FAILED "
                f"(exit {proc.returncode})\n"
                f"--- last 6000 chars ---\n{(proc.stdout + proc.stderr)[-6000:]}")
        if (not sidecar.is_file()
                or json.loads(sidecar.read_text(encoding="utf-8"))
                != _oracle_attestation()):
            raise AssertionError("phase 1 wrote no valid oracle revision attestation")
    return osm


class TestLegacyArchetypeRecipe(unittest.TestCase):
    def test_cache_key_changes_with_pin(self):
        self.assertNotEqual(_recipe_key(pin_ref=b"first\n"),
                            _recipe_key(pin_ref=b"second\n"))

    def test_cache_key_changes_with_epw_content(self):
        self.assertNotEqual(_recipe_key(epw=b"first"),
                            _recipe_key(epw=b"second"))


@unittest.skipUnless(support.HAVE_SDK, "needs the OpenStudio SDK")
class TestLegacyArchetypeE2E(unittest.TestCase):
    osm: Path

    @classmethod
    def setUpClass(cls):
        if not _pin_available():
            msg = ("the pinned oracle is not bundled — "
                   "BUNDLE_GEMFILE=legacy_pin/Gemfile bundle install")
            if os.environ.get("LEGACY_PIN_REQUIRED") == "1":
                raise AssertionError(f"LEGACY_PIN_REQUIRED=1 but {msg}")
            raise unittest.SkipTest(msg)
        cls.osm = _generate()

    def _model(self):
        from btap._sdk import load_model
        return load_model(str(self.osm))

    def test_phase1_archetype_is_structurally_sane(self):
        """A real generated archetype, not a tiny or empty file."""
        self.assertGreater(self.osm.stat().st_size, 100_000,
                           "a real generated archetype OSM is not tiny")
        model = self._model()
        self.assertGreaterEqual(len(model.getThermalZones()), 5,
                                "the SmallOffice archetype is multi-zone")
        self.assertTrue(model.getAirLoopHVACs(),
                        "generation built real HVAC, not bare geometry")
        self.assertTrue(model.getSpaceTypes(),
                        "the model carries real space-type tags")

    @unittest.skipUnless(support.engine_available(), "needs an EnergyPlus engine")
    def test_week_run_is_kiva_compatible_and_reports_topline_numbers(self):
        """Phase 2: the PYTHON pipeline drives the oracle's model.

        A January week, not a year — shortened deliberately, and the pipeline
        must SAY it is not an annual determination rather than quietly
        reporting one.
        """
        from btap.costing.hvac import geometry as cost_geometry
        from btap.necb.compliance import performance_compliance

        model = self._model()
        run_dir = tempfile.mkdtemp(prefix="necb-e2e-week-py-")
        self.addCleanup(shutil.rmtree, run_dir, True)

        result = performance_compliance(
            model, vintage="2020", simulate="annual",
            weather={"epw": str(EPW), "ddy": str(DDY)},
            building={"storeys": cost_geometry.above_ground_storeys(model)},
            run_period={"begin_month": 1, "begin_day": 1,
                        "end_month": 1, "end_day": 7},
            run_dir=run_dir)

        report = result.report
        proposed = report["proposed"]["total_site_kwh"]
        reference = report["reference"]["total_site_kwh"]
        for label, kwh in (("proposed", proposed), ("reference", reference)):
            self.assertIsNotNone(kwh, f"{label} produced no total_site_kwh")
            self.assertTrue(float(kwh) > 0 and float(kwh) == float(kwh),
                            f"{label} week energy is finite and positive")
        self.assertIn(report["compliant"], (True, False),
                      "the comparison arithmetic produced a boolean")
        self.assertFalse(report["annual"],
                         "a shortened run is NOT an annual compliance determination")

        # Kiva: the reason this gate cannot be replaced by the corpus. The
        # legacy generator emits Foundation surfaces; the association and the
        # layer materials must both survive the pipeline, because EnergyPlus
        # fatals on a Kiva construction built from massless layers.
        reference_model = result.reference_model
        foundations = [s for s in reference_model.getSurfaces()
                       if s.outsideBoundaryCondition() == "Foundation"]
        self.assertTrue(foundations,
                        "the Python reference retains real Kiva Foundation surfaces")
        for surface in foundations:
            self.assertTrue(surface.adjacentFoundation().is_initialized(),
                            f"{surface.nameString()} retains its Kiva foundation")
            construction = surface.construction()
            self.assertTrue(construction.is_initialized(),
                            f"{surface.nameString()} retains its construction")
            layered = construction.get().to_LayeredConstruction()
            self.assertTrue(layered.is_initialized(),
                            f"{surface.nameString()} construction remains layered")
            for layer in layered.get().layers():
                self.assertTrue(
                    layer.to_StandardOpaqueMaterial().is_initialized(),
                    f"{surface.nameString()}: Kiva construction layer "
                    f"{layer.nameString()} must be a StandardOpaqueMaterial, "
                    "not massless")

        # Every simulation stage must have COMPLETED, with no severe errors.
        for stage in ("proposed_sizing", "reference_sizing",
                      "proposed_annual", "reference_annual"):
            err = Path(run_dir) / stage / "run" / "eplusout.err"
            self.assertTrue(err.is_file(), f"{stage} wrote eplusout.err")
            text = err.read_text(encoding="utf-8", errors="replace")
            self.assertIn("EnergyPlus Completed Successfully", text,
                          f"{stage} completed")
            self.assertIn("0 Severe Errors", text,
                          f"{stage} has zero severe errors")

        for artefact in ("audit.json", "report.json"):
            self.assertTrue((Path(run_dir) / artefact).is_file(),
                            f"{artefact} written")


if __name__ == "__main__":
    unittest.main()
