require_relative 'test_helper'
require 'tmpdir'
require 'digest'
require 'fileutils'
require 'json'
require 'shellwords'

# The first WHOLE-BUILDING cross-validation of the new NECB gem family
# (openstudio-hvac/envelope/lighting/shw/necb) against the LEGACY
# openstudio-standards NECB implementation living in this same monorepo
# (lib/openstudio-standards, NECB2020 class).
#
# THE VEHICLE: a REAL, fully-tagged NECB2020 archetype building generated by
# the known-good legacy code (Standard.build('NECB2020') +
# model_create_prototype_model), fed through the NEW pipeline
# (BtapNECB.performance_compliance) as the PROPOSED building.
#
# Phase 1 (legacy generation) has to run OUT OF PROCESS under the PINNED
# oracle (BUNDLE_GEMFILE=<repo root>/legacy_pin/Gemfile bundle exec ruby
# <script>) because legacy openstudio-standards pulls in a completely different
# gem graph than the SDK-only gems (this file's own process only has
# `openstudio` on the load path, not `openstudio-standards`). The generated .osm is cached
# under Dir.tmpdir keyed by a content hash of the generation recipe, so
# repeated local runs skip the legacy sizing run (~1 minute).
#
# RULES OF ENGAGEMENT for this suite: no lib/ modifications. Where the
# cross-validation exposes a real defect in the new gems, that is a FINDING —
# recorded here as a documented/characterized assertion (or, where that is
# not practical, a loud failure) — not something to quietly patch around.
class TestLegacyArchetypeE2E < Minitest::Test
  include FixtureHelper

  REPO_ROOT = File.expand_path('../..', __dir__)
  # The legacy oracle is no longer inside this repository — the gems were
  # extracted out of openstudio-standards. Phase 1 therefore runs under the
  # PINNED oracle (legacy_pin/Gemfile), exactly like every sibling *_parity.rb
  # suite, instead of requiring lib/openstudio-standards.rb from the enclosing
  # host checkout.
  LEGACY_PIN_DIR = File.join(REPO_ROOT, 'legacy_pin')
  LEGACY_PIN_GEMFILE = File.join(LEGACY_PIN_DIR, 'Gemfile')
  CACHE_DIR = File.join(Dir.tmpdir, 'btap_necb_legacy_archetype_e2e')
  BUILDING_TYPE = 'SmallOffice'
  TEMPLATE = 'NECB2020'
  GEN_EPW_BASENAME = 'CAN_ON_Toronto.Intl.AP.716240_CWEC2020.epw' # resolved from data/weather/ by legacy

  # Phase 1 generation recipe: legacy Standard.build + model_create_prototype_model,
  # driven by a small standalone script (no dependency on this test process'
  # load path — it requires lib/openstudio-standards.rb directly, exactly the
  # pattern used by the sibling gems' *_parity.rb tests).
  GEN_SCRIPT = <<~'RUBY'
    output_osm = ARGV[0] or raise 'usage: gen.rb <output_osm> <sizing_run_dir>'
    sizing_run_dir = ARGV[1] or raise 'usage: gen.rb <output_osm> <sizing_run_dir>'

    # Resolved by bundler from legacy_pin/Gemfile — the PINNED oracle revision,
    # loaded the same way every sibling *_parity.rb suite loads it.
    require 'openstudio-standards'

    std = Standard.build('NECB2020')
    model = std.model_create_prototype_model(
      template: 'NECB2020',
      building_type: 'SmallOffice',
      epw_file: 'CAN_ON_Toronto.Intl.AP.716240_CWEC2020.epw',
      sizing_run_dir: sizing_run_dir
    )

    if model.nil? || model.is_a?(FalseClass)
      warn "GENERATION FAILED: model_create_prototype_model returned #{model.inspect}"
      exit 1
    end

    model.save(OpenStudio::Path.new(output_osm), true)
    puts "OK osm=#{output_osm}"
  RUBY

  # Availability means the oracle is actually BUNDLED, not merely that the pin
  # exists. legacy_pin/Gemfile is committed, so testing for it is always true
  # and the guard would not guard — Phase 1 then shells out and dies trying to
  # resolve the oracle, which is what CI hit on the first run. `bundle check`
  # verifies the Gemfile's dependencies are satisfied without installing them.
  def self.legacy_available?
    return @legacy_available unless @legacy_available.nil?

    @legacy_available =
      File.exist?(LEGACY_PIN_GEMFILE) &&
      system("BUNDLE_GEMFILE=#{LEGACY_PIN_GEMFILE.shellescape} bundle check > /dev/null 2>&1")
  end

  # The pinned oracle revision keys the cache to the LIBRARY that generates the
  # archetype — without it, a legacy change (e.g. the #2119 SHW/daylighting
  # fixes merged 2026-08-10) silently reuses a stale pre-change OSM, because
  # the script text and its arguments don't change when the library does.
  #
  # This was the host repo's `HEAD:lib/openstudio-standards` subtree SHA. That
  # command returns EMPTY once the gems live in their own repository, which
  # would have degraded the cache key silently; legacy_pin/REF states the same
  # identity explicitly and travels with the gems. Bumping the pin invalidates
  # the cache, which is exactly the intent.
  def self.legacy_sha
    @legacy_sha ||= File.read(File.join(LEGACY_PIN_DIR, 'REF')).strip
  end

  def self.cache_key
    @cache_key ||= Digest::SHA256.hexdigest(
      [GEN_SCRIPT, TEMPLATE, BUILDING_TYPE, GEN_EPW_BASENAME, legacy_sha].join('|')
    )[0, 24]
  end

  def self.cached_osm_path
    File.join(CACHE_DIR, "legacy_#{TEMPLATE.downcase}_#{BUILDING_TYPE.downcase}_#{cache_key}.osm")
  end

  # Runs Phase 1 exactly once per cache key (across ALL local runs — the .osm
  # persists under Dir.tmpdir). Raises with the full generation log on failure
  # (a precise obstacle report is a valid deliverable; we do not thrash).
  def self.ensure_legacy_archetype!
    osm = cached_osm_path
    return osm if File.exist?(osm) && File.size(osm).positive?

    FileUtils.mkdir_p(CACHE_DIR)
    Dir.mktmpdir('necb-legacy-gen-') do |dir|
      script_path = File.join(dir, 'gen_legacy_archetype.rb')
      File.write(script_path, GEN_SCRIPT)
      sizing_dir = File.join(dir, 'sizing')
      FileUtils.mkdir_p(sizing_dir)
      log_path = File.join(dir, 'gen.log')

      # LEGACY_PIN_REMOTE is passed through when set, so a developer who pointed
      # the pin at a local openstudio-standards checkout keeps that resolution
      # here — otherwise this child process would re-resolve against the
      # Gemfile's default remote and re-clone the fork.
      remote = ENV['LEGACY_PIN_REMOTE']
      env = +"BUNDLE_GEMFILE=#{LEGACY_PIN_GEMFILE.shellescape} "
      env << "LEGACY_PIN_REMOTE=#{remote.shellescape} " if remote
      cmd = "#{env}timeout 1200 bundle exec ruby " \
            "#{script_path.shellescape} #{osm.shellescape} #{sizing_dir.shellescape} " \
            "> #{log_path.shellescape} 2>&1"
      ok = system(cmd)
      status = $?
      log = File.exist?(log_path) ? File.read(log_path) : '(no log captured)'

      unless ok && File.exist?(osm) && File.size(osm).positive?
        raise "Phase 1 (legacy NECB2020 SmallOffice archetype generation) FAILED " \
              "(exit #{status&.exitstatus.inspect}).\ncommand: #{cmd}\n" \
              "--- last 6000 chars of generation log ---\n#{(log[-6000..] || log)}"
      end
    end
    osm
  end

  def setup
    skip 'bundler/legacy openstudio-standards not available in this environment' unless self.class.legacy_available?
    skip 'openstudio CLI not available' unless openstudio_cli?
  end

  # ---------------------------------------------------------------------
  # PHASE 1 — legacy archetype generation (real building, real BTAP tags)
  # ---------------------------------------------------------------------
  def test_phase1_legacy_archetype_generates_and_is_structurally_sane
    osm = self.class.ensure_legacy_archetype!
    assert File.exist?(osm), "[RAN] legacy generation script did not produce #{osm}"
    assert_operator File.size(osm), :>, 100_000, 'a real generated archetype OSM is not a tiny/empty file'

    model = OpenStudio::Model::Model.load(OpenStudio::Path.new(osm)).get
    zones = model.getThermalZones
    assert_operator zones.size, :>=, 5, '[RAN] legacy SmallOffice archetype has the expected multi-zone geometry'

    air_loops = model.getAirLoopHVACs
    refute_empty air_loops, '[RAN] legacy generation built real HVAC (air loops), not bare geometry'

    space_types = model.getSpaceTypes.select { |st| st.spaces.any? }
    refute_empty space_types, '[RAN] legacy model carries real space-type tags'
    tagged = space_types.map do |st|
      [st.standardsBuildingType.is_initialized ? st.standardsBuildingType.get : nil,
       st.standardsSpaceType.is_initialized ? st.standardsSpaceType.get : nil]
    end
    puts "[RAN] Phase 1: legacy NECB2020 SmallOffice archetype — #{zones.size} zones, " \
         "#{air_loops.size} air loops, space types: #{tagged.inspect}"
  end

  # ---------------------------------------------------------------------
  # PHASE 2 — pre-flight + value-level cross-checks against the NEW pipeline.
  # Runs with simulate: :none so the reference envelope/lighting/HVAC
  # transforms all execute (they are unconditional in the pipeline) without
  # needing a clean EnergyPlus run — isolates the STRUCTURAL/VALUE checks from
  # the E+-execution finding captured separately below.
  # ---------------------------------------------------------------------
  def test_phase2_preflight_resolves_and_value_crosschecks_match_expected
    osm = self.class.ensure_legacy_archetype!
    model = OpenStudio::Model::Model.load(OpenStudio::Path.new(osm)).get

    zone_types = OpenStudioHVAC::NECB.zone_space_types(model)
    storeys = OpenStudioHVAC::Costing::Geometry.above_ground_storeys(model)
    puts "[RAN] derived building facts: storeys=#{storeys}, zone_types=#{zone_types}"

    # FIRST FINDING CLASS: pre-flight space-type resolution. The legacy
    # NECB2020 SmallOffice archetype tags its office space type
    # 'Space Function' / 'Office enclosed <= 25 m2' (auto-zoning splits by
    # floor area) — this IS a catalog name (openstudio-loads NECB 2020 table),
    # so pre-flight is expected to pass without any retag.
    dir = Dir.mktmpdir('necb-e2e-preflight-')
    result = nil
    retags = []
    begin
      result = BtapNECB.performance_compliance(
        model, vintage: '2020', simulate: :none, hdd: 3890,
        building: { storeys: storeys, zone_types: zone_types },
        run_dir: dir
      )
    rescue ArgumentError => e
      raise unless e.message.include?('pre-flight FAILED')

      # Contingency path required by the cross-validation brief: retag every
      # unresolved space type to the nearest catalog name and continue,
      # RECORDING every retag. Not expected to trigger for this archetype
      # (see above), but implemented per spec in case a different vintage /
      # building type surfaces a genuine legacy-name vs catalog-name gap.
      puts "[FINDING] pre-flight FAILED on first attempt:\n#{e.message}"
      retags = retag_unresolved_space_types!(model, '2020')
      raise "pre-flight failed and no catalog-name suggestions could be derived:\n#{e.message}" if retags.empty?

      retags.each { |r| puts "[RETAG] #{r[:space_type]}: '#{r[:old]}' -> '#{r[:new]}' (#{r[:spaces]} space(s))" }
      result = BtapNECB.performance_compliance(
        model, vintage: '2020', simulate: :none, hdd: 3890,
        building: { storeys: storeys, zone_types: OpenStudioHVAC::NECB.zone_space_types(model) },
        run_dir: dir
      )
    end
    assert retags.empty?, 'expected the real legacy archetype tags to resolve cleanly against the catalog ' \
                          "(no retags needed) — got: #{retags.inspect}"
    puts '[RAN] pre-flight PASSED with no retags: legacy NECB2020 SmallOffice space types ' \
         "('Space Function' / 'Office enclosed <= 25 m2') resolve directly against the openstudio-loads catalog"

    reference = result.reference_model
    proposed = result.proposed_model

    # ---- (a) reference exterior wall U-value vs NECB 2020 Table 3.2.2.2, HDD bin ----
    # Expected value read directly from openstudio-envelope's vendored rule data
    # (rule: first bin where hdd < key), NOT hardcoded.
    envelope_rules = JSON.parse(File.read(File.join(
      REPO_ROOT, 'openstudio-envelope/lib/openstudio_envelope/data/necb/envelope_rules_2020.json'
    )))
    wall_bins = envelope_rules.fetch('u_values').fetch('outdoors').fetch('wall')
    hdd = 3890
    expected_wall_u = wall_bins.sort_by { |k, _| k.to_i }.find { |k, _| hdd < k.to_i }.last

    wall = reference.getSurfaces.find { |s| s.outsideBoundaryCondition == 'Outdoors' && s.surfaceType == 'Wall' }
    refute_nil wall, 'reference model has at least one above-ground exterior wall'
    got_wall_u = wall.construction.get.to_Construction.get.thermalConductance.to_f
    # D-23: envelope_rules table values are OVERALL U (incl. films, per 1.4.1.2);
    # the applied construction is CONSTRUCTION-ONLY conductance. Convert to overall
    # before comparing (mirrors openstudio-envelope/test/test_prescriptive.rb:135-138).
    r_films = BtapModeling::Constructions.film_r('wall', 'outdoors')
    got_overall_u = 1.0 / ((1.0 / got_wall_u) + r_films)
    puts "[RAN] (a) reference exterior wall U-value: expected #{expected_wall_u} W/m2K " \
         "(NECB 2020 Table 3.2.2.2, HDD=#{hdd} -> bin #{wall_bins.sort_by { |k, _| k.to_i }.find { |k, _| hdd < k.to_i }.first}), " \
         "got construction-only #{got_wall_u.round(6)} -> overall #{got_overall_u.round(6)}"
    assert_in_delta expected_wall_u, got_overall_u, 1e-3,
                    'reference exterior wall OVERALL U-value does not match the NECB 2020 Table 3.2.2.2 HDD-bin value'

    # ---- (b) reference LPD for 'Office enclosed <= 25 m2' vs catalog (W/ft2 -> W/m2) ----
    catalog = JSON.parse(File.read(File.join(
      REPO_ROOT, 'openstudio-loads/lib/openstudio_loads/data/necb/space_types_2020.json'
    )))['table']
    row = catalog.find { |r| r['building_type'] == 'Space Function' && r['space_type'] == 'Office enclosed <= 25 m2' }
    refute_nil row, 'catalog carries the Office enclosed <= 25 m2 space type'
    expected_lpd_w_m2 = OpenStudio.convert(row['lighting_per_area'].to_f, 'W/ft^2', 'W/m^2').get

    st = reference.getSpaceTypes.find do |s|
      s.standardsSpaceType.is_initialized && s.standardsSpaceType.get == 'Office enclosed <= 25 m2'
    end
    refute_nil st, 'reference model carries the Office enclosed <= 25 m2 space type'
    # lightingPowerPerFloorArea returns an OptionalDouble — unwrap before use
    # (same contract as report/model_query.rb's ModelQuery.unwrap).
    lpd_opt = st.lightingPowerPerFloorArea
    got_lpd = lpd_opt.is_a?(Numeric) ? lpd_opt : (lpd_opt.is_initialized ? lpd_opt.get : nil)
    refute_nil got_lpd, 'reference space type has a lighting power density set'
    puts "[RAN] (b) reference LPD 'Office enclosed <= 25 m2': expected #{expected_lpd_w_m2.round(4)} W/m2 " \
         "(catalog #{row['lighting_per_area']} W/ft2), got #{got_lpd.round(4)} W/m2"
    assert_in_delta expected_lpd_w_m2, got_lpd, 1e-2,
                    'reference LPD does not match the catalog lighting_per_area (W/ft2 -> W/m2)'

    # ---- counts: legacy-built systems (proposed) vs new reference selection ----
    puts "[RAN] THIRD (structural): proposed (legacy) air loops=#{proposed.getAirLoopHVACs.size} " \
         "(#{proposed.getAirLoopHVACs.map(&:nameString).uniq.first(1)}...), " \
         "reference (new) air loops=#{reference.getAirLoopHVACs.size} " \
         "(#{reference.getAirLoopHVACs.map(&:nameString).uniq.first(1)}...)"
    puts "[RAN] THIRD (structural): proposed ERV/HX count=#{proposed.getHeatExchangerAirToAirSensibleAndLatents.size}, " \
         "reference ERV/HX count=#{reference.getHeatExchangerAirToAirSensibleAndLatents.size} " \
         '(proposed ERVs are the legacy erv_package recipe; the reference 5.2.10.1 Table-trigger determination ' \
         'is POST-SIZING and therefore skipped under simulate: :none — the annual phase-2 run evaluates it on ' \
         'sized flows, where the 12.8%-OA continuous loop gains an ERV under Table 5.2.10.1.-B)'
  ensure
    FileUtils.remove_entry(dir) if dir && File.exist?(dir)
  end

  # ---------------------------------------------------------------------
  # PHASE 2 (continued) — the annual run + topline numbers. This is where the
  # whole-building cross-validation earns its keep: the legacy archetype's
  # REAL geometry carries Kiva slab-on-grade Foundation objects (5 zones on
  # one shared OS:Foundation:Kiva), which openstudio-envelope's NECB reference
  # envelope's lightweight-construction transform
  # (openstudio-envelope/lib/openstudio_envelope/necb/reference.rb, method
  # apply_lightweight_construction, ~line 137) does not special-case: it
  # rebuilds EVERY opaque surface's construction — including Foundation-
  # boundary ground floors — as a single-layer OpenStudio::Model::
  # MasslessOpaqueMaterial. EnergyPlus's Kiva foundation calculation requires
  # a "regular" (full R+thickness+conductivity) Material on any surface whose
  # Outside Boundary Condition is 'Foundation'; a NoMass/massless material
  # there is a FATAL error ("constructions referenced by surfaces with a
  # 'Foundation' Outside Boundary Condition must use only regular material
  # objects"), so the reference building's SIZING run (required before ANY
  # annual comparison — simulate: :sizing hits the identical failure) never
  # completes. No hand-built gem fixture in openstudio-envelope's own test
  # suite exercises a Kiva Foundation object, so this defect was invisible
  # until fed a real, legacy-generated archetype — precisely the point of
  # this cross-validation.
  #
  # RULES: no lib/ modifications. This test CHARACTERIZES the current defect
  # (captures a stable green assertion pinned to the exact failure) rather
  # than papering over it. If/when the defect is fixed upstream in
  # openstudio-envelope, this assert_raises will start failing — that failure
  # is the signal to convert this test into the full annual/topline
  # cross-check the `else` branch below already knows how to do.
  # ---------------------------------------------------------------------
  def test_phase2_annual_run_hits_kiva_foundation_defect_or_reports_topline_numbers
    osm = self.class.ensure_legacy_archetype!
    model = OpenStudio::Model::Model.load(OpenStudio::Path.new(osm)).get
    zone_types = OpenStudioHVAC::NECB.zone_space_types(model)
    storeys = OpenStudioHVAC::Costing::Geometry.above_ground_storeys(model)

    dir = Dir.mktmpdir('necb-e2e-annual-')
    error = nil
    result = nil
    begin
      result = BtapNECB.performance_compliance(
        model, vintage: '2020', simulate: :annual,
        weather: { epw: EPW, ddy: DDY },
        building: { storeys: storeys, zone_types: zone_types },
        run_period: { begin_month: 1, begin_day: 1, end_month: 1, end_day: 7 },
        run_dir: dir
      )
    rescue RuntimeError => e
      error = e
    end

    if error
      msg = error.message
      # Runner.run_energyplus! only surfaces the FIRST '*Fatal*' line from
      # eplusout.err in the raised message; the fuller root-cause detail
      # (which construction, which surface, why) lives in the err file on
      # disk — read it for the complete, precise characterization.
      assert_match(/Kiva/i, msg, 'expected the documented Kiva-foundation failure mode')
      err_path = File.join(dir, 'reference_sizing', 'run', 'eplusout.err')
      full_err = File.exist?(err_path) ? File.read(err_path) : ''
      assert_match(/Foundation/i, full_err, 'expected the Foundation-boundary root cause in eplusout.err')
      assert_match(/regular material objects/i, full_err,
                   'expected the "must use only regular material objects" root cause in eplusout.err')
      puts "[FINDING] [RAN] Phase 2 annual run FAILED as characterized — openstudio-envelope's " \
           'reference-envelope lightweight-construction transform is incompatible with Kiva ' \
           "Foundation-boundary ground floors (real legacy archetype geometry). Raised: #{msg}\n" \
           "Root cause (eplusout.err):\n#{full_err[/\*\* Severe.*Kiva.*terminates\./m] || full_err[-1500..] || full_err}"

      # even on failure, the audit trail must be flushed (compliance.rb's
      # flush_on_failure) — verifying the pipeline's diagnostics contract held
      # up through a real, unanticipated whole-building failure.
      assert File.exist?(File.join(dir, 'audit.txt')), 'audit.txt flushed despite the failure'
      assert File.exist?(File.join(dir, 'report.json')), 'report.json flushed despite the failure'
      audit_txt = File.read(File.join(dir, 'audit.txt'))
      assert_includes audit_txt, 'ABORTED', 'the abort is recorded in the audit trail'
      puts '[RAN] audit.txt / report.json flushed correctly despite the mid-pipeline failure ' \
           '(proposed sizing + reference HVAC/envelope/lighting/SHW all completed before the crash)'
    else
      # The defect is fixed (or never manifests in this environment) — report
      # the full topline cross-check the brief asked for.
      report = result.report
      puts "[RAN] Phase 2 annual run SUCCEEDED — topline numbers:\n" \
           "  proposed total_site_kwh = #{report.dig('proposed', 'total_site_kwh')}\n" \
           "  reference total_site_kwh = #{report.dig('reference', 'total_site_kwh')}\n" \
           "  compliant = #{report['compliant']}\n" \
           "  tier = #{report['tier']}"
      refute_nil report.dig('proposed', 'total_site_kwh'), 'proposed annual energy computed'
      refute_nil report.dig('reference', 'total_site_kwh'), 'reference annual energy computed'
      refute_nil report['compliant'], 'a compliant verdict (either way) was determined'
    end
  ensure
    FileUtils.remove_entry(dir) if dir && File.exist?(dir)
  end

  private

  # Contingency retag helper (spec: "retag the offending space types to the
  # nearest catalog name and continue, RECORDING every retag"). Uses the same
  # public catalog lookup / suggestion API compliance.rb's own pre-flight gate
  # uses (OpenStudioLoads::NECB::SpaceTypes / BtapNECB::Compliance.
  # suggest_space_types), so the suggestions are identical to what the raised
  # ArgumentError already reports.
  def retag_unresolved_space_types!(model, vintage)
    data_vintage = OpenStudioLoads::NECB.data_vintage(vintage)
    catalog = OpenStudioLoads::NECB.table(data_vintage, 'space_types')
    retags = []
    model.getSpaceTypes.each do |space_type|
      next if space_type.spaces.empty?

      bt = space_type.standardsBuildingType.is_initialized ? space_type.standardsBuildingType.get : nil
      st = space_type.standardsSpaceType.is_initialized ? space_type.standardsSpaceType.get : nil
      next if st.nil? || st.downcase.include?('plenum')

      record = bt && OpenStudioLoads::NECB::SpaceTypes.find(building_type: bt, space_type: st, vintage: data_vintage)
      next unless record.nil? || OpenStudioLoads::NECB::SpaceTypes.undefined?(record)

      suggestions = BtapNECB::Compliance.suggest_space_types(st, catalog)
      next if suggestions.empty?

      new_name = suggestions.first.delete("'")
      retags << { space_type: space_type.nameString, old: st, new: new_name, spaces: space_type.spaces.size }
      space_type.setStandardsBuildingType('Space Function')
      space_type.setStandardsSpaceType(new_name)
    end
    retags
  end
end
